### ISSUE TITLE
Clicking on **any descendant** of an element with `mv-action` triggers the corresponding action

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#1036]
Initially found by @LeaVerou.

In many cases, this behavior is not desirable. Especially when one clicks a form element inside an element with `mv-action`.

Testcase: https://codepen.io/dmitrysharabin/pen/eYweRPy

This happens because we run the corresponding action not on the target element itself but on the closest element with a `mv-action` attribute:
https://github.com/mavoweb/mavo/blob/dfe31493f767f1b20b5d34f3ff5c8666d117964b/src/actions.js#L8

**Comment by LeaVerou** [comment]
> This happens because we run the corresponding action not on the target element itself but on the closest element with a `mv-action` attribute:
> 
> https://github.com/mavoweb/mavo/blob/dfe31493f767f1b20b5d34f3ff5c8666d117964b/src/actions.js#L8

That's not a problem, of course we want to run it on the element that actually has an `mv-action` attribute! Otherwise the results would be completely unpredictable.

However, we first need to filter based on `evt.target` and ignore clicks on Mavo controls. I think even a test as simple as `evt.target.closest(".mv-ui")` would be a huge improvement.

**Comment by DmitrySharabin** [comment]
> However, we first need to filter based on `evt.target` and ignore clicks on Mavo controls. I think even a test as simple as `evt.target.closest(".mv-ui")` would be a huge improvement.

This also means that we will ignore generated buttons with both the `mv-ui` class and `mv-action` attribute and the corresponding actions will not be triggered. 

Ignoring `evt.target.closest(".mv-editor")` helps in some cases, but opening, e.g., a built-in color picker, also triggers the action and is not covered by the selector.

Ensure what can be a quick fix here. 🤷‍♂️

**Comment by LeaVerou** [comment]
> > However, we first need to filter based on `evt.target` and ignore clicks on Mavo controls. I think even a test as simple as `evt.target.closest(".mv-ui")` would be a huge improvement.
> 
> This also means that we will ignore generated buttons with both the `mv-ui` class and `mv-action` attribute and the corresponding actions will not be triggered (e.g., the Add list item button won't work).
> 
> Ignoring `evt.target.closest(".mv-editor")` helps in some cases, but opening, e.g., a built-in color picker, also triggers the action and is not covered by the selector.
> 
> Ensure what can be a quick fix here. 🤷‍♂️

Good point. How about this: we ignore clicks from elements *inside* an `.mv-ui` element UNLESS the `[mv-action]` element is closer than the `.mv-ui` element.

**Comment by DmitrySharabin** [comment]
> Good point. How about this: we ignore clicks from elements _inside_ an `.mv-ui` element UNLESS the `[mv-action]` element is closer than the `.mv-ui` element.

Nice idea. I will give it a try. Thanks!
