### ISSUE TITLE
Allow buttons to call backend-defined mutation procedures

### ISSUE THREAD

**Issue by mattmccutchen** [mavoweb/mavo#107]
Object Spreadsheets has mutation procedures that run on the server.  We'd like to be able to set up a button in Mavo to call a procedure with arguments taken from particular input fields.  Mavo should pass the procedure name and arguments to the Object Spreadsheets backend connector to perform the call.  The resulting mutations would come back to Mavo via the change notification API of #105.

(Split out from #81.)

**Comment by LeaVerou** [comment]
Closing as data actions do this much more easily on the client, and the JS API can always be used by more advanced users to do more custom things.
