### ISSUE TITLE
Allow other API calls to Github

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#138]
Since we have a Github backend, it would be cool to allow other API calls as long as people use the right property names (e.g. to show directory listings!). It's all JSON anyway, so it should be easy to support and it will be very nice functionality for power users.

**Comment by jenil** [comment]
Hey, Can you show a sample of how to use this?

**Comment by LeaVerou** [comment]
We use it here for directory listing: https://test.mavo.io
