### ISSUE TITLE
SVG Demo combobox bug

### ISSUE THREAD

**Issue by jdmb77** [mavoweb/mavo#178]
In Chrome 58.0.3029.96 the SVG Builder demo http://mavo.io/demos/svgpath/ combobox values do not show when it is active. If you hover over the opened combo you can see that there are values there, just not visible until you hover the item. Line 190 in style.css sets the color value to white. It does seem to display properly in FireFox. Mavo is looking pretty cool as a dev tool. Thanks Lea V!

**Comment by LeaVerou** [comment]
Thanks! Looks like a Windows issue, it displays ok on OSX. On it!

**Comment by LeaVerou** [comment]
Fixed via https://github.com/mavoweb/mavo.io/commit/7cdc0e7f33d4a087f909c9f26268b3773116d215
