### ISSUE TITLE
time.datetime is shifted by one day

### ISSUE THREAD

**Issue by pchampin** [mavoweb/mavo#180]
I'm using Firefox 53.0.2 under Linux, and the demo http://mavo.io/demos/foodie/ is buggy:
the displayed date is one day sooner than the stored date.

E.g. the default value is "2016-03-15", but "14 Mar 2016" is displayed.

**Comment by LeaVerou** [comment]
Huh, I thought I had fixed that. Which timezone are you in?

**Comment by pchampin** [comment]
UTC+0200 (France, Daylight Saving Time)

**Comment by Zatnosk** [comment]
I have the same issue as pchampin, from the same timezone, but only after* 30-10-2017 and before* 26-03-2017, both inclusive. It seems to be a daylight saving bug.
* in the year 2017, 2016 changes on other dates.

**Comment by LeaVerou** [comment]
Could you please check if it's fixed now?

**Comment by Zatnosk** [comment]
The bug is fixed for me :)

**Comment by pchampin** [comment]
Yep, fixed for me as well.

**Comment by LeaVerou** [comment]
Woohoo!
