### ISSUE TITLE
Unable to type letter ś while editing

### ISSUE THREAD

**Issue by fusilli** [mavoweb/mavo#181]
It is impossible to write letter ś (alt + s), which is used in Polish.

**Comment by LeaVerou** [comment]
What happens instead?

**Comment by fusilli** [comment]
It seems that "alt + s" is another keyboard shortcut for saving. I guess it should only be "ctrl + s".

**Comment by LeaVerou** [comment]
But it isn't, that's the weird thing. :(
Which OS is this?

**Comment by fusilli** [comment]
Windows 7

**Comment by LeaVerou** [comment]
Is this a special keyboard layout or anything?

**Comment by fusilli** [comment]
Not sure what exactly you are asking, but my keyboard in Windows is set to "Polish (Programmers) Keyboard Layout" and my keyboard is logitech classic keyboard 200. 
I do not have similar issues anywhere else.

**Comment by ashsearle** [comment]
@fusilli Are you using the AltGr key to type the ś (this is normally the Alt key on the right-hand-side of the keyboard)?

@LeaVerou reading a couple of answers from stackoverflow ([1](https://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press), [2](https://stackoverflow.com/questions/17857404/why-does-alt-gr-have-the-same-keycode-as-ctrl)), you _probably_ need to change [this line](https://github.com/mavoweb/mavo/blob/8e45ce76ee855d46f38de0ac1d17cbc806affac8/src/mavo.js#L232):

```js
if (this.permissions.save && evt.keyCode == 83 && evt[_.superKey]) {
```

To something like:
```js
if (this.permissions.save && evt.keyCode == 83 && evt[_.superKey] && !evt.altKey) {
```

It feels nasty though, and I don't want to submit PR before confirming AltGr is the cause.

**Comment by fusilli** [comment]
Yes, the right alt key, and yes, it solves this problem! :)

**Comment by LeaVerou** [comment]
@ashsearle ah, excellent! I was wondering how on earth can `evt.ctrlKey` can be true for alt!
Do you want to submit a pull request so you can be credited properly for this fix?

**Comment by LeaVerou** [comment]
Should be fixed now, please let us know if not!
