### ISSUE TITLE
Connect a database?

### ISSUE THREAD

**Issue by aolko** [mavoweb/mavo#184]
Is it possible to connect a database like [Arango](https://www.arangodb.com)/[Taffy](https://github.com/typicaljoe/taffydb)/[Rx](https://github.com/pubkey/rxdb)/[Pouch](https://github.com/pouchdb/pouchdb)
?

**Comment by mxuribe** [comment]
+1 on Pouch support!

**Comment by LeaVerou** [comment]
@lizziew is doing some work on a Firebase backend plugin. Hopefully someone will work on a plugin for these databases?

**Comment by LeaVerou** [comment]
This issue was moved to mavoweb/plugins#3
