### ISSUE TITLE
Footer links at plugins.mavo.io result in 404 not found

### ISSUE THREAD

**Issue by terabaud** [mavoweb/mavo#185]
When you are at the [plugins page](https://plugins.mavo.io/) and you want to get back to, eg. "Getting started" via the footer links, you get a `404 Not Found` error: 

The footer links mistakenly contain the plugins.mavo.io subdomain: https://plugins.mavo.io/docs/... instead of https://mavo.io/docs/...

**Comment by LeaVerou** [comment]
Why did you close this? It's a legit bug :)

**Comment by LeaVerou** [comment]
It *is* in the wrong repo however…

**Comment by LeaVerou** [comment]
This issue was moved to mavoweb/plugins#8
