### ISSUE TITLE
Support other data back-ends such as remoteStorage, Standard File, etc. 

### ISSUE THREAD

**Issue by mxuribe** [mavoweb/mavo#187]
This is an awesome project, kudos and congrats to you!  

Beyond supporting localStorage, github, and dropbox, please consider supporting other common and standard data back-ends that would allow for **self-hosting**, such as for example remoteStorage (https://wiki.remotestorage.io/Protocol), Standard File (https://standardfile.org/#protocol-specification), etc. 

Again, kudos and congrats; I look forward to using this!

**Comment by LeaVerou** [comment]
This issue was moved to mavoweb/plugins#5
