### ISSUE TITLE
MongoDB as a storage backend

### ISSUE THREAD

**Issue by brundonsmith** [mavoweb/mavo#189]
When I first started playing with this I quickly thought, "this is amazingly powerful syntax; even as a professional web developer I'd consider using this for projects". Then it occurred to me that it would need to be possible to hook up a custom API for storage, which, I can see by a comment on the Smashing Magazine article, is apparently possible. But then I thought, "well, maybe all I actually need is a database". Since the data is already JSON, might it be possible to create a MongoDB storage option? That way it wouldn't require any custom code to hook up to an API, it would just work.

For clarity, the use case for this would be having multiple users, each of whose data is private to the other users. Github and Dropbox allow user permissions for editing, but all data is necessarily public.

Thoughts? Is this on the roadmap? Is it even feasible?

**Comment by aolko** [comment]
Mongo ~ Arango https://github.com/mavoweb/plugins/issues/3

**Comment by LeaVerou** [comment]
This issue was moved to mavoweb/plugins#9
