### ISSUE TITLE
Property can't be set when using the minified version

### ISSUE THREAD

**Issue by SteeveDroz** [mavoweb/mavo#191]
When using `mavo.js`, everything works fine, but when using `mavo.min.js` and entering Edit mode, the content of a property is cleared upon hover and I can't type anything.

Reloading the page shows only the last character I've typed.

Same results with **Firefox 53** and **Chrome 58**.

# My code

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css">
    <!-- Works fine with https://get.mavo.io/mavo.js -->
    <script src="https://get.mavo.io/mavo.min.js"></script>
    <title>Mavo test</title>
  </head>
  <body>
    <div mv-app="test" mv-storage="local" mv-autosave="0">
      <div>
        <article property="element" mv-multiple>
            <h1 property="title">Title</h1>
            <span property="content">Content</span>
        </article>
      </div>
    </div>
  </body>
</html>
```

**Comment by LeaVerou** [comment]
Thanks for reporting!
I wonder if this is a bug with our minifier, https://github.com/babel/babili but who could track it down… :/
Does it happen with `mavo.es5.min.js`?

**Comment by SteeveDroz** [comment]
Yes, same bug with `https://get.mavo.io/mavo.es5.min.js`. Sorry!

**Comment by SteeveDroz** [comment]
It is probably the minifier, `https://get.mavo.io/mavo.es5.js` works fine.

**Comment by LeaVerou** [comment]
Damn, I've never encountered this before, not sure where to even start debugging this.
I could switch to Uglify for the es5 version, but Babili is pretty much the only ES6-aware minifier out there :/

**Comment by congomonster** [comment]
Same here for me. Only on the not minified version i can make edits. Please fix this bug because starters like me are easily afraid. Luckily i found this issue and could use the non minified version.

**Comment by karger** [comment]
maybe should take down the minified version till we track down the problem.

**Comment by LeaVerou** [comment]
Yeah, good point, done.

**Comment by abo3desa** [comment]
i think there is nothing wrong with Babili maybe you should minify before merge with lib files
i tried this and worked
```gulp.task("minify", function() {
	return merge(gulp.src("lib/*.js")
	, gulp.src(mavo)
	.pipe(babel({
			"presets": [
				["babili"]
			]
		}))
	)
		.pipe(sourcemaps.init())
		.pipe(concat("mavo.min.js"))
		.pipe(sourcemaps.write("maps"))
		.pipe(gulp.dest("dist"));
});
```
you should have tests because a lot of things like this are coming

**Comment by LeaVerou** [comment]
> you should have tests because a lot of things like this are coming

There's an entire testsuite at https://test.mavo.io but it doesn't test the minified files…

**Comment by LeaVerou** [comment]
Thanks for fixing the issue! Can you send a pull request so you're properly credited for this fix?
