### ISSUE TITLE
GitLabs as Storage Option

### ISSUE THREAD

**Issue by craigcecil** [mavoweb/mavo#193]
First, a big congrats on Mavo. This is a fantastic library, especially for prototyping. However, our UX group of over 40 designers would love to use Mavo, especially for testing our designs, but we use GitLabs, and not Github, since GitLabs allows us to have free private repos.

Is this something that you could easily add? It seems as though it would be a natural extension of what you already have for Github?

Thanks.

Craig
Northrop Grumman User Experience

**Comment by LeaVerou** [comment]
Hi Craig,

Glad you like Mavo!

It would be relatively easy, yes, but it would still be some work. Depends on their API. There's an open plugin request [here](https://github.com/mavoweb/plugins/issues/4) about this, so I’m closing this as a duplicate. :)
