### ISSUE TITLE
Add option to conditionally call mv-source

### ISSUE THREAD

**Issue by jamiewilson** [mavoweb/mavo#195]
I'd like to be able to check local storage for existing data so that I don't have to make any unnecessary api requests. Is something like this be possible?

```html
<div mv-app mv-source="if(!users) https://api.url/users">
```

P.S. Mavo is freaking awesome. Been procrastiworking with it all afternoon! 👍

**Comment by LeaVerou** [comment]
No, but `mv-init` may be useful? http://mavo.io/docs/storage/#providing-initial-data

> P.S. Mavo is freaking awesome. Been procrastiworking with it all afternoon! 👍

Thank you!!

**Comment by karger** [comment]
Is there a particular cost associated with the local storage api query 
that you want to avoid?
