### ISSUE TITLE
Is there a way to auto store the response from mv-source

### ISSUE THREAD

**Issue by jamiewilson** [mavoweb/mavo#196]
Say you're requesting a list of users and want to store the response without making the user edit/save, is there a way to go about doing that currently? If this doesn't exist, maybe something like `mv-autostore` would be a nice feature. 

```html
<div
  mv-app="users"
  mv-source="https://jsonplaceholder.typicode.com/users"
  mv-storage="local"
  mv-autostore>
  <div property="username" mv-multiple></div>
</div>
```

Just a thought!

**Comment by LeaVerou** [comment]
`mv-autosave` exists!! It's an attribute, with a value of how many seconds to throttle (0 for saving immediately).
It's currently only mentioned in the [index](http://mavo.io/docs/#other-attributes), more docs coming soon!

**Comment by LeaVerou** [comment]
Keep in mind that the user *will* need to modify the data for `mv-autosave` to take effect. If I understand what you want to do correctly, you're basically hacking it here for something it was not intended. :)

**Comment by jamiewilson** [comment]
Right, so `mv-autosave` Is contingent upon the user editing the fields. The idea was to provide a way for the  `my-source` response to automatically be saved to local storage without any action from the user. Does that make sense?

I can think of a lot of use cases where this would be useful. For example, say you want a user to link their twitter account so that you can display their profile info, but you don't want the user to be able to edit that data in the mavo app. Currently you'd have to make your user click save to store anything. 

Thanks for the response!

**Comment by LeaVerou** [comment]
FWIW, you can specify `mv-mode="read"` on a property to prevent it from being editable. Does that help? If not, more info about the use case would help provide better advice!

**Comment by jamiewilson** [comment]
Okay, here's another example based on something I was just working on. 

Say you have an API endpoint that contains an array of events and associated info. When the user loads the page, I want to make a request to the API and then immediately store that data on local storage, so the next time the user loads that page, instead of making another unnecessary API call for the same data, I can just use local storage. There is no need to make the user edit or save that data explicitly.
