### ISSUE TITLE
Possible bug when using GitHub organization repo for storage?

### ISSUE THREAD

**Issue by LearningNerd** [mavoweb/mavo#197]
Thought I'd bring this up as a potential issue, guessing it might be related to how the GitHub API and permissions system works?

**The issue:** setting the storage to a GitHub repo that belongs to an organization throws "HTTP error 404: Not Found" when trying to save a change via Mavo, *only when the authenticated user is a member of that organization.* (It worked fine when the authenticated user was NOT a member of the organization; Mavo forked the repo, made a commit, and made a pull request just fine in that case!)

Let me know if there's more info I should provide here, or more things I should test related to this issue!

**Comment by LeaVerou** [comment]
What was the storage URL you were using? I've noticed a similar issue when I used the format https://github.com/organizationName, but not when I used a specific repo.

**Comment by LearningNerd** [comment]
We tried the formats outlined at http://mavo.io/docs/storage/#github like `https://github.com/[username]/[reponame]` and `https://github.com/[username]/[reponame]/[filename]` and `https://github.com/[username]/[reponame]/blob/[branch]/[filename]`, same bug with all three. We tried it from my friend @jimthoburn's personal account, forking a repo on the @FoodOasisLA organization account that he has direct commit access to, and no luck with any of those storage URL formats. But when we tried from my account, which does not have access to that repo, it worked fine.

Thanks for the quick reply! Seems like an edge case but thought I'd mention it just in case it comes up again.

**Comment by LeaVerou** [comment]
Could you please provide the specific URLs you used? It probably doesn't matter, but there's a small chance the bug could be related (since it doesn't occur with all organizations, anything is possible!)

**Comment by jimthoburn** [comment]
Hi Lea!

Here’s the URL that we were testing with…
[https://github.com/foodoasisla/site/blob/master/_data/organization.csv](https://github.com/foodoasisla/site/blob/master/_data/organization.csv)

The HTML looks like this…
```
<ul
  mv-app="organization"
  mv-storage="https://github.com/foodoasisla/site/blob/master/_data/organization.csv"
  mv-format="csv">
  <li property="organization" mv-multiple>…</li>
  <li property="organization" mv-multiple>…</li>
  <li property="organization" mv-multiple>…</li>
  …
</ul>
```

And here’s our test page, if you’d like to try it…
[https://foodoasis.la/organizations/edit/](https://foodoasis.la/organizations/edit/)

I’d be happy to add you as a collaborator on the `foodoasisla/site` repository, so you can see if the issue happens to you as well.

Thanks so much for the quick response. Liz and I are both super excited about using Mavo with GitHub!

**Comment by LeaVerou** [comment]
Thank **you** for trying out Mavo and sorry about this horrible bug!

Question: Does it seem to make any difference if you're added as team in the org instead of collaborator on the specific repo?

**Comment by LearningNerd** [comment]
Sure, we just tested it again after I was added as a team member in the org, still getting the same error. Specifically: "organization: Problem saving data: HTTP error 404: Not Found". This is a weird bug indeed! Because when we go to the `responseURL` listed in the XMLHTTPRequest in the console (https://api.github.com/repos/foodoasisla/site/contents/_data/organization.csv) it definitely exists! I do see `withCredentials: false` though.

**Comment by LeaVerou** [comment]
Hello there,

It's been almost a year since this issue was opened, but I finally reproduced it with an organization I'm a part of and (with the help of the awesome Github support) realized what the issue was.

It looks like the issue is caused by the organization having OAuth app access restrictions enabled:

https://help.github.com/articles/about-oauth-app-access-restrictions/

Because Mavo isn't an approved third-party application for that organization, it isn't possible to use that token to make API requests to update any of the organization’s public resources.

I recommend requesting organization approval for that application:

https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/

And then having an owner of the organization approve Mavo:

https://help.github.com/articles/approving-oauth-apps-for-your-organization/
