### ISSUE TITLE
Tiny MCE not loading

### ISSUE THREAD

**Issue by emdashbuck** [mavoweb/mavo#199]
I've followed the instructions at https://plugins.mavo.io/plugin/tinymce but tinyMCE doesn't appear in any editable elements. I've tried both the mv-plugin and the script inclusion route. No console errors. My browser can find the script. It's just not running.

Let me know if there's any additional information I can provide or debugging steps to take, please!

**Comment by LeaVerou** [comment]
Does it work in the homepage demo at Mavo.io?

**Comment by emdashbuck** [comment]
It does. Aha, the problem is that I didn't include the class. (It looks like it also doesn't load if both the script loads and the mv-plugin attribute is set.)

I submitted an edit to the readme. :)

**Comment by LeaVerou** [comment]
Thanks for the edit! 

> It looks like it also doesn't load if both the script loads and the mv-plugin attribute is set.

That sounds like a bug, could you please file it separately?

**Comment by emdashbuck** [comment]
Sure thing. I'll make sure it's reproducible and then file.
