### ISSUE TITLE
Polymer Interop

### ISSUE THREAD

**Issue by nwwells** [mavoweb/mavo#201]
Has anyone tried to use polymer (or custom elements in general) with mavo? I'd be interested to hear how well it works. I was planning on trying it out myself, but I thought I'd ask before I go too far.

**Comment by LeaVerou** [comment]
I haven't, but I imagine it would be a very interesting combination :) Since Mavo works with your markup, the more rich your markup, the more you can do with Mavo as well :)

**Comment by nwwells** [comment]
I'll take a look and let you know what I find.

**Comment by gilsonnunesfilho** [comment]
Any updates on that?

I'm pretty new at javascript in general, but I work mainly in polymer 2 and web components. I couldn't figure out a way to use Mavo inside my components.

If anyone did, please teach me how.

Thanks in advance
