### ISSUE TITLE
DIY Backend with Sinatra, Flask, or other microframework?

### ISSUE THREAD

**Issue by jivank** [mavoweb/mavo#203]
Is there any documentation or guide on implementing a REST API for Mavo with a web microframework?

**Comment by LeaVerou** [comment]
The only docs for adding a new storage backend are here: http://mavo.io/docs/storage/#creating-your-own-storage-backend
But more docs are coming soon :)

**Comment by LeaVerou** [comment]
In any case, closing this, as documentation issues should be filed in https://github.com/mavoweb/mavo.io
