### ISSUE TITLE
Formatted numbers are printed inside <style>

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#205]
Reported by @marcomastri in #45 

We could special case `<style>`, I wonder what other cases exist where you don't want a formatted number (attributes already don't have this behavior).

**Comment by marcomastri** [comment]
That would do the trick, but wouldn’t it be a problem for the `content` property? There still should be a way to enable/disable formatting.

**Comment by LeaVerou** [comment]
@marcomastri You mean the `content` attribute? Attributes don't get formatted numbers anyway…
