### ISSUE TITLE
jQuery conflicts with Mavo/Bliss

### ISSUE THREAD

**Issue by SharpenedSpoon** [mavoweb/mavo#212]
I saw that there is a similar issue expressed in the (now closed) #106 and I come with the same problem. Looks like Mavo just does not like it at all if jQuery is loaded before it. Seems as though if Mavo gets loaded before jQuery, then jQuery knows to not conflict with the `$` symbol, but not vice versa.

Two codepens to demonstrate. They are the exact same (except for a bit of explanatory text), except in one pen jQuery is loaded before Mavo, and in the other their order is switched.

**Mavo before jQuery (works):**
https://codepen.io/anon/pen/PmMLvq

**jQuery before Mavo (breaks):**
https://codepen.io/anon/pen/mmNoZb

**Comment by LeaVerou** [comment]
Argh, yeah, this is a bug. Thanks for reporting!
Should be very easy to fix, so expect a fix very soon!

**Comment by LeaVerou** [comment]
Please wait a few seconds for deploys and try again?
