### ISSUE TITLE
Unhiding toolbar

### ISSUE THREAD

**Issue by asd-and-Rizzo** [mavoweb/mavo#213]
I can hide tool bar via `mv-bar="none"`. Could `mavo.js` unhide toolbar, e.g. if user opens `example.com/index.html?mavo` or `example.com/index.html#mavo`.  I can implement that myselft, but guess it would be common requirement. I.e. usual users see clean page, power users/admins see toolbar via link.

**Comment by LeaVerou** [comment]
You can use an id on your app (like `<div mv-app id="foo">` with some CSS like:

```css
[mv-app]:not(:target) .mv-bar {
    display: none;
}
```

If you just want to hide the toolbar for non logged in users, you can use the `mv-bar` attribute. See http://mavo.io/docs/ui/
There should probably be an FAQ item on this or some shorthand syntax, indeed it's a very common request…
