### ISSUE TITLE
Create cdnjs request

### ISSUE THREAD

**Issue by dzmitry-lahoda** [mavoweb/mavo#214]
Your project is starry. Please consider create CDN for it. I have seen minified version is not here yet?

https://github.com/cdnjs/cdnjs/issues

https://cdnjs.com/

**Comment by LeaVerou** [comment]
The URLs provided on http://mavo.io/get/ use @netlify's CDN. 
I wouldn't be opposed to adding it to CDNJS too, but the build files (including the minified version) are not in the repo, to prevent pointless conflicts, not sure CDNJS can work with that…

**Comment by asd-and-Rizzo** [comment]
I have asked about CDN because I have found some slowness. I am from Belarus. Other sites do work fast. Not looked into more details. I think mavo is good for SEO optimized sites, at same time SEO needs fast load times. So puting mavo on many or possible better CDNs is good.

**Comment by LeaVerou** [comment]
Reading [their guidelines](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md), it should be ok to submit to CDNJS, all they need is URLs to the files, not files in the repo.

**Comment by DmitrySharabin** [comment]
Oh, I didn't know we have an issue concerning submitting Mavo to CDNJS. Luckily, Mavo is already on CDNJS: https://cdnjs.com/libraries/mavo

So we can close this issue. However, I noticed that on CDNJS, the last version of Mavo is 0.2.3. It looks like we forgot to publish the latest release on NPM. @LeaVerou Is there a chance we can do it now?

**Comment by LeaVerou** [comment]
Done!

**Comment by DmitrySharabin** [comment]
Yay! Thank you! 😃
