### ISSUE TITLE
Logged in OR logged out?

### ISSUE THREAD

**Issue by Tarqez** [mavoweb/mavo#216]
Hi, within a Mavo app,

which is the best way to show/hide a DIV element depending on user status, logged-in/logged-out?

I would like an admin to see things that a visitor can not.

**Comment by LeaVerou** [comment]
If the user is logged in, there is a `can-logout` class on the Mavo root.
Similarly, if the user is logged out, there is a `can-login` class.

So if your div has a class of `logged-in-only` you can do this:

```css
.can-login .logged-in-only { display: none }
```

Does this help?

**Comment by karger** [comment]
I'm not sure-that can-login and can-logout are the right names to 
distinguish logged out from logged in.  For example, some users might 
not be able to log in at all (maybe the app doesn't allow logins) in 
which case they should be in logged-out state but without can-login 
state.  Wouldn't logged-in and logged-out be more directly indicative?

**Comment by LeaVerou** [comment]
@karger If the app doesn't allow logins, then you can match that with `[mv-app]:not(.can-login):not(.can-logout)`. There is no case where an app may allow logins but not from particular users, because it cannot know which user it's dealing with until they login :)

**Comment by Tarqez** [comment]
@LeaVerou sorry, doesn't help.

I don't have those classes on Mavo root in any case, so no show/hide effect.
If you want to give a look https://murk.alwaysdata.net/

**Comment by karger** [comment]
@LeaVerou my main point is that "can-login" and "can-logout" are not intuitive names for checking whether you are logged in or logged out.

**Comment by LeaVerou** [comment]
@Tarqez Sorry, that was based on an earlier version of Mavo that was using separate classes for permissions. Now it uses an `mv-permissions` attribute. Therefore, please use `[mv-permissions~=login]` instead of `.can-login` and `[mv-permissions~=logout]` instead of `.can-logout`.

@karger I agree. But are you suggesting we add classes that duplicate the above (which Mavo needs anyway) for the sole purpose of more readable CSS?

**Comment by LeaVerou** [comment]
Hi @Tarqez,

I just pushed a change that will allow you to use classes like `mv-logged-in` and `mv-logged-out` for this. Docs here: http://mavo.io/docs/#classes

**Comment by Tarqez** [comment]
Hi @LeaVerou, 

I appreciate this improvement.
