### ISSUE TITLE
Should the mv-bar attribute be presentational or semantic?

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#222]
Currently, using classes like e.g. `mv-save` on one's own buttons, even outside the Mavo toolbar, will associate those buttons with the respective action (in this case, saving).
However, if a button is removed from the toolbar via `mv-bar` (e.g. `mv-bar="no-save"`), then this will not work.

Is that desirable or is it a bug? Do we want `mv-bar` to be about which *actions* are available or about which *buttons* are displayed in the toolbar?

**Comment by joyously** [comment]
Can the buttons be somewhere other than the toolbar? 
Is the toolbar the only place where those actions can be initiated?

**Comment by LeaVerou** [comment]
> Can the buttons be somewhere other than the toolbar?
> Is the toolbar the only place where those actions can be initiated?

Yes, with the right classes. This is what my first post was asking: If removed via `mv-bar` should they still be available?

**Comment by LeaVerou** [comment]
After some thinking, I decided it makes sense that `mv-bar` is merely presentational and does not prevent these actions from custom buttons. I think most people use `mv-bar` to hide buttons for presentational reasons, exactly because they want the functionality to be available via their own custom buttons. If we want to restrict permissions, this should be done via the `mv-permissions` attribute, not the `mv-bar` attribute, which should only concern the toolbar.
