### ISSUE TITLE
Logging in to one Mavo app should log user in to other Mavo apps on the page with the same backend

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#223]
User should not have to tediously log in individually to every single Mavo app on the page. As long as it uses the same backend (e.g. Github) and the user is NOT logged in, it should log them in.

What about log out? Should they log out of all of them simultaneously?

**Comment by LeaVerou** [comment]
What about log out? Should they log out of all of them simultaneously?

**Comment by karger** [comment]
perhaps generalize: if there are multiple mavo pages on a single site, 
should the credentials be shared among them?

**Comment by LeaVerou** [comment]
They already are. Even before this fix, if you logged in to one Mavo app and then refreshed, you were logged in to all of them that used the same type of backend.

**Comment by karger** [comment]
so what is it that you are fixing?

also, are there potential risks here in large hosting sites; e.g. is it 
a problem loggin in to one mavo on wordpress.com logs you into all of them?

**Comment by LeaVerou** [comment]
> so what is it that you are fixing?

Removing the need to refresh.

> also, are there potential risks here in large hosting sites; e.g. is it
a problem loggin in to one mavo on wordpress.com logs you into all of them?

No because origin is per subdomain.
