### ISSUE TITLE
Dragging collection items does not scroll window

### ISSUE THREAD

**Issue by squarestar** [mavoweb/mavo#231]
When dragging an item in a collection that is longer than the available vertical space, the browser window does not scroll when the cursor reaches the top or bottom browser edge. Occurs in Firefox 54 and Chrome 59

**Comment by LeaVerou** [comment]
Hello there, thanks for reporting this!

I completely agree that this is super annoying. However, it's actually a bug in Dragula, the Drag & Drop library that Mavo uses.
It will be fixed automatically once this is fixed: https://github.com/bevacqua/dragula/issues/327

Therefore closing this, as it's not a Mavo bug per se. You could follow the Dragula bug above for updates.
