### ISSUE TITLE
GitHub back-end takes 3 HTTP requests for saving

### ISSUE THREAD

**Issue by RubenVerborgh** [mavoweb/mavo#234]
Upon saving the [editable homepage example](http://mavo.io/demos/homepage/), 3 HTTP request to GitHub happen:
1. `GET /user/repo/data?timestamp=t`
2. `GET /user/repo/data/contents/homepage.json?timestamp=t`
3. `PUT /user/repo/data/contents/homepage.json`

These 3 all happen in sequence, and lead to extra time and bandwidth on saving. Moreover, each request additionally requires an `OPTIONS` preflight, which brings the total for 6 requests. (The `OPTIONS` for 3 is omitted after the first time, but the first 2 `OPTIONS` cannot be committed because the timestamp makes the URL different every time.)

The first request is seemingly the result of authentication, which unnecessarily repeats login. This request can certainly be eliminated. The second request is probably there to avoid a `409` on the third; however, technically speaking, we could still get a `409` there in race conditions. So maybe a viable strategy is to always try request 3, and only when it `409`s, do the second request as well.

**Comment by RubenVerborgh** [comment]
Would this be covered by #245/#247? Probably at least 1 request disappears now.

**Comment by LeaVerou** [comment]
Looks like it!
