### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#239]
At the very least basic localization of phrases so that third-party devs can make locale plugins.

In the future, some declarative way to override certain phrases in the HTML would be nice, but that would be a separate issue.

**Comment by uitvaartfotograafgroningen** [comment]
Is there some documentation about how to implement localization?

**Comment by LeaVerou** [comment]
If I'm understanding what you want to do correctly, you could use a property for the current language (use `mv-storage="none"` to prevent it from being stored in the data), and then use that in `mv-storage` to change the data file depending on the language.

In general, documentation right now doesn't have a lot about usage patterns and tutorials, we're focusing on documenting the building blocks first, and once we're done with that, we can focus more on documenting ideas on how to combine them. Sorry about that, I know the docs could be much better!

**Comment by wouter-muller** [comment]
Thanks! That sounds like exactly what i need, i will play around with that and if i am successful might write a blog about it. 

Thanks for taking the time to answer this question :) @LeaVerou

**Comment by LeaVerou** [comment]
That would be awesome, thank you!
If you run into any issues, let me know!
