### ISSUE TITLE
Image path is not committed to fork

### ISSUE THREAD

**Issue by RubenVerborgh** [mavoweb/mavo#241]
As discussed in #235, when uploading an image, the image path is not committed to the fork after saving.

Video: https://youtu.be/uJA4dDFXbuE?t=16s
Corresponding commits:
- https://github.com/RubenVerborgh/data/commit/d99756116f02df0be6f0c07eed5bdf34ae7c918d (save after editing text)
- https://github.com/RubenVerborgh/data/commit/c1a30a0fe9ca50781e06984bd87638c505102a4f (upload image [was the same though])
- https://github.com/RubenVerborgh/data/commit/a9768db1c0e6abcd63f710fcf6932b51bc176448 (save after image upload, nothing was changed in the commit, yet the new path should have been committed)

**Comment by LeaVerou** [comment]
Now that #235 is fixed, could you check if this is also fixed by any chance?

**Comment by RubenVerborgh** [comment]
Yes, will check!

**Comment by RubenVerborgh** [comment]
Yes, the path is committed: https://github.com/RubenVerborgh/data/commit/4df616a51cb846becf53abdf8d3e324a4a446502
