### ISSUE TITLE
Set timestamp only on storage backends that require it

### ISSUE THREAD

**Issue by RubenVerborgh** [mavoweb/mavo#248]
Right now, a [timestamp is set on all requests](https://github.com/mavoweb/mavo/blob/v0.1.1/src/backend.js#L18) by default. However, this might only be a requirement for certain storage backends (GitHub, for instance).

The downside of this automatic append is that it breaks caching (for stores that correctly support it, which does not include GitHub), and that it might break on backends that do not support additional query parameters (they could then override, but perhaps not adding anything might be a sensible default).

Does it make sense to:
- delegate that responsibility to the storage backends?
- or hide that functionality behind a flag?

**Comment by LeaVerou** [comment]
Hmm, perhaps it could be a setting on `Backend#request()`.

**Comment by DmitrySharabin** [comment]
I faced exactly the same issue while working on the `GSheets` plugin. Precisely that forced me to implement `Backend#get()` instead of `Backend#load()`.
So I agree with Ruben. It would be nice if we give this issue another shot.
