### ISSUE TITLE
Mavo appears unable to run when (firefox) tracking protection is enabled

### ISSUE THREAD

**Issue by karger** [mavoweb/mavo#255]
Potential user reports that mavo is not running on their page; console is posting a message saying "The resource at "https://www.google-analytics.com/analytics.js" was blocked because tracking protection is enabled.  Empty string passed to getElementById().  mavo.es5.js:1304:10"

More info here: https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection

**Comment by LeaVerou** [comment]
There is no google analytics fetched by Mavo itself. I suspect this is a problem in the mavo.io website instead? If so, it needs to be reported in https://github.com/mavoweb/mavo.io
