### ISSUE TITLE
Make gallery using Mavo?

### ISSUE THREAD

**Issue by stalcer** [mavoweb/mavo#257]
Is there a possibility to make something like gallery using Mavo? Thumbnail image property (with mv-multiple) leading via link href to the full-size image? Can Mavo generate a thumbnail for this case?

**Comment by karger** [comment]
Is the example at https://mavo.io/demos/portfolio/ suitable?

**Comment by stalcer** [comment]
Something like that yes, but also I need to open full-size images.
Resulting markup must be roughly this: `<a href="image-full.jpg"><img src="image-thumb.jpg" /></a>`
'Portfolio' example shows only thumbnails.

**Comment by LeaVerou** [comment]
Yes, there are many ways to do this!

If you want to use separate files for thumbnails and full size images, you would need to have separate properties for them (e.g. `<a href="image-full.jpg" property="image"><img src="image-thumb.jpg" property="thumbnail" /></a>` in your example).
Alternatively, you could decide on a naming scheme and only have 1 property, in which case the thumbnail filename is inferred from the full size filename. Your example would look like `<a href="image-full.jpg" property="image"><img src="thumb-[image]" /></a>` in that case.

Then, to make the gallery:

1. Probably the simplest way would be to use a link to the image, like in your example. The downside is that there is no navigation out of the full size image (besides clicking back in the browser)
2. You could use some clever CSS to provide a lightbox effect. Something similar is used in this demo, to open the invoices: https://mavo.io/demos/invoice/ The benefits of that approach is that you can also offer next/previous navigation
3. You could make a separate page for viewing individual images and use `mv-path` to only display 
1 item. Something like this is used on the Mavo plugins directory, see https://plugins.mavo.io/ and e.g. https://plugins.mavo.io/plugin/markdown

Hope this helps, please ask if you have more questions! Sorry the documentation is not good enough yet :/

**Comment by stalcer** [comment]
Lea, thank you for such a detailed answer!

Do I understand correctly that I have two different ways?

1. Separately upload a thumbnail and a full picture

1. Upload one large image and use it as a thumbnail downsampling with html/css

**Comment by LeaVerou** [comment]
Yes!

If you choose to go with separate images, you would need to have an `<img property="...">` for it to allow uploads. To prevent that from loading when the gallery is viewed, you can either go with Suggestion #3 and have separate pages or if you go with suggestion #2 apply `display: none` to that image via CSS when the gallery is not being edited (browsers don't load images that are hidden via `display: none`).

**Comment by joyously** [comment]
> You could use some clever CSS

This CSS for a responsive gallery is pretty clever: [CSSPlay Responsive momentum swipe gallery](http://www.cssplay.co.uk/menu/cssplay-momentum-swipe-gallery.html)

**Comment by stalcer** [comment]
@LeaVerou 
Looks like I've found some bug in Mavo. You can look at example here: https://codepen.io/stalcer/pen/rzyLwY

I were trying to create a gallery using this approach: <a href="[image]"><img src="thumb-[image]" property="image" /></a>

My example shows how Mavo goes into an infinite loop (or maybe recursion), trying to build file names for link and image. He spawns many network requests trying to load incorrect filename.

**Comment by LeaVerou** [comment]
@stalcer Hey, sorry for the delay, I was in several flights from Australia. :) 

It’s not exactly a bug, but it's certainly unintuitive.

Explanation of what’s happening: The primary attribute of `img` is `src`. This is the attribute that becomes editable when you add a `property` attribute to it, as well as the one that is used for its value in expressions. Therefore, any time you use `[image]` it means "the value of the `src` attribute on the image with `property=image`. So, when you use that in the `src` attribute itself it's basically saying `[image] = thumb-[image]` which causes an infinite loop. Think of uploading an image with the filename `a.png`. This would make the `src` attribute `thumb-a.png` and then `thumb-thumb-a.png` and then `thumb-thumb-thumb-a.png` and so on.

Now, if you try to explain what you were actually trying to accomplish with this, two things can happen:

1. There is probably a different way to do what you wanted so I could help you with that.
2. It will help me see if I can address this confusion in Mavo somehow, to prevent (or at least detect and stop) such infinite loops.

@karger referring to our earlier discussion, see how easy infinite loops are already? :P

**Comment by stalcer** [comment]
This is all in the continuation of the idea with the gallery.

I want to solve the problem with uploading one image, saving it on the server in two sizes - full and small and showing them on the client. I thought that if I upload a large picture through Mavo and convert it into a small size (with "thumb-" prefix) on the server, then the trick '<a href="[image]"> <img src = "thumb-[image]" property = "image" /> </a>` will solve my problem.

**Comment by LeaVerou** [comment]
Oh I’m sorry if I misled you there, there is no such special handling when using a `thumb-` prefix. That's a great idea for a plugin though!
At the moment, if you need two different sizes you'd need to upload two separate images and have two separate properties. Sorry if I wasn’t clear enough about that!

**Comment by stalcer** [comment]
Let's assume that my server itself is able to create "thumb-image.jpg" for each uploaded "image.jpg".

Is there a possibility for mavo-markup in the current version of Mavo, which will be able to pass a full picture into the link, and into the child img - a thumb version?

**Comment by LeaVerou** [comment]
Yes, of course.

So, to be clear so that I don’t suggest the wrong thing, you want to upload the full version, your server generates the thumbnail, the thumbnail is used on the `<img>` and the large image is not shown, just linked via a surrounding `<a>`?

**Comment by stalcer** [comment]
And one more question regarding gallery. I want to add event listener after Mavo renders all mv-multiple items. Is there some event that fires after Mavo finished render iterating objects?

**Comment by stalcer** [comment]
> So, to be clear so that I don’t suggest the wrong thing, you want to upload the full version, your server generates the thumbnail, the thumbnail is used on the <img> and the large image is not shown, just linked via a surrounding <a>?

Yes, you are quite right.

**Comment by LeaVerou** [comment]
Turns out it’s a little trickier than I thought, because even if you hide the large image, it will still be loaded by the browser. The main problem is that you need an `<img>` to enable uploads, but you don’t want that image to be there when viewing the gallery because then it will load, defeating the point of having thumbnails at all. There is no way to hide it with CSS so that it doesn’t load. You could use `mv-if` to hide it with Mavo, which removes it from the page entirely. That would help prevent it from loading, but it would also hide it from the data so you wouldn't be able to refer to it. So how do you make sure there is an `<img>` there to upload to when editing but doesn’t load when not editing?

The easiest way is to create two separate pages, one for editing with an `<img property="image">` and one for viewing with `<img src="thumb-[image]" />`. You don’t need anything with `property=image` in the second page.

Perhaps a better way: Instead of creating two gallery pages, one for viewing and one for editing, you could create one page for viewing an index of pictures and one for viewing (and editing) the large version of any picture. This would be better than just linking to an image, because it would also display the image's metadata (title, description etc). You could use the latter to upload the large images, whereas the former would only allow editing of what is displayed in the index (titles etc). Let me know if you want to go this way and I can give you more advice on how to do this.

Whether this is a good idea depends on your usage. If it's likely that you want to upload multiple images all at once, then having two gallery index pages might be a better process.

> And one more question regarding gallery. I want to add event listener after Mavo renders all mv-multiple items. Is there some event that fires after Mavo finished render iterating objects?

Yes, `mavo:load`.

**Comment by stalcer** [comment]
I came up with the following workaround. Maybe it's not beautiful but it works.

This is my template: `<a mv-multiple><img property="image"></a>` (link without href attribute).

When Mavo uploads the image, the server creates two images: the one with original image name but small size, and the second one with original size but with 'full-' prefix in the name.

After Mavo finished render all gallery items, my JS script iterates thru all links and adds href attribute with string 'full-' + src value from nested image.

**Comment by stalcer** [comment]
> Yes, mavo:load.

For some strange reason, this event fires two times. But ok, I'll look more closely at this.

**Comment by LeaVerou** [comment]
That works too! Excellent solution! I didn't realize that using the original name for the thumbnail was an option.

No need for the JS, just use `<a href="full-[image]">` in the link! 

> For some strange reason, this event fires two times. But ok, I'll look more closely at this.

Can I look at your code?

**Comment by stalcer** [comment]
> No need for the JS, just use <a href="full-[image]"> in the link!
As I understand it, it will not work, because [Image] contains not only the name of the file but also the path to it and 'full- [image]' will be something like '' full- / images / image.jpg ''.

> Can I look at your code?
Right now it's a local server with no internet access. If I don't find the solution, then I host it somewhere to show you.

Great thanks to you Lea! You're a very nice person!

**Comment by LeaVerou** [comment]
> As I understand it, it will not work, because [Image] contains not only the name of the file but also the path to it and 'full-[image]' will be something like 'full-/images/image.jpg'.

Oh, you're absolutely right! You can use the `filename()` function: `href="/images/full-[filename(image)]"`

**Comment by stalcer** [comment]
One more question.
I have some makup: `<a href="http://www.example.com"><img src="image.jpg" property="image" /></a>`;

When I try to edit that propery, `<a>` gets click and and leads me to the link.

Is there native Mavo workaround for this?

**Comment by LeaVerou** [comment]
> Hmmm. Looks like it was only one time, when src attribute was empty.

Are you sure you had clicked Edit? This often happens to me, then I realize I forgot to click Edit.
