### ISSUE TITLE
Explicit, anonymous group declaration prevents child properties from being editable

### ISSUE THREAD

**Issue by stalcer** [mavoweb/mavo#262]
When I use the Schema.org markup, the Mavo refuses to edit those elements and childrens. For example:
```
<div mv-app="appName" mv-storage="local">
	<ul itemscope itemtype="http://schema.org/Organization">
		<li property="nameJane" itemprop="name">Jane Doe</li>
	</ul>

	<ul>
		<li property="nameJohn">John Doe</li>
	</ul>
</div>
```
Second list item will be editable, but not the first one. Why so? And what can I do to use Mavo on elements with Schema markup?

**Comment by LeaVerou** [comment]
It’s not Schema markup, it’s Microdata. Schema itself works with all three technologies, Microdata, RDFa, and JSON-LD. There are tabs for all three on the Schema.org website. Mavo’s syntax is based on RDFa, so it works much better with that, but it should work with Microdata as well. In fact, if you use the RDFa variant of Schema.org, Mavo even uses the extra info in the saved JSON, to make it JSON-LD compliant.

This here looks like a bug. I’ll look into it, but in the meantime, I'd suggest just using RDFa instead.

**Comment by LeaVerou** [comment]
Reduced testcase: https://codepen.io/leaverou/pen/NvwRPJ?editors=1100#
It looks like it’s not related to Microdata or Schema.org at all.

**Comment by LeaVerou** [comment]
While we're at it, it may make sense to stop supporting Microdata for defining Mavo stuff at some point. Nobody seems to use it in that way, support for it makes Mavo slightly slower, and it gets in the way when people want to use both Microdata and Mavo (but don't realize that Microdata triggers Mavo stuff too).
