### ISSUE TITLE
?login loop

### ISSUE THREAD

**Issue by tleen** [mavoweb/mavo#266]
Hi there, I have been experimenting with using the ?login argument to the app page url. I have found that by using this argument the base url of the app now keeps ?login appended to it. So when I use the toolbar to logout it logs me out to an immediate ?login popup.

Say my app was at 
http://localhost/test-app.html

To get the user to login (without the toolbar) I send them to:
http://localhost/test-app.html?login

They get the popup, verify, and start working on the app, their location is now:
http://localhost/test-app.html?login 

When they logout, they logout to the url:
http://localhost/test-app.html?login 

Which will immediately pop up another login dialogue.

Could I be doing the ?login incorrectly? Is there a better way to handle it?

**Comment by LeaVerou** [comment]
Thanks for such a detailed report!
Could this be the same bug as https://github.com/mavoweb/mavo/issues/224 by any chance?

**Comment by tleen** [comment]
Yes! Sorry for the dup.
