### ISSUE TITLE
Allow optional Mavo bar buttons

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#269]
Currently, one can only remove buttons (e.g. `no-login`) or specify the exact set of toolbar buttons.
It should be possible to have optional buttons that are not there by default and are added via `mv-bar` without having to specify the entire set of buttons and their order (which is not futureproof).

**Comment by karger** [comment]
I assume the mv-bar will ultimately be implemented as a widget like any 
other.  Is its configuration being specified the same way we ultimately 
expect other widgets' configurations to be?  i.e., have we thought about 
a standard way of using attributes to provide arguments to widgets?

**Comment by LeaVerou** [comment]
Mavo does not really have a concept of "widgets", so I’m not sure I follow what you mean here…

**Comment by karger** [comment]
Per our past discussions, first regarding David Wong's widgets and more 
recently Florian's widgets api---a standard mechanism for giving the 
bindings between attribute names and widget arguments. So for example 
the login widget may take certain input arguments through some 
attributes (permissions requested?) and be triggered by others (once we 
figure out triggering) and may also return outcomes/status through other 
attributes, which other mavo exprs could read.
