### ISSUE TITLE
Compatibility issues with Googlebot crawler (Chrome 41)

### ISSUE THREAD

**Issue by EtunaAikido** [mavoweb/mavo#276]
Googlebot is unable to run Mavo properly, so no content that is rendered with Mavo is being indexed, even when mavo.es5.js is being used. It's referencing several other libraries that are not es5 compatible it seems, and the polyfill is not complete or not working. This is probably a pretty big issue for mavo adaption in the wild.

I don't have the javascript skills necessary to work it all out, but from what i've been able to find:

Array.from() is not supported, possibly implement the polyfill into https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

Css custom properties do not seem to be supported until Chrome 49, i.e Mavo.getStyle(this.element, "--mv-mode") will probably never work.

Possibly more issues exist. Easiest way to debug is to run Chrome 41 through Turbo.net or Browserstack.

**Comment by LeaVerou** [comment]
Thanks @EtunaAikido for your work investigating this!

> Array.from() is not supported, possibly implement the polyfill into developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

We could add it to the list for polyfill.io polyfills being fetched pretty easily.

> Css custom properties do not seem to be supported until Chrome 49, i.e Mavo.getStyle(this.element, "--mv-mode") will probably never work.

Custom properties are not a problem, we don't care about GoogleBot being able to edit the data, we just want it to be able to *read* the data. So, as long as that code doesn't produce an error (it shouldn't) it should be ok :)

**Comment by EtunaAikido** [comment]
Unfortunately custom properties does seem to produce a blocking error, but hopefully it just needs a null-check:

TypeError: Cannot read property 'trim' of null {stack: (...), message: "Cannot read property 'trim' of null"}

In util.js row 156

	/**
	 * Get the current value of a CSS property on an element
	 */
	getStyle: (element, property) => element && getComputedStyle(element).getPropertyValue(property).trim(),

**Comment by EtunaAikido** [comment]
Working solution:

Load a polyfill for Array.from and URL before loading Mavo.
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Array.from,URL&unknown=polyfill"></script>
<script type="text/javascript" src="js/mavo.es5.js"></script>
Obviously this should be done through Mavo itself.

Quickpatch for util.js

		/**
   * Get the current value of a CSS property on an element
   */
		getStyle: function getStyle(element, property) {
			var value = getComputedStyle(element).getPropertyValue(property);
			if (value) {
				return element && value.trim();
			}
		},

**Comment by EtunaAikido** [comment]
Added in some plugins on my testpage now, and got new errors :) Anyway, the plugins break but are not blocking, but i had to quickfix this:

Added:
`if (element === null) { return; }`

```
    * Search for Mavo.DOMExpression object(s) associated with a given element
    * and optionally an attribute.
    *
    * @return If one argument, array of matching DOMExpression objects.
    *         If two arguments, the matching DOMExpression object or null
    */
            search: function search(element, attribute) {
                if (element === null) { return; }

				var all = _.elements.get(element) || [];

				if (arguments.length > 1) {
					if (!all.length) {
						return null;
					}

					return all.filter(function (et) {
						return et.attribute === attribute;
					})[0] || null;
				}

				return all;
			}
```

**Comment by LeaVerou** [comment]
Thank you so much @EtunaAikido! Should I apply your fixes or do you want to send a pull request?
It's better to send a PR so that you're added to the [list of contributors](https://github.com/mavoweb/mavo/graphs/contributors). Just make sure to follow the code style enforced via ESLint and I can help with whatever you need.

**Comment by LeaVerou** [comment]
> Edit: Problem is also that Array.from() is used long before polyfill.io is ever called (on the first row of mavo.es5), so the polyfill is not loaded without a manual Array.from() polyfill. So perhaps the polyfill should be loaded before anything else.

It's inside a function though, so it's called when that function is called. 

> Load a polyfill for Array.from and URL (minimum required) before loading Mavo. Observe the "unknown=polyfill" to get polyfill.io to send polyfill even if it doesn't recognize the useragent, which it doesn't. "flags=gated" is required also to avoid conflicting errors.

Done, thanks! `flags=gated` is deprecated, I implemented their recommended way (`|gated` after each feature).

Can you test that the polyfills for `URL` and `Array.from` are actually still required?

**Comment by EtunaAikido** [comment]
I don't think flags=gated is deprecated? I can't find any documentation on that anyway. Of course in this case it does not matter that much since we only have two features, so it's exactly the same length :)

I did some quick testing, and URL is not needed anymore. Array.from is still required in the pre-load polyfill however.

**Comment by LeaVerou** [comment]
I looked into this as well today and applied a few fixes. Indeed, `Array.from` was required, [I fixed that in Bliss](https://github.com/LeaVerou/bliss/commit/e79d681f844f90c8886cf8c176dd13d4e9d81510).
It looks like Mavo should work out of the box now!
I just requested a re-indexing of the FAQ, since it displayed correctly in the console :)
Thank you so much for looking into this @EtunaAikido!!!

**Comment by EtunaAikido** [comment]
Confirmed, no extra polyfill needed anymore! 👍

**Comment by LeaVerou** [comment]
> I don't think flags=gated is deprecated? 

Not sure where I got that from, can't find it either! I will change it to `flags=gated` when I get a chance, much cleaner than adding `|gated` to every feature!
