### ISSUE TITLE
Autosave not working when getting save permissions after login

### ISSUE THREAD

**Issue by valterkraemer** [mavoweb/mavo#283]
If you don't have save permissions when the application loads, autosave won't work after logging in and getting save permission.

https://codepen.io/anon/pen/MEQeEW?editors=1111

**Comment by LeaVerou** [comment]
This is an excellent testcase, it will really help fixing this, thank you so much!

**Comment by LeaVerou** [comment]
Hey @valterkraemer, could you please verify on your end that this bug is fixed?
I also saw in one of your readmes that you found a bug with `mv-autosave="0"` that doesn't happen with `mv-autosave=".01"`. Have you filed a bug for that?
Thanks!

**Comment by valterkraemer** [comment]
Yes, seems to be fixed now. Thanks!

It's related to this one https://github.com/mavoweb/mavo/issues/256. The hack mensioned in https://github.com/mavoweb/mavo/issues/256#issuecomment-318920475 doesn't work when `autocomplete="0"`.
