### ISSUE TITLE
CORS problem when upload checks if file is uploaded

### ISSUE THREAD

**Issue by valterkraemer** [mavoweb/mavo#292]
Im having CORS problems when uploading images to Firebase Storage. `XMLHttpRequest cannot load https://firebasestorage... due to access control checks.`.

If I skip `checkIfLoaded` in the upload function in elements.js uploading works.

```
var upload = (file, name = file.name) => {
  if (file && file.type.indexOf(type + "/") === 0) {
    this.mavo.upload(file, path + "/" + name).then(url => {
      mainInput.value = url;

      this.mavo.inProgress = false;
      $.fire(mainInput, "input");
    });
  }
};
```

Maybe the checking could be skipped for certain backends?

I played with the idea of using `new Image()` instead and it seemed to work fine. But then audio and video would also be needed to be handled, and there isn't an `new Video()` to my understanding.

```
var checkIfLoaded = Mavo.rr(() => {
  var img = new Image();

  img.onload = () => {
    this.mavo.inProgress = false;
    $.fire(mainInput, "input");
  };

  img.onerror = () => {
    if (attempts++ < 10) {
      this.mavo.inProgress = "Loading Image";
      Mavo.timeout(2000).then(checkIfLoaded);
    }
  }

  img.src = url + "?" + Date.now();
});
```

**Comment by LeaVerou** [comment]
This whole part of the code is a clusterfuck so I'm very open to changing it. The reason it has to try multiple times is that Github Pages and Netlify etc take a while to deploy, and there's no way to know when.

Do keep in mind that eventually we want to allow uploads of more filetypes e.g. PDF on `<a>`.

Perhaps we can create a dummy `<img>` or `<video>` element and listen to its `onload` event? Does that work?

Alternatively, perhaps we can move that part of the code to the Github backend and have `upload()` return a promise that resolves with the URL. I'm not sure whether other backends suffer from the same problem, though in theory any backend that takes a bit of time to deploy does... Perhaps we could abstract it away into a function on `Backend.prototype` and then backends that need it can just call it.

Thoughts?

**Comment by valterkraemer** [comment]
Probably could make dummy elements, but that still wouldn't work e.g. for PDFs.

To me it makes sense the move the checking part to the backend's responsibility, when it's not valid for all backends.

One possibility would be to not wait for GitHub Pages to deploy, but instead use the [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) to show the image/video to the user.

**Comment by LeaVerou** [comment]
> Probably could make dummy elements, but that still wouldn't work e.g. for PDFs.

But you don't need to display those, they’re just links :)

> To me it makes sense the move the checking part to the backend's responsibility, when it's not valid for all backends.

It's valid for many, but not all backends. Does Firebase Storage deploy instantly?

> One possibility would be to not wait for GitHub Pages to deploy, but instead use the FileReader API to show the image/video to the user.

Yeah, I wondered about that. The thing is, if something goes wrong, you want them to know, not be fooled into thinking their upload worked when it didn't…
OTOH, it could be implemented in Optimistic UI fashion, where we show it to the user via FileReader, then replace it with the real URL like 10 seconds later. The more I think about it, the more I like this idea…

PS: When are you going to add your Firebase project to the Plugins directory? 😁

**Comment by valterkraemer** [comment]
> It's valid for many, but not all backends. Does Firebase Storage deploy instantly?

Yes, files are available immediately. Also PouchDB attachments (that I've also made an backend for).

> OTOH, it could be implemented in Optimistic UI fashion, where we show it to the user via FileReader, then replace it with the real URL like 10 seconds later. The more I think about it, the more I like this idea…

Makes sense to me.

> PS: When are you going to add your Firebase project to the Plugins directory? 😁

I've done big changes this weekend, now I feel like it's mature enough. Maybe I'll get to it in the coming days 😉

**Comment by LeaVerou** [comment]
Just pushed a commit that should fix this, can you check @valterkraemer?

It also uses `FileReader` to display the image locally, and will only show a broken image if it keeps failing to load the uploaded image after 38.5 seconds (if you’re interested why such a weird number: it will try to load it a maximum of 11 times, increasing the delay by 500ms on each attempt, so 1 + 1.5 + 2 + ... + 6 = 11 + .5 * (1 + 2 + 3 + ... + 10) = 11 + .5 * 55 = 38.5).

I’m gonna close this, but please reopen if your issue is not fixed.

**Comment by valterkraemer** [comment]
@LeaVerou yes it works! Great, thanks!
