### ISSUE TITLE
cannot add editable images to collections

### ISSUE THREAD

**Issue by joshpitzalis** [mavoweb/mavo#293]
I created a collection like so...
```
<section mv-multiple>
      <h2 property='14fa484a-39e5-4a4c-b317-dd84bfaa3b5e'>Loading...</h2>
      <p property='54d63832-b5fe-43e1-b740-84872b3109a4'>Loading...</p>
      <figure class="fullwidth">
        <img src="img/placeholder.png" alt="" property='5d4f80b4-6026-407f-9100-919a9e538200' />
      </figure>
      <p property='8b445701-efa9-45ac-9092-8055eea2de81'>Loading...</p>
    </section>
```

When I try and create a new collection all the text fields are editable in the new collection but not the image. Its as if the image doesn't even exist.

![screen shot 2017-10-29 at 12 03 44](https://user-images.githubusercontent.com/10258114/32141241-4e5d9400-bca1-11e7-8c7a-df2c41aac782.png)

Am I doing something wrong or is this a bug?

**Comment by LeaVerou** [comment]
I’m not sure if this is the cause of the problem, but property names cannot contain hyphens. Only letters, underscores, numbers. You might be able to get away with other characters for certain uses, but not all (e.g. hyphens won't work in expressions, they will be treated as a subtraction).

Apart from that, I can't see anything else that's wrong at first glance. 
It would help me to figure out what's causing this if I had an online testcase to examine. https://play.mavo.io might be helpful for that.
I [just created one here](https://codepen.io/leaverou/pen/vWYoEM?&editors=1100#) where the only change is the placeholder src (not even the property names), and editing works fine.

Which browser are you using? Does editing in other images work?

**Comment by LeaVerou** [comment]
Closing this as it received no response in over a month.
