### ISSUE TITLE
Updating $now every 100ms is too slow for animations

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#302]
100ms are a little too slow for animations via $now. Somehow use RAF for now updates instead or in addition ?

Basic example:

https://summer-toy.glitch.me/

**Comment by LeaVerou** [comment]
`$now` wasn't really designed for animations, though that is certainly a valid use case.
OTOH, I don't want to penalize apps that don't need this kind of resolution.
I think perhaps the best of both worlds would be to pick a sensible default (like 100ms) and have an attribute that changes it to a different number of milliseconds (and 0 would mean rAF).
Now if only I could find a good name for that attribute, most of the work would be done :)

**Comment by andreasplesch** [comment]
hmm, perhaps `nowUpdateInterval` ? Or
- [ ] nowSpeed
- [ ] nowRate
- [ ] nowEvery
- [ ] nowHow (just kidding)
- [ ] nowInterval
- [ ] nowStep
- [ ] nowUpdates
- [ ] nowThrottle
- [ ] something else

**Comment by LeaVerou** [comment]
Thanks! I'll sit on it for a bit.
Btw our attributes are hyphenated and start with `mv-`, so it's more like:

- [ ] mv-now-speed
- [ ] mv-now-rate
- [ ] mv-now-every
- [ ] mv-now-how (just kidding)
- [ ] mv-now-interval
- [ ] mv-now-step
- [ ] mv-now-updates
- [ ] mv-now-throttle
- [ ] something else

Tying it to `$now` seems a bit low-level TBH. I would prefer something that declares *intent* instead.
@karger, any ideas?

**Comment by andreasplesch** [comment]
Well, my thinking was until there is wider adoption of such an attribute in mavo, it would be actually tied to $now. Perhaps an attribute should rather be a mode indicating performance/power tradeoffs ?

**Comment by LeaVerou** [comment]
I was discussing this with @svgeesus today and he suggested using a separate variable instead of an attribute that modifies how `$now` works.
This doesn't seem too crazy, we already have `$startup` that works like `$now` but is only updated once.
The question is: what should that variable be named?
Two names we discussed are `$tick`, `$frame` but I don't like any of them, they're too technical and don't sound like a timestamp (unlike `$now` and `$startup`).
Any ideas?

**Comment by andreasplesch** [comment]
A separate variable would be cleaner and allmow for more flexibility but I agree that the name becomes more important since there is potential for confusion with $now which would be almost identical from a user perspective. There may be a parallel with Date.now and Performance.now or DOMTimeStamp and DOMHighResTimeStamp in terms of naming.

Let's brainstorm:

- $now-highres : following existing naming
- $now-updatedasoftenaspossible : too long, but I think the name could be longer since it may not be used as often
- $now-anim: main purpose but sort of ungrammatical
- $now-and-then (could not resist)
- $now! (probably not allowed)
- $milliseconds: emphasizing updates on the order of milliseconds
- $moment: emphasizing immediacy
- $rightnow: too colloquial?

I like the idea of making the name a subspecies of $now to clearly state that it has the same function but works a bit differently.
Sorry, that's all I have for now (!).

**Comment by LeaVerou** [comment]
Do note that hyphens are not possible either, since they conflict with minus (in CSS we solved that by requiring spaces around minus, which causes endless confusion to authors).

I like `$moment` and `$rightnow`!
Anyone else have any thoughts? @karger?

**Comment by LeaVerou** [comment]
Btw another possibility would be use `$now` for this and rename `$now` to something else.

**Comment by LeaVerou** [comment]
@karger suggested `$rate`, `$pace`, `$pulse` over email but also said "60 times per second is only 6 times more often and ought to be fast enough given video frame rates?"

(Though browsers have started doing 120fps so basically 6-12 times more often)

I wonder if I’m prematurely optimizing by trying to have two variables here. Perhaps I should bite the bullet and just update `$now` via rAF, which is certainly the most usable way...

If we go that route, it would be nice if there was a heuristic to adapt to what resolution is needed.
E.g. start with rAF (60-120fps), and if expression doesn't change for a N seconds drop resolution to once every 100ms (or even more). Then if it changes multiple times again, increase resolution again. Thoughts?

**Comment by andreasplesch** [comment]
rAF should give mobile browsers the opportunity to throttle (to say 10fps) whenever they deem that advantageous, e g. to invoke a power saving mode. It will be of course important to make sure that $now updates only provoke other updates where necessary. [ I am curious how breaking of property loops is handled; will just test ]
Not sure if a throttle heuristic is necessary since the point of $now is that expression values will change. I suspect that in many cases the Mavo cost would be only a small fraction of total frame cost in animations. Gaming and VR applications may want to avoid any kind of overhead anyways and stick to webgl, three et al.

property loops:
```
property="a" value="[b + 1]"
property="b" value="[a - 1]"
```

**Comment by LeaVerou** [comment]
> Seems like a typical usage of exponential backoff.   Increase the update rate linearly by say 10ms per iteration (up to the 100ms max you are currently happy with) but cut it in half any time you get a new value.

Interesting. And double every time I get the same value?

**Comment by karger** [comment]
No, that's the linear increase

**Comment by LeaVerou** [comment]
@karger I edited my post shortly after posting it:

> Interesting. And double every time I get the same value? Or increase linearly and decrease exponentially? If it's the latter, why?

**Comment by LeaVerou** [comment]
Just pushed a commit that changes the update frequency to every repaint (uses rAF).
Let's see how this goes, if that turns out to cause an actual bottleneck, we can explore other strategies, such as exponential backoff (I actually implemented EO today, then realized that it may be premature optimization and reverted it).

**Comment by andreasplesch** [comment]
thanks!
