### ISSUE TITLE
js expression with leading newline

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#307]
leads to early return.
This works:
```
[some_property
/* js */
]
```
But this does not (at least in es5 bundle):
```
[
some_property
/* js */
]
```
because the compiled function 
```js
return
some_property
```
will have a `return` on a line by itself.
Here is a simple test:

no newline: https://codepen.io/anon/pen/XzVLzZ?editors=1000
newline: https://codepen.io/anon/pen/rYpEpJ?editors=1000

**Comment by LeaVerou** [comment]
Thanks, that should be very easy to fix!

**Comment by andreasplesch** [comment]
Yes, let's see. 
https://github.com/mavoweb/mavo/blob/master/src/mavoscript.js#L336 has the object literal which is used as the function to be evaluated.

https://codepen.io/anon/pen/YEYoOm?editors=1010
has a possible fix by enclosing the code in parenthesis (the grouping operator) which then allows line breaks.

**Comment by LeaVerou** [comment]
Yup, that was the way I was planning to fixing it too, by adding parens :)

A PR is more than welcome!!

Is there a reason for the whitespace inside the parens or just coding style?

**Comment by andreasplesch** [comment]
Just style.
