### ISSUE TITLE
Blank value is not saved, causing the template value to be rendered when the data is read

### ISSUE THREAD

**Issue by svgeesus** [mavoweb/mavo#311]
It does not seem to be possible to remove an image just by setting it's `src` attribute to a blank string. It appears to work at first, but when the Mavo is reloaded the default image is back.

Steps to reproduce:

1. https://mavo.io/demos/invoice/?storage=local (or some other repo)
2. Edit
3. Edit image, delete url to the logo
4. Save, print; logo not there
5. Refresh, logo returns

**Comment by LeaVerou** [comment]
After some investigation, this has nothing to do with images. The bug is that empty values are not saved, even when there is a non-empty template value, which causes the result to be different when the data is read back. 

Testcase/explainer: https://codepen.io/leaverou/pen/wNmaxN?&editors=1100#0
