### ISSUE TITLE
Internet Explorer not pulling in Mavo data

### ISSUE THREAD

**Issue by brianhaferkamp** [mavoweb/mavo#313]
I've run into an issue with IE not reading data from the JSON file. When I try the same site in Chrome and Firefox, I'm able see the Mavo data being pulled in, but I get no content when I open the site in IE11. You can test this Mavo-powered site across browsers:

http://highwaywebconsulting.com/demos/ubooks/pride-and-prejudice/

I also created a test site that specifically includes a backward compatible version of Mavo as a test case. The Pen is here:

https://codepen.io/brianhaferkamp/pen/xPywyb

You can edit the properties in Chrome and Firefox, but nothing shows up for IE. I have not tried this on Edge to see if the same issue persists.

Screenshots:

Chrome:
![chrome-mavo](https://user-images.githubusercontent.com/18403729/33344121-6878e416-d44d-11e7-843d-f13ce2ff2cfe.jpg)

Firefox:
![firefox-mavo](https://user-images.githubusercontent.com/18403729/33344122-688bf006-d44d-11e7-923f-705ff615d876.jpg)

IE11
![ie-mavo](https://user-images.githubusercontent.com/18403729/33344123-689d2894-d44d-11e7-900a-ac267bf7f61f.jpg)

IE Version: 11.0.9600.18838

**Comment by LeaVerou** [comment]
This was a lot of work, but I'm finally almost there :)
Expect a fix soon, sorry for the delay! :)

**Comment by brianhaferkamp** [comment]
Thank you for your hard work.

**Comment by LeaVerou** [comment]
The change I just pushed should enable some basic IE11 support.
It's not perfect, and I wouldn't recommend *editing* the data from there, but it should at least display the data correctly, which is the most important part.
