### ISSUE TITLE
https://mavo.io/docs/primer Dead Link

### ISSUE THREAD

**Issue by zachleat** [mavoweb/mavo#314]
Trying to click the Get Started link and it takes me to a page that only says:

> Redirecting to /docs/primer/ 

Using Firefox 57.0 (64-bit) on Mac OS X Sierra.

**Comment by LeaVerou** [comment]
Cannot reproduce over here (also FF 57, also OSX Sierra). Have you set any about:config flags? Any extensions?

**Comment by zachleat** [comment]
Huh, working fine for me now too.

I’m not sure what changed but it appears to be fixed now—thanks!
