### ISSUE TITLE
item index from within collection

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#315]
Within a collection properties in expressions refer to the current item. This includes the wrapper property (the current cat in the doc example).

Is there a way to get the index in the complete collection array of the current item ? For example, for a simple counter in a list (1. cat, 2. cat ..)

More generally, is there a way to access the values of other than the current items within a collection ?

**Comment by LeaVerou** [comment]
> Is there a way to get the index in the complete collection array of the current item ? For example, for a simple counter in a list (1. cat, 2. cat ..)

`$index` https://mavo.io/docs/mavoscript

> More generally, is there a way to access the values of other than the current items within a collection ?

`parentProperty.collectionName`
(if collection is not inside another property, just use the app name)

Does this help?

**Comment by andreasplesch** [comment]
Somehow I never looked at the $ special properties to find the index ... Thanks ! It works fine with regular element content and attributes but sofar I could not get it to evaluate to other than 0 with attributes of custom registered elements (x3dom). I will try a couple more things.

**Comment by andreasplesch** [comment]
ok, I had to use mv-attribute to explicitly define the value of the item property. Works fine now:

https://handsomely-yard.glitch.me/

Edit to add spheres and boxes. I think this can be closed.

**Comment by LeaVerou** [comment]
Wow, that's so cool! @karger see, more 3D demos with Mavo :D 

```html
<transform property='box' mv-multiple>
    <transform propery='trafo' mv-attribute='translation' translation='[$index+1] 0 0'>
```

It's very weird that you had to use `mv-attribute` there, it should just work. I wonder if it has to do with the misspelling of `property`? But still, even without property there it should work, since it's inside a collection... Maybe look into it a bit more and if it still needs `mv-attribute` file a new bug with a reduced testcase?

**Comment by andreasplesch** [comment]
Sorry about the typo. $index works without a local property, and with a local property if specified via mv-attribute. I added a cone with a local property and default value allocation (without mv-attribute) for which index stays at 0. The default property value may be the text content which is empty, or  it may be child elements ? Not sure how it matters but it seems to.

Editing 3d content may be fundamentally different than editing a structured document. But x3d is also declarative and has its own template concept (prototypes). I was thinking about plugins dealing with x3d nodes but did not get very far yet.

Expressions are already very useful in a 3d context to do simple math.
