### ISSUE TITLE
$index stays 0 for unknown elements

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#317]
if the element is a property but does not have an explicitly defined value slot via mv-attribute.

```html
<transform property='trafocone' without-mv-attribute='translation' translation='[-$index-1] 0 0 '>
```

live

https://mavo-issue-317.glitch.me/

followup from #315 

without-mv-attribute is not a mavo feature and only used above to make explicit that mv-attribute is not used.

**Comment by LeaVerou** [comment]
This appears to have been fixed, please re-open if that's not the case!

**Comment by andreasplesch** [comment]
yes, looks like it is fixed. thanks.
