### ISSUE TITLE
"Editing" on Mavo toolbar impossible to localize w/o writing CSS

### ISSUE THREAD

**Issue by mycaule** [mavoweb/mavo#319]
It is not right to set language rules into CSS.

See for example [_bar.scss ::after](https://github.com/mavoweb/mavo/blob/a2bed16201337647597da560a021276a6bf9bf4b/src-css/_bar.scss#L117)

```
&::after {
  content: "ing";
}
```

This issue has also been mentionned in [mavo-locale-fr](https://github.com/Falafel65/mavo-locale-fr/issues/1).

**Comment by LeaVerou** [comment]
Yup, agreed!
