### ISSUE TITLE
NPM build issues

### ISSUE THREAD

**Issue by mycaule** [mavoweb/mavo#323]
Hello,

I saw that you have published a package on [NPM](https://www.npmjs.com/package/mavo) and would like to use your library from a JS file, using a JS bundler.

This means writing this from a JS file

```javascript
import mavo from 'mavo' // is this correct ?
```
instead of this in the HTML,

```html
<script src="https://dev.mavo.io/dist/mavo.es5.min.js"></script>
```

But doing `npm install mavo --save` from my Node.js project and then bundling with [parcel bundler](https://github.com/parcel-bundler/parcel)
```bash
$ cat package.json | grep mavo
    "mavo": "^0.1.4",
$ cd node_modules/mavo/dist/
$ ls
0.1.2           0.1.3           index.html      mavo.js
```

The `mavo.js` file loads but here are some problems:
* `package.json` doesn't include  `bliss`, `stretchy`, `jsep` dependencies, resulting in mavo throwing a *Reference error* `Uncaught ReferenceError: jsep is not defined` in the browser (it might be a problem with `gulp` build, I am not sure),
* 0.1.4 and 0.1.5 haven't been published in NPM yet.

You may want to kill the `bliss` and `stretchy` dependencies above in the future as well.

Concerning `jsep`, you could solve the problems you mentionned in the [Mavo functions discussion](https://github.com/mavoweb/mavo/issues/161) modifying the package or choosing another?

Do you plan on real support for Node.js? It could be allow writing desktop applications using [Electron](https://github.com/electron/electron). You may want to update documentation for usage with Node.js as well (NPM page and Mavo documentation).

**Comment by LeaVerou** [comment]
I just published the most recent version to npm. I also added the built files to npm so that nobody would need to use gulp locally.

> package.json doesn't include bliss, stretchy, jsep dependencies, resulting in mavo throwing a Reference error Uncaught ReferenceError: jsep is not defined in the browser (it might be a problem with gulp build, I am not sure)

But these are bundled (and gulp fetches them from the lib folder...). They should be included in mavo.js...

> You may want to kill the bliss and stretchy dependencies above in the future as well.

Why?

> Concerning jsep, you could solve the problems you mentionned in the Mavo functions discussion modifying the package or choosing another?

Not sure what problem you're referring to? I searched for "jsep" in that discussion and found nothing. But choosing another is not really an option, other parsers are WAY larger and much less flexible.

> Do you plan on real support for Node.js?

It’s a nice to have, but not top priority, since the majority of our target group doesn't use npm.

**Comment by mycaule** [comment]
You could modify the `jsep` parser to be able to declare functions (extending the mavoscript language features)?

**Comment by LeaVerou** [comment]
> You could modify the jsep parser to be able to declare functions (extending the mavoscript language features)?

Why would I want to do that and how is it related to supporting npm?

> bliss and stretchy are opiniated libraries.

How so?

**Comment by mycaule** [comment]
You ask too much questions which have simple answers, I am just here to give opinions;

**Comment by mycaule** [comment]
Related: https://github.com/LeaVerou/bliss/issues/107

**Comment by LeaVerou** [comment]
> Related: 

How?

**Comment by mycaule** [comment]
> How? 🤔

I agree.

**Comment by LeaVerou** [comment]
Ok, play time is over, this user is now blocked from all Mavo repos since his behavior was being toxic and unproductive (I even had to google how to do that, there’s a first time for everything!).
