### ISSUE TITLE
Documenting event listeners

### ISSUE THREAD

**Issue by mycaule** [mavoweb/mavo#324]
You may want to update Mavo API documentation regarding event listeners from JS.

See: https://github.com/joachimesque/mv-styleguide/issues/1

**Comment by LeaVerou** [comment]
Yes, that's true, in general the JS API documentation is very, very lacking :(
As is often the case with these things, the reason is limited resources.
Perhaps you want to help? 😀 

PS: For documentation issues, please use the [mavo.io](https://github.com/mavoweb/mavo.io/issues) repo in the future.

**Comment by mycaule** [comment]
If you tell me where I should insert that stuff yes.
Your documentation is really difficult to read, especially colors aren't that great.
