### ISSUE TITLE
nothing is saved without first clicking on editing button

### ISSUE THREAD

**Issue by g-verma** [mavoweb/mavo#327]
When i tries to edit something on page, every time I supposed to first click on 'editing' button and then click on save button to save it.

**Comment by LeaVerou** [comment]
Hi @g-verma, sorry for the lack of response, your bug report somehow slipped through the cracks!
You can use the [`mv-autosave`](https://mavo.io/docs/) attribute to save automatically, and the `mv-autoedit` class to go into edit mode automatically. If you do not wish to have an edit mode at all, you can use [`mv-mode="edit"`](https://mavo.io/docs/properties#mv-mode) on your Mavo root.
Hope this helps, feel free to re-open if you have any more issues!
