### ISSUE TITLE
Improve Github pull request flow

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#336]
Currently, users without commit permissions can save data in their own fork and even send an "edit suggestion" (pull request). However, when they revisit the Mavo, they see the master data, not their own data. To see their own data, they need to use `?storage=...` in the URL, and I doubt anybody will have bookmarked that. This results in them making duplicate changes, as well as an overall frustrating user experience.

It would be easy to just check if a user has push permissions **when they log in**, not when they save, and load their own data if not, and if they have their own data copy.

This would also be a good first PR.

**Comment by LeaVerou** [comment]
@jwass91 should this be closed? I believe you fixed that and there's now a message asking them if they want to switch, right?

**Comment by jwass91** [comment]
@LeaVerou Yes, I believe this can be closed.
