### ISSUE TITLE
Unable to edit property in collection with empty value after disabling and re-enabling editing mode

### ISSUE THREAD

**Issue by visualdatasolutions** [mavoweb/mavo#339]
First of all, this is an awesome project with very easy user interface and huge potentials. Thank you for designing, developing and sharing it. 

Currently after adding an item in a collection, disabling editing mode and re-enabling editing mode, if a property has no value and has not been clicked (events bound but not fired), it is no longer editable. The class name of the element remains "mv-pending-edit".  You can reproduce this issue by adding a new item in the cat collection, disable and re-enable editing on the demo page here https://mavo.io/docs/primer, which is running mavo version 0.1.6. I saw the same behaviour using Chrome and Firefox so the issue is not related to browsers.

Not sure if this behaviour is by design or a bug. It is quite common for people to disable edit mode and preview the work in progress before editing again. Not being able to edit empty fields will cause confusion and frustration, especially when some fields have been filled in and are editable, and the item can not be simply deleted and created afresh. 

thanks for looking into this issue. Your thoughts?

**Comment by LeaVerou** [comment]
Hi there,

Thanks for the kind words!

I can reproduce the issue, thank you!

**Comment by LeaVerou** [comment]
Hi there,

The issue should be fixed now (give it a few minutes to deploy to the website/CDN).
Feel free to reopen this if you come across it again.

**Comment by LeaVerou** [comment]
I've also changed the version on dev.mavo.io (which is what the website uses) to 0.1.7-beta

**Comment by visualdatasolutions** [comment]
Thank you for the prompt solution. The empty fields are editable now after resuming edit.
I am really impressed by your speed to respond and address issues.  Thank you.
