### ISSUE TITLE
IE11 Basic Functionality?

### ISSUE THREAD

**Issue by craigcecil** [mavoweb/mavo#341]
@LeaVerou 

In the Mavo v0.1.5 release (Dec 5, 2017), it mentions "Basic IE11 support!"

Can you elaborate on what 'basic' support is provided?

Currently, I am unable to store or retrieve for display Mavo property values in IE11 or Edge. 

Additionally, there seems to be a Mavo error displayed in IE11 when Mavo attempts to autosave with autosave="0" set.

**Comment by LeaVerou** [comment]
Basic support means support for displaying data and basic expressions (i.e no editing and no referring to deeply nested or ancestor elements in expressions).

What is the error displayed? Could you provide a link to a simplified testcase? (or a demo on the Mavo site that exhibits the problem, that works too)

**Comment by craigcecil** [comment]
The error I'm seeing says, "OH NOES! Problem saving data". Note that I'm seeing this in both IE11 and Edge.

Here's the full HTML of a minimal page which produces this error in both IE11 and Edge. Also, note that the property data does not get saved, and the conditional IF does not work.

<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Mavo Test</title>
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css" />
    <script src="https://get.mavo.io/mavo.es5.min.js"></script>
</head>
<body mv-app="demo" mv-storage="local" mv-autosave="0" mv-plugins="clear">
    <label for="dp-test" id="dp-test-PatternLabel">What's Your Name?</label>
    <input property="username_test" mv-init="" size="30" maxlength="30" name="dp-test" id="dp-test" type="text" autocomplete="off" />
    <input type="submit" value="Reload Page" name="btnReload" id="btnReload" onclick="javascript:location.reload();" />
    <br /><br />
    <fieldset>
        <span id="uef-radioList1PatternLabel">Do you live in the United States?</span>
        <ol>
            <li>
                <input property="residency" type="radio" name="ex_RadioList_1" id="ex_radiolist_1_15" value="yes" />
                <label for="ex_radiolist_1_15" id="ex_radiolist_1_15Label">Yes</label>
            </li>
            <li>
                <input type="radio" name="ex_RadioList_1" id="ex_radiolist_1_16" value="no">
                <label for="ex_radiolist_1_16" id="ex_radiolist_1_16Label">No</label>
            </li>
        </ol>
    </fieldset>
    <div mv-if="residency = no">
        <h4 tabindex="0">Sorry, this application only supports U.S. citizens.</h4>
    </div>
</body>
</html>

**Comment by LeaVerou** [comment]
Oh I see. Yeah, saving doesn't work in IE11. As I mentioned, basic support refers to viewing data and basic expressions (to cover  the use case where you have an editable website and you want IE11 users to be able to read it, but you don't mind editing it in a recent browser). Sorry about that! We could look into it in case it's something easy to fix. Could you please open developer tools by pressing F12, click on "Console" and paste here a screenshot of any errors that appear?

Are you seeing the same issues in Edge too? Edge is definitely more high-priority than IE11. Which versions of Edge did you try? Can you reproduce the issues with the latest (unreleased) version of Mavo? (`https://dev.mavo.io/dist/mavo.es5.js` and `https://dev.mavo.io/dist/mavo.css`)

**Comment by craigcecil** [comment]
I am seeing the same issues in both IE and Edge (version 38.14393.2068.0), using both the stable and latest (unreleased) versions of Mavo.

Also, might be strange, but neither IE or Edge is showing any Console errors in Dev Tools when the test page (above) is loaded.

Background--we are using Mavo as part of the core of our home-grown web prototyping tool for the federal government. The data persistence (saving) and conditional logic (mv-if) are big parts of our use case. They work great in Chrome.

**Comment by craigcecil** [comment]
Did a little more spelunking in IE11, and I traced thru the mavo.es5.min.js code via the IE11 Dev Tool debugger and noticed that there are several errors related to undefined objects, including 'Promise'.

**Comment by LeaVerou** [comment]
Thank you for digging in! If that's the only issue, that's certainly easy to fix :)

Can you try one thing for me please? Include this before Mavo:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise"></script>
```

Does this fix the issues?

**Comment by LeaVerou** [comment]
That is very weird, since the CORS header is added... Is your app online somewhere so I can take a look? Are you getting that CORS error anywhere else?

**Comment by craigcecil** [comment]
OK, since the government agency is 33 verSsions behind on Edge, I did some testing this afternoon on the latest version of Edge (42) and everything is working fine. Since you stated earlier that IE11 does not support data persistence (saving), then I am good here. I am able to get Mavo's conditions working in IE11, and the agency is planning on upgrading the Windows 10 installation and Edge to the latest version by the end of the year. In the meantime, we will continue to use Chrome. Thank you for all your work on Mavo. There is really nothing else like this out there--I've always been a big proponent of markup-based logic.

**Comment by LeaVerou** [comment]
Thank you so much! We would all be elated to see that tool whenever its ready!
Don't hesitate to ask about any issues you run into, either here or on Gitter :)
