### ISSUE TITLE
Non-node related special properties without $ don't update as needed

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#348]
Related to #343 

E.g. `[mouse.x]` just prints 0 and never updates.

**Comment by betaveros** [comment]
Is this bug still present? It seems to work for me: https://codepen.io/betaveros/pen/EeJzpL

**Comment by LeaVerou** [comment]
Oh nice! I don't remember fixing this, but maybe I just didn't CC the issue in the commit? Closing for now, we can always re-open if needed.

**Comment by LeaVerou** [comment]
Actually, no, it's not fixed. If you remove the `$mouse` expression from your demo, it stops working.

The reason it works when you add `$mouse` is because that gets picked up so the `Mavo.Functions.$mouse` object gets updated on mousemove, so then `mouse` reads that too.
