### ISSUE TITLE
Getting "you have your own copy of the data" notice on repo I have commit access to

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#365]
This is what I get when I visit the attribute index on mavo.io: 

![image](https://user-images.githubusercontent.com/175836/42138811-b50ff008-7dc6-11e8-818c-d844b283d0cc.png)

Perhaps it has to do with the username being different than mine? But you're using `this.canPush()` and not just a username comparison...

**Comment by jwass91** [comment]
I thought we wanted to show this whenever you have a fork regardless of whether or not you have commit access. I vaguely remember discussing the case of a blog with several admins where an admin wants to use their fork to submit a PR for their changes even though they have the permission to commit them. 

Now, however, I see how showing the message doesn't make sense in a case like the mavo.io docs.

Either way is going to have drawbacks as there are cases where showing the message is useful and cases where it is confusing and unnecessary. 

I am happy to switch to the other way and check if the user can push. Just let me know which you think makes more sense.

**Comment by LeaVerou** [comment]
I sort of remember this discussion, I think my point was about the PR flow when on the user's fork, not about showing this message.
I think that message is a little confusing when you do have access to the current repo.

(fwiw I didn't even know I had a fork until today! Now I wonder why...)

**Comment by LeaVerou** [comment]
Fixed via https://github.com/mavoweb/mavo/pull/366
