### ISSUE TITLE
Moving pull request code to a plugin

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#367]
I know #364 is still open about redoing the Github workflow, but since other things are prioritized above it, it could be a while before we get to it.
Meanwhile, the Github backend code has exploded in size, and I was thinking it may be a good idea to move the pull request flow to a plugin. Without the plugin, people would still be able to save their edits in forks, the plugin would just enable them to send a pull request.
That would also provide a way to disable the PR flow, which does not exist today.

@jwass91 can you look into how much code that would help us get rid of? It may turn out not to be worth doing after all.

**Comment by LeaVerou** [comment]
I was reminded of this again now that I'm working on a Github Gist backend for #599 so I looked at the Github Backend code again.

It's even more imperative to do it since Jared has moved on to other things and is not maintaining this code any more and there are a bunch of bugs with it. And of course there are the issues with uploads discussed in #538. A plugin would allow users to opt-in to allowing pull-requests, since they may not always be desirable.

@DmitrySharabin any chance this is something you might want to work on? I think it's a reasonable scope and not too hard. It will require new hooks to be added, but that's easy (we can discuss together what hooks would be optimal for this, so that they are more generally useful).

**Comment by DmitrySharabin** [comment]
@LeaVerou 
Sure, Lea. I would love to help. Please give me some time to have a look at the code so I could be more useful and could ask the right questions.

**Comment by DmitrySharabin** [comment]
Can we close this issue now?

**Comment by LeaVerou** [comment]
Sure!
