### ISSUE TITLE
Vocab attribute works only in root (mv-app) element. Typeof without property breaks initialization

### ISSUE THREAD

**Issue by gregid** [mavoweb/mavo#369]
Placing an element with `vocab` attribute in the child of `mv-app` causes mavo to fail initialization - it doesn't recognize the remaining properties:
https://codepen.io/anon/pen/MXGjBv

As suggested by @LeaVerou placing `vocab` in the `mv-app` root makes it work:
https://codepen.io/anon/pen/aKMPMQ

As pointed the problem is related to `typeof=Invoice` being given without property:
https://codepen.io/anon/pen/pKYBre

Adding property makes it work again:
https://codepen.io/anon/pen/RJdOav

**Comment by LeaVerou** [comment]
I believe this was fixed when #262 was fixed. Your first testcase seems to work now. Closing, please comment if I'm wrong!
