### ISSUE TITLE
i am sorry to ask this but i want to learn so please help me 

### ISSUE THREAD

**Issue by FERMAT1991** [mavoweb/mavo#371]
the demo of to-do app work fin in code pen without me adding the javascript code (/js/demo.js) how this is possible if this javascript has no functionality why they add it because the idea behind Mavo is to write less code.
can I make a tutoring website with Mavo?. I am looking for the easy way to accomplish this I am learning now flask and python because I found python easy to learn.
thank you very much.

**Comment by LeaVerou** [comment]
You do not need demo.js for any of the demos to work. That's just used by the Mavo website to add the navigation bar at the top (for next/previous demo etc). I should probably add a comment above it mentioning this.

Regarding your other question, I suppose that depends on what kind of tutoring website you want to make? I would suggest trying and if you run into things that you think Mavo can't do, ask us :)

**Comment by LeaVerou** [comment]
Closing this, since there's no response. If you run into any trouble, feel free to write here or open a new issue!
