### ISSUE TITLE
Next release ETA?

### ISSUE THREAD

**Issue by jeremycook** [mavoweb/mavo#391]
Hello,

When do you anticipate your next release will be? Will you publish to NPM at the same time?

The main motivation for my asking is what you fixed here https://github.com/mavoweb/mavo/commit/9c1e6fcd31a52bc10f1f08f4d1ebf47eac72ac3b

I use Mavo to make `<form>`s dynamic. Currently, anytime a user hits the Enter key and at least one item in a collection is present the first collection item in the form will be removed (because the form submission will go through a Mavo item deletion button) and then form will submit. Obviously not the desired outcome.

Alternatively, would you be willing to do a small release that includes that bug fix before the bigger release you have been working hard on?

**Comment by LeaVerou** [comment]
We will likely do a 0.2.0 release sometime in October. There's been too long without a release (since April, with commits from January!) which is suboptimal.

If that’s too late for you, you can use `dev.mavo.io/dist` and report any bugs you find (which will also help the release), or use a locally downloaded version of Mavo.

Hope this helps! Thanks for using Mavo!

**Comment by jeremycook** [comment]
Thank you. I tried dev.mavo.io/dist, but at the time it was a bit too bleeding edge for my sake (I don't remember why now). I'll be in production soon, but October would be great. I look forward to it! Worse case I fork 0.1.6 and patch in that one change.

Is there a channel for getting updates on releases (via email or whatever) that's not as noisy and easily overlooked as Twitter?

**Comment by LeaVerou** [comment]
There is Mavo’s twitter, where we don't post super often: https://twitter.com/mavoweb

I thought Github exposed RSS feeds for commits and releases, but it doesn’t seem to be the case :(

Btw we would love to see what you’re making with Mavo if/when you’re comfortable sharing it :)

**Comment by jeremycook** [comment]
I'll definitely let you know once I make something with it that is publicly available. It's a really cool library you've made and I love the ethos. My current project is for an intranet, so yeah, no sharing that one.

Here's a thought for announcements. You could do what the aspnet folks do and create an announcements repository like https://github.com/aspnet/Announcements and anyone who watches it will receive emails about issues you post. You can see how they discourage posting issues to it by trying to create an issue on it yourself. So far I've only gotten one or two spam issues from that repo, which is perfectly acceptable and frankly really impressive that the community has been so polite. (And when I say "spam" I really mean they posted a valid question, just to the wrong aspnet project.) I guess there's always a risk though...
