### ISSUE TITLE
Empty expression leads to confusing error message

### ISSUE THREAD

**Issue by betaveros** [mavoweb/mavo#392]
The error Mavo prints to the console is something like this.

Firefox:
```
Oops! 😳 There is something wrong with the expression : expected expression, got ')'
```
Chrome:
```
Oops! ðŸ˜³ There is something wrong with the expression : Unexpected token )
```
(there should be an emoji there, not sure what's up with encoding)

The JavaScript that an empty expression compiles to is basically `return ();`, which is why the parse error is what it is, but this error is not very friendly. Perhaps we should special-case empty expressions to have an error like "There is an empty expression!" Or, I wonder if users might expect an empty expression to evaluate to an empty string or something. Of course, as a programmer I prefer to see the error, but I'm not in the target audience.

This is something I ran into while playing with the inspector and it may be hard to accidentally run into this in the wild.

**Comment by betaveros** [comment]
(It's also not obvious what counts as an empty expression --- only the empty string? If `/\S/.test(str)` is false?)

**Comment by LeaVerou** [comment]
In general, we try to avoid unnecessary error conditions. A blank expression is likely just someone using brackets. There is no reason for an error at all, it should not even be picked up as an expression.

**Comment by betaveros** [comment]
That makes sense, but the case I found this in is the equivalent of somebody writing `mv-value=""`. What do you think the behavior should be then?

**Comment by LeaVerou** [comment]
Empty string then. That's what Angular does too.
