### ISSUE TITLE
Syntactic sugar for editing via select menu

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#394]
A common pattern is to want to restrict a property's value to specific options (like an enum). Currently, this is done by defining a `<select>` menu and either nesting it within the property, or linking to it. This has the benefit of re-using existing HTML knowledge, but is a little clunky. It would be nice to have the ability to do that via an attribute. 
E.g. `data-options="text1, value2: text2, text3, ..."`.

**Comment by DmitrySharabin** [comment]
I believe this issue and [the one we've already closed](https://github.com/mavoweb/mavo/issues/767) are about the same things. Should we close it too?

**Comment by LeaVerou** [comment]
Yes, thanks!
