### ISSUE TITLE
Comparing lists of mismatched lengths extends with `true` (approximately, 1)

### ISSUE THREAD

**Issue by betaveros** [mavoweb/mavo#404]
It is convenient that many Mavo binary operations naturally vectorize across lists so that you can add two lists and corresponding components will be added together, and the shorter list is padded to the length of the longer. However this breaks down when you compare two lists since comparison doesn't have a really sensible identity. It looks like the comparison operators are defined to have `true` as their identity, but this is the identity of `&&`, which is used in the interpretation of chaining comparisons. However this `true` identity is still used to pad lists of different lengths when comparing them, makes comparing two lists of different lengths somewhat nonsensical: e.g. `[1, 2, 3] < [4]` approximately becomes `[1 < 4, 2 < true, 3 < true]`.

I'm not really sure what the best behavior would be in this case. In a vacuum I would expect vectorized operators between lists of different lengths to either fail or use the length of the shorter operand, but it doesn't look like this is consistent with the goals or other parts of Mavo.

**Comment by LeaVerou** [comment]
Oops, it definitely shouldn't be true. This is a good example of a case where we need separate defaults for left and right operands, then we just use `±Infinity` accordingly. Thoughts?
