### ISSUE TITLE
class mv-target-within not added on page load or refresh

### ISSUE THREAD

**Issue by BrooksPatton** [mavoweb/mavo#416]
When I refresh a page that has a `#id` in it the `.mv-target-within` class doesn't get injected into the elements.

When I click on the link that adds the `#id` nothing seems to happen. If I click another link the class gets added as normal.

This can be seen in the example [My Invoices](https://mavo.io/demos/invoice/#invoice1) where the list of invoices is listed despite the `#invoice1` in the url. 

Is there a way to tell Mavo to check the hash and reload?

**Comment by LeaVerou** [comment]
Thanks for reporting this!
I remember this bug, I thought I had fixed it. Will take another look.

**Comment by LeaVerou** [comment]
It is fixed indeed, the Invoices app just uses the latest stable, not the most recent version. :)
