### ISSUE TITLE
refactoring of node.uid  and destroy method

### ISSUE THREAD

**Issue by hopeful2** [mavoweb/mavo#426]
## current status
Currently all node instances are recorded in an array Mavo.Node.all. A node instance uses its position in the array as uid, and when the node instance is destroyed, the array fills this position with null. 

## pros
quick to access child nodes by array index. this is very helpful if we record this position and relative path to other objects, and use this information for the getter function of value object stored in Mavo.elementData. This will avoid accessing a nested object using property path, from root node all the way to the great great great ... grandchild node. 

## potential issues
When nodes are destroyed by batch, and new ones added by batch, the array Mavo.Node.all will grow in size and may end up in a very long array with many null items. this will potentially slow down the operations when we need to loop through the array in the future.  This is not an issue if we loop through all nodes of an app by the node.walk method. When there are many apps on the page, walking within an app probably takes less time than looping through the array of all nodes on the page.

The null items occupy extra memory.

## alternative approach 1
use a dictionary instead, with random string as node id. 

## alternative approach 2
* take the destroyed node out of the array by splicing, without null items
* use a random string as node uid to avoid id clashes. This can be generated with Math.random with a prefix "n" for node. 

## impact
A search in the code base indicates that uid is only used in src/node.js, for accessing the node by uid to replace it with null, and toString function. 

If you think the alternative approach suits the majority of users better, I will submit a PR for this. Let's weigh the pros and cons before jumping into action.

**Comment by LeaVerou** [comment]
I'm not a huge fan of using random strings if we can avoid it. Right now the `uid` carries information about when the node was created relative to other nodes that would be lost if it was just a random string. It's also simpler to type and recognize when logging multiple nodes in the console.

Instead of null, we can just `delete _.all[this.uid]` in `destroy()`. That should not use up any extra memory and seems to preserve array length, so the UIDs should keep increasing. It does make the array holey which is supposed to be slightly slower but let's not prematurely optimize for that yet :)

**Comment by hopeful2** [comment]
I am OK with your suggestion. As long as we don't iterate through the array, longer array is not a problem (yet).  In mavo.destroy method, the nodes of an app can be accessed using mavo.root.walk method.

once mavo.destroy is available, developers may be tempted to toggle on/off apps because that helps to keep things stay functional on a big dom. let's revisit this topic when the array does grow into an issue.

**Comment by LeaVerou** [comment]
Even iterating could be ok, if we use a method that ignores holes, like `.map()` or `.forEach()`.

Do you want to send that 1 line PR to convert the nulls to holes?

**Comment by hopeful2** [comment]
All right I will send a PR before we forget this.
