### ISSUE TITLE
infinite recursion bug when registering cross-app domexpression with multiple external apps

### ISSUE THREAD

**Issue by hopeful2** [mavoweb/mavo#434]
While it is fine to access values from another Mavo app in Mavo expression, trying to access values from multiple external Mavo apps will cause infinite recursion and abort after reaching maximum call stack. The reason is that `mavo.expressions.register()` function keeps calling each other app's `expressions.register()` function and then calls itself recursively when there are multiple external apps involved.

The solution is to track and check if a Mavo app has already registered the `domexpression` instance, and make sure to call `expressions.register()` only once per app. I will submit a PR for this shortly for you to consider.

**Comment by LeaVerou** [comment]
Hi @hopeful2!

Thank you so much for your continued hard work!
Just so I understand the issue, could you please provide a reduced testcase that reproduces the problem? Is it something that happens when writing Mavo HTML or something that happens when using the JS API?

**Comment by hopeful2** [comment]
This bug is hard to reveal with a fiddle or pen. I will create a separate repo to hold html files with simple test cases so as to see the error log in dev console. 

If you save the following code to a local file and check the browser console, you should be able to see the error.  The end user will still see the result of Mavo expressions in UI.  The infinite recursion goes on after registering a domexpression. Chrome on my laptop reported the error as 

```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title> simple test cast </title>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width,minimum-scale=1">

    <link rel="stylesheet" href="https://dev.mavo.io/dist/mavo.css" />
	  <script src="https://dev.mavo.io/dist/mavo.es5.js"></script>

  </head>
  <body>

    <div mv-app="app1">
    	<div property="appname">Mavo</div>
    </div>

    <div mv-app="app2">
    	<div>What do you think about [app1.appname]</div>
    	<div property="rating">awesome</div>

    </div>

    <div mv-app="app3">
    	<h2>Discovery:</h2>
    	<div>	[app1.appname] is [if(app1.rating, app1.rating, app2.rating)] </div>
    </div>


  </body>
</html>

```

**Comment by hopeful2** [comment]
I have created a simple test case to demonstrate the bug in Expressions.register() and Expressions.unregister() functions. Here is the link. 

[Expressions bug test case](https://hopeful2.github.io/simple/index.html)

Firebox on my macbook did not report infinite recursion error  in register function, but it reported the error in unregister function after clicking the button at the bottom of the page.  Chrome reported both errors. 

`ReferenceError: domexpresssion is not defined`
