### ISSUE TITLE
"Uncaught ReferenceError: domexpresssion is not defined" when unregistering domexpresssion involving multiple external apps

### ISSUE THREAD

**Issue by hopeful2** [mavoweb/mavo#436]
Now that I have got `mavo.expressions.register()` working in local dev version after applying patches in PR #435 , the following error was thrown when unregistering `domexpression` involving multiple external apps. 

```
Uncaught ReferenceError: domexpresssion is not defined
at domexpression.identifiers.forEach.id
at Array.forEach (<anonymous>)
at e.unregister
... 
```

It seems when there are multiple external apps, the `domexpresssion` object is destroyed during the loop, and by the time a certain external app's `expressions.unregister(domexpresssion)`  is executed, this object no longer exists. 

I will submit a PR shortly to make sure this object still exists before calling external app's `expressions.unregister` function.

**Comment by LeaVerou** [comment]
Hi @hopeful2,

I'm missing a bit of context here.
Where exactly is the error thrown?
Which loop is `domexpression` destroyed during?
It seems a little weird, because if `domexpression` did not exist, then how did we loop over `domexpression.identifiers`? 

Also, this seems intrinsically linked with #435 and should likely be in the same issue/PR. No need to change anything now, just mentioning this for future PRs!

**Comment by hopeful2** [comment]
At the very beginning I didn't believe this error message. But the error was thrown. It seems a domexpression object was there before entering the first loop, but it was then destroyed during the loop. By the time 

This bug is present only when an expression involves multiple apps. I found this one after filing issue #434 and applying patches in PR #435 in local dev version. It needs a different fix.

I have created a simple test case to demonstrate the bug in Expressions.register() and Expressions.unregister() functions. Here is the link.  You can see the source code in browser, or on the repo [hopeful2/simple](https://github.com/hopeful2/simple/blob/master/index.html).

[Expressions bug test case](https://hopeful2.github.io/simple/index.html)

**Comment by LeaVerou** [comment]
Thanks!
So the bug is only present if an expression references values in other applications?
I see in your testcase you are calling `expressions.unregister()` manually. Does this bug ever organically happen in a Mavo app? Why did you need to call `expressions.unregister()` manually in the first place? What were you trying to accomplish? I'm asking in case there's a different way to do things, not to dismiss your issue!

**Comment by hopeful2** [comment]
Yes the bug only appears when referencing values from at least two other applications. A typical use case is to

* manage the global default value (shared among pages) with one app, 
* manage the custom value of the current page with another app,
* use the values in other apps.

I called `expressions.unregister()` manually just to reveal the bug in the test case. In the project I am working on, the error happened when destroying a Mavo instance, which destroyed all nodes. Our project code does not call this function. `expressions.unregister()` was called automatically during destroying nodes. That is how it caught my attention. Mavo.destroy() involves quite a few changes and is not merged into this library yet. it will take some time to prepare separate atomic PR's. It is easier to trigger this error manually using the current official library.  

thanks again for looking into this. Please let me know if you have found a better way.

**Comment by LeaVerou** [comment]
@hopeful2 When I open your testcase, before I press anything, I get this: 
![image](https://user-images.githubusercontent.com/175836/51329409-1d393280-1a7e-11e9-9f69-88258fba047f.png)

Does this happen with the current (dev) version of Mavo as well? If so, it's a serious bug. If not, your version might have a serious regression!

**Comment by LeaVerou** [comment]
It can't be happening for **any** expression that involves two applications, since there are many examples of that that are not triggering this. E.g. there's a test for that in our testsuite, and it's not triggering any such error: https://test.mavo.io/expressions.html#cross-mavo-expressions

**Comment by hopeful2** [comment]
Well it has happened on Chrome. Firefox did not report it as an error, and ignored the recursion silently. I guess Node does the same, silently ignoring the recursion. 
The recursion wastes cpu cycles, but other code still gets executed. the app seems to be functioning otherwise.

**Comment by LeaVerou** [comment]
The testsuiite runs locally, so if you're running it in Chrome, it's executed in Chrome, not Node. I just opened that test in Chrome before posting, and did not see a recursion error. Do you?

**Comment by hopeful2** [comment]
I was just reading the source code of the official testsuite. There are multiple apps, but each app only references ONE external app. If you change the source code and refer to two other apps, you should see the error too. 

The reason is that when app3 refers to app1 and app2, app1.expressions.register() sees app2 as external, and calls app2.expressions.register(). from inside app2.expressions.register(), it sees app1 as external and calls app1.expressions.register(). so on and so forth.  

This recursion does not happen when app3 only references app1. app1.expressions.register() sees no external app and exits normally.

does it make sense to you?

**Comment by LeaVerou** [comment]
You're right! I added another test (refresh to see it), and indeed it triggers the issue!
Why PR is your fix so I can merge it? The one linked here looks like it's fixing a bug with `unregister()`, not the one you're describing. I seem to remember there was another one?

**Comment by hopeful2** [comment]
I am glad you finally see what I saw. PR #435 addressed that issue, which was reported as a separate bug.
