### ISSUE TITLE
mavoscript mv-edit-list behaves oddly with mavoscript in innerhtml

### ISSUE THREAD

**Issue by lukesmurray** [mavoweb/mavo#441]
I created a codepen replicating this [here](https://codepen.io/lukesmurray/pen/roqyKg). Basically the mv-edit-list doesn't appear to work if the initial value provided is in the innerHTML and is in mavoscript.

**Comment by LeaVerou** [comment]
I'm not sure I understand. Is this what I'm supposed to be seeing in the codepen?
![image](https://user-images.githubusercontent.com/175836/51087421-ae956580-175b-11e9-8a21-645d02a1a497.png)

Oh, I just noticed I can't edit the last one. Is that the bug?

**Comment by lukesmurray** [comment]
Yes that's the bug,  I'm not sure if it's expected or not.

**Comment by LeaVerou** [comment]
Yes, that's expected, computed properties (properties whose value is an expression) are not editable.

One could argue that if `mv-mode="edit"` is set it should override the default behavior although it's unclear to me how the expression is applied if we can also edit the value. I'm gonna close this for now, if you want the behavior changed and can come up with a consistent proposal for how it should work, I'd be open to discussing it!
