### ISSUE TITLE
How I can get raw html from json?

### ISSUE THREAD

**Issue by MaxCpp** [mavoweb/mavo#447]
For example:
`{
    "text": "Lorem ipsum dolor sit amet,<br>consectetur adipisicing elit."
}`
I get `<br>` as text.

**Comment by LeaVerou** [comment]
Hi Max!
Could you elaborate a little bit on what you're trying to do? What is the structure and types of properties in your app? How are you getting the JSON? What are you trying to get instead?

**Comment by LeaVerou** [comment]
Closing, due to no response from OP.
