### ISSUE TITLE
Primitives should have a separate “presentational” value

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#45]
Numbers need a lot of touchup to be presentable (rounding, thousand separators, ±Infinity to ±∞ to name a few), but that touchup should not affect the internal value that will be stored.

**Comment by marcomastri** [comment]
Hello, I have a use case where this gets in the way: I’m setting a value on a CSS property (e.g. `[16*120]px` becomes `1,920px`). Is there a way to show the internal value instead, when needed?

**Comment by LeaVerou** [comment]
Ouch, that's bad. It shouldn't happen in attributes though, could you provide some details about your use case? (Ideally in a new issue, since this seems to be a separate bug)

**Comment by marcomastri** [comment]
It’s not on an attribute, but inside a `<style>` tag. Also, you have the same problem on your SVG demo.
