### ISSUE TITLE
Interactive mv-mode inside other mv-mode element is not working

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#451]
Yet another `mv-mode` bug. 😭This feature is a mess and needs a complete rewrite at some point...

Bug originally discovered by @DmitrySharabin and reported on Gitter.
Reduced testcase (adapted from Dmitry's testcase): https://codepen.io/leaverou/pen/omzoxm?editors=1100

It appears that dynamic `mv-mode` is very buggy when inside an element with its own `mv-mode`. Here are some tests about what happens, based on the testcase above:

| Ancestor mv-mode | Property mv-mode | Result on property |
|------------------|------------------|--------|
| `read` | `edit` | Editable at all times (correct!) |
| `edit` | `read` | Uneditable at all times (correct!) |
| `[if(mode,'read','edit')]` | `read` | Uneditable at all times (correct!) |
| `[if(mode,'read','edit')]` | `edit` | Editable at all times (correct!) |
| `read` | `[if(mode,'read','edit')]` | Uneditable at all times, some hover styling when `mode` is `false` |
| `edit` | `[if(mode,'read','edit')]` | Editable at all times, no styling when `mode` is `true` |
| `[if(mode,'read','edit')]` | `[if(mode,'read','edit')]` | Uneditable at all times |

**Comment by DmitrySharabin** [comment]
Hi @LeaVerou,

I am sorry to say that, but I think I've found a bug. Please take a look at my reduced testcase [here](https://codepen.io/dsharabin/pen/BbjqRY?editors=1100).
