### ISSUE TITLE
Move item bar inside item for collections of primitives

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#453]
Currently, the item bar is **inside** each item for collections of groups, but **after** each item for collections of primitives. However, this complicates many things:

- Styling is complicated
- It means that the item bar is technically outside the scope of each item for expressions (or it has to be special cased) which makes #454 difficult, as well as similar UI customizations from users.
- It's inconsistent since it's inside for collections of groups.

Perhaps we should move the item bar back inside the element, which will simplify these things. It will however mean that we can't have collections on primitives of empty elements like media elements(`<img>`, `<video>` etc), or form elements (`<input>`, `<select>` etc). Or, better, a collection is still created, but has item bar and they see a warning in the console. However, collections of primitives are an edge case anyway, so this is easy to work around by just wrapping in a group (though that may make some cases of templating existing data hard) so I'm leaning towards doing this asap.

**Comment by LeaVerou** [comment]
FWIW I just looked at over 200 use cases of `mv-multiple` ([first 20 pages of this](https://github.com/search?l=HTML&p=1&q=%22mv-multiple%22&type=Code)) and this change wouldn't break any of them.
Virtually all of them were on normal elements (`<div>`, `<span>`, `<li>`, `<tr>`, sectioning elements) with 1-2 on `<option>` which a) were mine and b) don't have an item bar today either.

**Comment by LeaVerou** [comment]
Primitives are properties that don't contain other properties, i.e. whose value is text, a number, or a boolean.

**Comment by karger** [comment]
So <span property="name"> is primitive?  Then I don't understand the 
problem; certainly you can put things inside a span element.

**Comment by LeaVerou** [comment]
`<img property="foo">` is also a primitive and cannot have content.
