### ISSUE TITLE
Localization of static text

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#456]
As a sequel to issue #455... 😃

So, I have an app that I want to be localized in some languages (French for example). Suppose dynamic `lang` attribute is supported by Mavo. And I successfully use that feature.

Working with my [application](https://codepen.io/dsharabin/pen/VgPwWV?editors=1000) I face some other problems: there are some unlocalized strings of text.

For example:
![2019-01-31 1 44 47](https://user-images.githubusercontent.com/9166277/52018015-21dbfd00-24fa-11e9-8a71-60696f089df1.png)
This problem can be resolved by redefining appropriate `id`s and `phrases` from the `locale` file in `<datalist>` element. Like that:
```
<datalist class="mv-phrases" lang="fr">
...
	<option value="delete-item">Supprimer cette tâche</option>
...
</datalist>
```
Moreover, there are fragments of text that can't be localized that way. So to say hard-coded text: `h1`, `p` etc.
![2019-01-31 1 44 20](https://user-images.githubusercontent.com/9166277/52018033-2e605580-24fa-11e9-8580-8e647e7dc6d6.png)
```
<h1>My tasks</h1>
```
and
```
<p><strong>[count(done)]</strong> done out of <strong>[count(task)]</strong> total</p>
```
It would be great if Mavo has a function (the name` i18n` I use as an illustration) that would let us construct expressions like that:

```<h1 lang="[language]">[i18n('app-header')]</h1>```

or

```<button lang="[language]" title="[i18n('reset-button-hint')]">[i18n('reset-button-text')]</button>``` etc.,

where `app-header`, `reset-button-hint`, and `reset-button-text` are the `id`s that are defined in `<datalist>` element:
```
<datalist class="mv-phrases" lang="fr">
...
	<option value="app-header">Mes tâches</option>
	<option value="reset-button-hint">Supprimer toutes les tâches</option>
	<option value="reset-button-text">Supprimer</option>
...
</datalist>
```

**Comment by LeaVerou** [comment]
Hi @DmitrySharabin,

Both of your suggestions would definitely be useful, we could look into implementing it once v0.2.0 is out!

**Comment by DmitrySharabin** [comment]
Hi, Lea!
I'm looking forward for that. Thanks! 😃

**Comment by LeaVerou** [comment]
Hi @DmitrySharabin,

I just pushed an experimental `phrase()` function that does this.
You can use it as `phrase(id)` or `phrase(id, language)` (e.g. `phrase("edit", "fr")`), or `phrase(id, vars)` (e.g. `phrase("http-error", group(status: 404, statusText: "Not found"))`) or all three (e.g. `phrase("http-error", group(status: 404, statusText: "Not found"), "ru")`).

Before I document it on mavo.io, do you want to play around with it a bit and see if it works as expected?

**Comment by DmitrySharabin** [comment]
Yay! Awesome! 🎉  I am definitely going to play around with this function with great pleasure. I was waiting for that feature. But not so fast actually. Thank you very much! 🙌

**Comment by DmitrySharabin** [comment]
Hi @LeaVerou,

I've played around with the `phrase` function. That's what I've discovered (besides its awesomeness 😃 ): I need to have the text for credits in two languages at the bottom of the page. There are some links there, and the `phrase` function drops them. Is there any chance that we could use HTML-snippets as localization strings?

My use case is here: https://codepen.io/dsharabin/pen/bzzyNx?editors=1000

**Comment by LeaVerou** [comment]
Unfortunately not right now, Mavo expressions cannot create HTML. We may introduce syntax for that in the future, but it needs to be an explicit opt-in, because it's dangerous security-wise.

**Comment by DmitrySharabin** [comment]
Ok. I got it. Thank you. This function IS already awesome: I could localize my app!

I am eager to see all the new features you are adding to Mavo 0.2.0. Good luck, Lea!

**Comment by karger** [comment]
I'm curious about why html creation is necessary.  When does the structure of the html itself need to be different, as opposed to e.g. attributes that can show/hide different parts of the structure?

**Comment by LeaVerou** [comment]
@DmitrySharabin Btw a workaround for certain cases could be to use the Markdown plugin (though that would only work if the element containing the expression is also a property).

**Comment by DmitrySharabin** [comment]
> I'm curious about why html creation is necessary. When does the structure of the html itself need to be different, as opposed to e.g. attributes that can show/hide different parts of the structure?

Hello Mr. Carger! If you give me some time, I'll think it over.

All I can say for now is that once I’ve tried to use Mavo for the first time, I was going to build a very complex app (my mistake): kind of tests constructor. Then I thought that I would need to generate the HTML code inside my app on the fly: an end user would choose the type of the question (single choice, multiple choice, arrangement, etc.) and based on his choice Mavo would dynamically change (generate) the HTML code. Unfortunately, I couldn't put my ideas into HTML code then, and I gave up. I’m definitely going to make one more try to build that app a bit later.
