### ISSUE TITLE
Information about keys pressed during data action should be accessible in expressions

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#463]
Even though v0.2.0 is currently feature locked, we need to make an exception for this because otherwise it will include a significant regression (#459).

As a minimum, we need to expose the state of modifier keys that triggered a data action (akin to `evt.shiftKey`, `evt.ctrlKey`, `evt.metaKey` and `evt.altKey` in JS).
However, this opens Pandora's box in a way: What other event properties should we expose? E.g. what about which mouse button was clicked?
Should we do this via individual special properties (e.g. `$ctrl`, `$cmd`, `$alt`, `$shift` or perhaps  `$ctrlKey`, `$cmdKey`, `$altKey`, `$shiftKey`) or some sort of event object (e.g. `$event.ctrlKey`)? The latter is more flexible, but closer to JS, whereas the former is more readable and intuitive, but we need to add a new special property for each event object property we want to expose. However, it does mean that we can do "magic" over them, e.g. `evt.metaKey` isn't very useful on its own because it creates shortcuts that cannot be triggered on Windows, whereas we can wrap it with something like `$cmdKey` which uses `metaKey` on Mac and `ctrlKey` on Windows. Perhaps we should expose both the event object (for advanced users) and some nicer helper properties?

Eventually data actions will be triggerable via the keyboard as well, but we haven't discussed that syntax at length. Perhaps we should, since this is related. Obviously we'd need to figure out which key was clicked, but would that be part of the trigger (e.g. `mv-action-trigger="Ctrl + A"`) or part of the expression (e.g. `mv-action-trigger="keyup" mv-action="if ($key = 'A' and $ctrl, add(...)"). Obviously the former is easier, but less flexible: What happens if on the same element we need a certain action for Ctrl + A and a different one for Ctrl + B? Perhaps both of them should be possible? In that case, we can just expose modifier keys for now, and leave everything else for v0.3.0?

**Comment by karger** [comment]
I think for many cases an mv-trigger attribute could be used to specify the modifier keys or the keyboard press or whatever (mv-action-trigger seems redundant).  But, what to do when you want to have multiple triggers for distinct actions?  in particular, there may be cases where you have tens of different hotkeys for a particular element.

In that case it seems like you would want to take advantage of html's already existing structure to help organize everything.  for example, inside the element you want to trigger you could have &lt;div class=mv-action-table&gt; and inside it a list of elements that each specify a trigger and a corresponding action, with the understanding that they all apply to the parent element.   As an alternative to nesting inside you could refer to an elsewhere "action list" similar to the datalist construct.  (this could also let you use the same action for multiple elements)

But then for more advanced programmers you probably do want to have "what was the input" variables that can be checked in the expression

**Comment by LeaVerou** [comment]
Testcase that should eventually make it into the testsuite in some form: https://codepen.io/leaverou/pen/wNPPgJ?&editors=1100#0
