### ISSUE TITLE
When using mv-attribute to bind to an attribute, a false value should not hide the element

### ISSUE THREAD

**Issue by karger** [mavoweb/mavo#464]
By default, an element with a property tag associates the value of the property with the content of an element.  This can be overridden by the mv-attribute attribute which associates the value with the specified attribute.

Separately, when the value of a property is false, Mavo hides that property's element.

These two rules interact badly.  If you've associated your property with an attribute so you can use something else for the content, then Mavo *still* hides the element when the property is false.  Instead, using mv-attribute should decouple the content from being affected by the property value.

**Comment by LeaVerou** [comment]
I agree this behavior is more reasonable and should be very easy to implement. While technically an enhancement and a breaking change, I think we can get this in to v0.2.0 and it shouldn't break (m)any use cases.
