### ISSUE TITLE
Remove support for Microdata for defining Mavo stuff

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#479]
Currently, Mavo supports both RDFa(-inspired) and Microdata attributes for defining what the properties are.

However:

- This fact is undocumented (except a tooltip in one of the demos in the homepage that mentions `itemprop` in passing as another way to give one's property a name which will still work). Everywhere in the docs the RDFa-inspired syntax is used.
- As #262 shows, this can lead to unexpected behavior because people might use both Microdata for data, and Mavo's attributes, not knowing that Mavo picks up both.
- I can almost hear @karger saying "but it doesn't hurt to leave it in". It does. Everything has a cost. It adds extra complexity in a number of places, which is not needed if almost nobody uses it (and it causes confusion).

[Searching Github for mv-app itemprop](https://github.com/search?q=mv-app+itemprop&type=Code) brings up very few results and after a closer look, it appears that there is only one person using Mavo in that way: this website https://github.com/anton-v-svetlov/anton-v-svetlov.github.io/
There is also https://github.com/christinajohnstonweb/christinajohnstonweb.github.io/blob/master/web_reset/jekyll/update/2017/09/01/welcome-to-jekyll.html but it looks like an experiment.
For comparison, [searching for mv-app by itself brings up hundreds of results](https://github.com/search?l=HTML&q=mv-app&type=Code).

Proposed plan of action:
- We remove Microdata from the entire Mavo codebase asap. Instead, we add a bit of code that adds `property` for each `itemprop` and `typeof` for each `itemscope` and warns the user that Microdata syntax will be removed in the next stable version.
- Then, in the next stable, it's just a matter of deleting that bit of code. We can even offer it as a plugin if any people complain about their sites breaking.

**Comment by karger** [comment]
Before we completely remove support, note that google seems to be 
pushing hard for microdata https://schema.org/docs/gs.html and what 
google wants they often get.

What if we just added an attribute to activate/deactivate microdata 
parsing, and defaulted to off?  For now, you could lazy load the code to 
do that, but we could also watch the logs to see if it becomes popular 
enough to include by default....

------ Original Message ------

**Comment by LeaVerou** [comment]
Yeah, the idea was originally that Mavo would piggyback on existing data definitions on the page, but at this point Mavo has evolved into its own language and only shares 2-3 attributes with RDFa, and I'm not sure it helps to combine it with the data definition language of the page. It can still get names from `itemprop` (just like it does from `class` or `id` if a property value is not provided), but I think there's value in having one way to define what the Mavo properties are.
Right now you can even mix and match, e.g. use `itemprop` instead of `property` but still `typeof` for groups, which is certainly wrong.

**Comment by LeaVerou** [comment]
@karger, please make sure to read my edits before you respond

**Comment by LeaVerou** [comment]
I was just making some changes so we can at the very least remove selectors that mix the two, e.g. `[typeof][itemprop]` and so on.
I eliminated a bunch from the JS, but when I went to the CSS, there was nothing.
So it turns out that we always set the RDFa-inspired attributes, even when what we find at first is Microdata, i.e. `<span itemprop="foo">` becomes `<span itemprop="foo" property="foo">`. 🤢

**Comment by LeaVerou** [comment]
@karger thoughts? I was hoping for a reply to my comment from 9 days ago.

**Comment by LeaVerou** [comment]
Recording F2F resolution from Friday: We concluded to remove support for Microdata, and create a plugin for those who need it.
