### ISSUE TITLE
outsideCollection where outsideCollectionProperty = localProperty produces unexpected results

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#484]
Originally discovered by @karger.
Testcase: https://codepen.io/leaverou/pen/RvEKyW?&editors=1100#0

Testcase schema is:

- col1#
	- name
	- foo
- col2#
	- name
	- bar

`col1 where foo = bar` from **inside** col2 items produces unexpected results. The expected result is returned by `filter(col1, col1.foo = bar)`. `col1 where foo = this.bar` will also produce the expected result.

This is not exactly a bug, but the behavior of Mavo is quite unintuitive.

**An explanation of what's going on:**
When you write `col1 where foo = bar`, it gets rewritten internally to something like `filter(col1, scope(col1, foo = bar))` where `scope(A, B)` gives you the B you'd get if you had written B inside A. It's an undocumented function that's currently only used internally, to implement the `where` operator.

The reason this happens is so that you can have expressions like `woman where age > 30` where the women are filtered by their own ages, and not by the ages of man items that just happened to be first in the page.
So essentially, you're comparing `col1.foo` and `col1.bar`, but you're expecting to compare `col1.foo` and `this.bar`.

The problem is that `foo = bar` needs to be evaluated **before** the expression reaches the `where` operator. So it has to pick a scope: either the scope it's used in (the default behavior of every expression), or the scope of the first operand of `where` (via rewriting). The former would fix this problem, but led to incredibly confusing behavior when there were collections with internal properties of the same name (e.g. `col2 where name = 'name2'`) filtered from the outside, so we changed it to the latter early on.

It's also not possible to pick a different scope per identifier, based on the filtered collection, since expressions are rewritten before any data touches them.

As we've seen, none of the two possible scoping behaviors are optimal. I wonder if there's any third option that would do the right thing in this case, without breaking other cases. Basically, you want to prioritize the properties immediately available in the current scope, and then defer to the scope of the first operand.

**Comment by karger** [comment]
I hesitate to suggest, but we could introduce some disambiguating 
syntax.

   Filter A on x,y where x..a..y...b.

could mean that when you filter collection A, any references to x and y 
are references to properties "inside" A (should be evaluated inside A's 
scope) while any other references are not.

Or, going the other way, we could introduce a this construct to qualify 
terms that should be evaluated in the current scope instead of the 
filtered collection's scope.

    Filter A where x... this.a... y... this.b


------ Original Message ------

**Comment by LeaVerou** [comment]
@karger Disambiguating syntax exists already (and your suggested `this` is already implemented, I even used it above). Different disambiguating syntax also existed even before the rewriting. The issue is about avoiding unexpected results that lead people to have to search what they did wrong and what kind of disambiguating syntax they have to choose.

**Comment by karger** [comment]
I know there's disambiguation like the filter operator but I think that 
goes into relatively technical territory compared to just extending the 
syntax of the where operator.

------ Original Message ------

**Comment by LeaVerou** [comment]
@karger did you miss the `col1 where foo = this.bar`?

**Comment by karger** [comment]
It's not in the codepen and I missed it in the note.

------ Original Message ------

**Comment by LeaVerou** [comment]
Ok, I think I have a fix, though I'm not sure if I should push it.
It's based in the same way that `this`/`$this` works. The current scope is passed as a parameter to the rewriting function and its properties become unscopables, so they pass through the dynamic scoping imposed by `scope()`. So, the expression is still scoped to the first operand, EXCEPT `this` and properties that are immediate children of the current scope.

- Could this break anything?
- What about descendant properties of the current scope?

**Comment by karger** [comment]
Also, consider a scoping like
a multiple
---b
c multiple
---d
---a where b... d...

In this case, it seems pretty obvious that author wants to refer to d inside current c, but refer to b of each a as it is being filtered.  The disambiguation here would seem to be clear because there is no b inside c and no d inside a.  Does that work?

**Comment by LeaVerou** [comment]
@karger How is this different than the use case explained in the original post and the testcase? It seems exactly the same. Your a = col1, c = col2, b = foo, d = bar.

**Comment by karger** [comment]
yes same schema; I was proprosing requested "third options"

**Comment by LeaVerou** [comment]
@karger https://github.com/mavoweb/mavo/issues/484#issuecomment-464915946

**Comment by karger** [comment]
You're suggesting only immediate children of current scope be privileged.  But what about children of ancestors of the current scope?  I know that's vague--- the collection being filtered might itself be such an element,---but that was what came up in my use case that originally hit this problem.

**Comment by LeaVerou** [comment]
> But what about children of ancestors of the current scope? 

Not sure there's a clear correct behavior here: the expression could be referring to either.

> but that was what came up in my use case that originally hit this problem.

Not sure we're on the same page, because the fix I'm suggesting does fix your use case that originally hit this problem (I just verified it).

**Comment by karger** [comment]
Here's another possibly kooky heuristic.  What if you privilege singleton values over collections?  E.g., where a=b seems more likely to be wanting to compare a single a to a single b.  So if one of your scopes yields a singleton eval while the other yields a collection, its likely the singleton that is wanted.

**Comment by LeaVerou** [comment]
Like I said, the `a=b` needs to eval before it touches the `where`.

**Comment by LeaVerou** [comment]
I've just changed the fix for now to only privilege child properties.
The problem with privileging descendant properties is that if the `where` is in the root (as often happens) this is ALL properties!! Any ideas @karger? :(

**Comment by LeaVerou** [comment]
This fix also broke things like `name where age > 40`, not sure why, investigating.
