### ISSUE TITLE
TypeError: Not enough arguments to Document.evaluate

### ISSUE THREAD

**Issue by joyously** [mavoweb/mavo#491]
The Mavo docs and demos pages are not working, since recently, in my normal browser (Sea Monkey -Linux). They work in Firefox 65.

The console shows `TypeError: Not enough arguments to Document.evaluate` in https://dev.mavo.io/dist/mavo.es5.js on line 1419.

**Comment by LeaVerou** [comment]
Hi @joyously, I cannot get my hands on SeaMonkey, since I use OSX and Browserstack doesn't seem to have it but I just pushed a fix based on what I think is the problem, please test and let me know if it was fixed!

**Comment by joyously** [comment]
Yes, both the Plugins page and the Demo page are working again.
Thanks!  I guess you need some browser that uses es5, to test.

**Comment by LeaVerou** [comment]
> Yes, both the Plugins page and the Demo page are working again.

Yay!

> I guess you need some browser that uses es5, to test.

`document.evaluate()` is a DOM API, not part of ECMAScript, so es5 has no bearing here.
