### ISSUE TITLE
Re-entering edit mode remembers last state

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#492]
Ways to reproduce:

- Enter edit mode. Click to edit a property. While it's focused, exit edit mode. Do something else. Then enter edit mode again. The last edited property becomes focused and selected.
- Enter edit mode. Click to edit a property that is edited via a popup. While the popup is open, exit edit mode. Do something else. Then enter edit mode again. The popup of the last edited property opens.

While remembering state in general is a good thing, in this case it's disruptive, because the user themselves has forgotten it, done something else and is just left puzzled why this random property is focused or has its popup open.

**Comment by DmitrySharabin** [comment]
Could we please give this issue a bit higher priority? Every Mavo newcomer will face this issue. It's especially noticeable when working with images, or `<meta>` elements—every time after switching into **Edit** mode every single previously generated popup re-appears.
Please, please, please. Let's fix that asap. 🙏

**Comment by LeaVerou** [comment]
@DmitrySharabin Last time I looked into it, it was pretty difficult to fix without introducing other issues. That part of the code is quite messy. I will take another look in a few days, once I finish a few other things I'm working on.

**Comment by DmitrySharabin** [comment]
Sure! I understand. Thanks.

**Comment by LeaVerou** [comment]
I believe this has been resolved with the recent editing changes?

**Comment by DmitrySharabin** [comment]
I checked it in a couple of my pens with images. And 🥁 it's fixed!!! Yay! 🥳  Thanks!

**Comment by LeaVerou** [comment]
Yay! Closing this then.
