### ISSUE TITLE
<datalist> translations should take precedence over existing translations in current locale

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#501]
When I try to redefine text for a localization string with the `phrase` function, it fails with Russian and Hebrew locales.
The testcase is here: https://codepen.io/dsharabin/pen/XGKNBw?editors=1000

**Comment by LeaVerou** [comment]
So the problem is that for non-English locales, the datalist doesn't override existing phrases? Or did I misunderstand?

**Comment by DmitrySharabin** [comment]
For the Greek and the French locales it works, but for the Russian and for the Hebrew—doesn't. And that's weird.
I also noticed that some of the phrases are being overridden, and the others are not. It might be my mistake, but I can't find it.

**Comment by LeaVerou** [comment]
So it looks like the reason this happens is that the Greek and French locale don't have a translation for "Export" at all. 
This is clearly a bug; the `<datalist>` should take precedence.
