### ISSUE TITLE
delete() doesn't empty collections

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#513]
If I correctly identified the problem, my testcase is here: https://codepen.io/dsharabin/pen/rRoGQo

**Comment by LeaVerou** [comment]
It looks like the numbers get deleted but the expression doesn't get updated. Is that your experience too?

**Comment by DmitrySharabin** [comment]
Yep. I discovered that today in my other app—[Flexbox Demo](https://codepen.io/dsharabin/pen/PxbZXX).

It is noteworthy that if you add only one element, then everything works fine.

**Comment by LeaVerou** [comment]
> It is noteworthy that if you add only one element and delete all after that, then everything works fine.

Interesting. I've also noted that if it's a collection of groups, the bug also doesn't happen.

**Comment by LeaVerou** [comment]
Actually, it's even more narrow than that: It seems to happen only on collections of simple properties, whose default value depends on `$index`. The bug is triggered because behind the scenes, items are deleted one by one, and the changing `$index` causes the property to re-attach itself to its parent collection (which is a bug). Hmmm.

**Comment by DmitrySharabin** [comment]
I would have never found the cause of that bug! 😂 The only thing I believe in is that you will fix it. I wish you good luck, Lea!

**Comment by LeaVerou** [comment]
Btw this is way more complicated to fix than it looks at first, which is why it's taking so long. But it helped me discover a major memory leak (expressions of deleted items are still evaluated, forever), so fixing it should speed Mavo up a fair bit!

**Comment by LeaVerou** [comment]
Finally fixed this and the number of other issues this unearthed.
Thank you so much @DmitrySharabin for finding this!
Now fingers crossed my commits don't introduce any regressions! 🤞

**Comment by DmitrySharabin** [comment]
You are always welcome Lea! Glad if I could help somehow. :) I continue to play with Mavo then.
