### ISSUE TITLE
Uppercase in mv-attribute results in broken property value in expressions

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#515]
This is rather strange. But a custom attribute with a name ending in String does not get its expression evaluated. I think this only happens in unknown elements. Here is the example, a modified Mavo test:

https://bl.ocks.org/andreasplesch/30f855de85dc6d819f3958dd06018c0b/ade05349714f954557524decf39939da0e52a9f8

The background mv-attribute test is duplicated. The only difference is that the first test has an attribute name ending in String.

**Comment by LeaVerou** [comment]
Hi there,

Thank you for reporting this!
Could you please create a reduced testcase that with the minimum amount of code to reproduce the issue? I looked at the link you provided and I'm a bit lost since there's so much going on (I understand it's copied from our tests and modified, but it's still hard to track down the individual issue). 
You may find play.mavo.io useful for creating reduced testcases.

**Comment by andreasplesch** [comment]
https://codepen.io/anon/pen/ZZpvgw?&editors=1100#0

could be even smaller

**Comment by LeaVerou** [comment]
Thanks!

Interesting. There's definitely a bug at play here, though I don't think it's what the title describes. I think it has to do with the uppercase character, e.g. if I use `stylestring` it works. Will investigate further.

**Comment by LeaVerou** [comment]
Yup, it's the uppercase. Here's an even more reduced testcase: https://codepen.io/leaverou/pen/XQjEXN?&editors=1100#0

I suspect it has to do with the fact that in HTML attributes are not case sensitive, so Mavo is trying to find an attribute that doesn't really exist or something like that. It should be easy to fix :)

**Comment by andreasplesch** [comment]
Thanks ! I did not get further with narrowing down and had to base the issue title on that. Somewhat related: Is xhtml supported ? I guess time to try it.

**Comment by andreasplesch** [comment]
Oh, I did not see that
https://github.com/mavoweb/mavo/commit/03e855694647a7e0f1710bada7aa274392261e0f
just normalizes to lowercase. So .xhtml would not work since it is case sensitive. It is not used much anyways.

**Comment by LeaVerou** [comment]
Look closer :) It only normalizes to lowercase if `document.xmlVersion` is falsy, which only happens in HTML.
Yes, XML should be supported (though it's less tested, so you may find bugs). There are some important use cases we want to support with using Mavo in SVG documents, so we're very keen on supporting XML :)

**Comment by andreasplesch** [comment]
Right there and I did not realize ... X3D is xml, and has SVG in mind as a model on how to integrate with HTML.
