### ISSUE TITLE
External attribute updates no longer trigger property updates in expressions if property value is in attribute

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#520]
Changing a property attribute via javascript does not lead to updates of the property value:
https://codepen.io/anon/pen/ZZBYmj?&editors=1000
However, it used to work in the stable version:
https://codepen.io/anon/pen/zXorPJ?editors=1000
or here
https://impossible-hydrofoil.glitch.me/
[but split does not work yet in the stable version]

**Comment by LeaVerou** [comment]
Interesting. It looks like the attribute does get updated, but for some reason the update is not reflected in the expression. Definitely something we should investigate and fix before 0.2.0 is out, thank you so much!

**Comment by LeaVerou** [comment]
It also seems to have to do with the attribute: if there's no `mv-attribute` and the JS updates `textContent`, it works. Different attribute names also fail.

**Comment by andreasplesch** [comment]
Yeah, the attribute gets updated as it should since Mavo probably does not play a role in that. Somehow, the expression is never updated. Some triggering seems to be missing.
It still works when mutating the attribute early:
https://codepen.io/anon/pen/jRVLRY?editors=1000
As well as later but only if textContent is also mutated. Without the textContent mutation the attribute mutation is not picked up later.

**Comment by andreasplesch** [comment]
Mutating textContent from the event handler also works to  trigger property updates:
https://codepen.io/anon/pen/LvbzQN?editors=1000
So I guess this could be a workaround although actual content changes are required. Just setting textContent to the same value each time does not count as a mutation.

**Comment by andreasplesch** [comment]
Thanks, works for me !

**Comment by LeaVerou** [comment]
Hi @andreasplesch,
Since the fix introduced a regression in #533, I had to revert it and push a different fix, which seems to address this issue without introducing a regression (that I'm aware of!). Could you please verify that it fixes your use cases? I have checked it against your initial codepen. Thanks!

**Comment by andreasplesch** [comment]
My original use case was this:
https://dragthebox2.glitch.me/
It seems to work well with the latest dev.
