### ISSUE TITLE
Can't dynamically assign classes to the time element

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#525]
If I tried to implement that feature, it would break the UI for the `time` element: the corresponding datepicker widget won't even appear.
The reduced testcase is here: https://codepen.io/dsharabin/pen/rgBgRm

**Comment by LeaVerou** [comment]
Unfortunately, this is another instance of this long-standing bug: #30

Basically, both the expression and Mavo are trying to modify the class attribute, so Mavo loses, doesn't get to add its `mv-empty` class, so the placeholder text doesn't get added and everything is out of whack.

One workaround would be to use a `data-*` attribute and an attribute selector instead.
Sorry about that, it's kind of a horrible bug, and really difficult to fix :(

**Comment by DmitrySharabin** [comment]
Oh! I get it. Thanks.

Sorry for duplicating issues. I'll try to be more accurate next time.
And bugs don't bother me at all (you have nothing to sorry for): for me, it's more important to be aware of them and have a workaround. :)

As always, may the force be with you! :)

**Comment by LeaVerou** [comment]
Don't be sorry! That bug was very poorly worded since it was filed before Mavo was publicly released, so it was written for Mavo developers and would have been impossible to find.
