### ISSUE TITLE
A collection defined with the `mv-multiple="collectionName"` attribute inside a property breaks the group logic

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#535]
That's really strange (that had never happened before). I made some testcases: https://codepen.io/dsharabin/pen/ZdQbXJ?editors=1000

I might describe the problem not very well. I hope the idea would become clear from the testcases.

**Comment by LeaVerou** [comment]
Oh wow, yeah, that's definitely a regression. Thanks Dmitry!!

**Comment by DmitrySharabin** [comment]
You are always welcome, Lea!

**Comment by LeaVerou** [comment]
Hi Dmitry, I just pushed a fix! I've tested it a bit, but if you have time, more testing to see if it broke anything else is appreciated!

**Comment by DmitrySharabin** [comment]
Hi Lea! Thanks. Sure, I'll test it.
