### ISSUE TITLE
Allow specifying data transform via custom JS function

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#536]
Idea inspired by @plehegar's markup-based system.

While we do generally try to avoid any need for custom JS, sometimes custom things are needed. We do have `mv-path` for simple property-chain transformations and property lookups, which has the benefit of being automatically reversible, but that doesn't cover all possible transformations, and even for good JS developers, it's kinda tricky right now to write a custom data transformation.
We should allow the user to specify custom transformations (in/out), either in MavoScript or JS, and possibly even make the current ones a special case of those (though that would be backwards incompatible, but hey, we're still in v0.x.y).

**Comment by LeaVerou** [comment]
Actually, if all we care about is transforming root data before load & before save, this can be easily done with the current hook system (I've just added another hook to facilitate). E.g.:

```js
Mavo.hooks.add("render-start", function(env) {
	if (this.id !== "myMavoApp") {
		return;
	}

	// Transform env.data before rendering
});
Mavo.hooks.add("getdata-end", function(env) {
	if (this.id !== "myMavoApp") {
		return;
	}

	// Undo env.data transformation before saving
});
```

So if this covers use cases, maybe this can be a documentation issue? Are there use cases for doing this on a node-by-node basis?

**Comment by LeaVerou** [comment]
@DmitrySharabin we should probably mention this somewhere in the docs, what do you think?

**Comment by DmitrySharabin** [comment]
Totally agree! I even bookmarked this issue to be able to re-use the code snippet you suggested when needed. 😅

What if we add a new subsection to the [For JS developers](https://mavo.io/docs/js) section? How would we name it? What about _Transforming root data before load and/or save_?

**Comment by LeaVerou** [comment]
Sounds good!

**Comment by DmitrySharabin** [comment]
It’s my pleasure! Get ready for the PR. 😉

**Comment by DmitrySharabin** [comment]
@LeaVerou Done! Please feel free to correct my wording.
