### ISSUE TITLE
Allow specifying different upload backend than storage backend

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#537]
E.g. someone using local storage might still want to upload images to Github. Or there could even be plugins for backends that are only suitable for uploads, e.g. Imgur.

Implementation details:

The code already makes a distinction between the storage backend and the upload backend (however `this.uploadBackend` is currently just a getter that returns the storage backend IFF it has an upload method), so this should be rather easy to implement.

**Comment by LeaVerou** [comment]
@winniejo You mean like imgur?

**Comment by winniejo** [comment]
Hi Lea , No just a plane server in php mavo
but Its solved by Falafel65 but worth mentioning !!

see: https://github.com/Falafel65/mavo-php/issues/11

Thank U also for the work sofar.

W.J.

**Comment by webil13** [comment]
👍
