### ISSUE TITLE
Data are shown only if logged in

### ISSUE THREAD

**Issue by HRSlab** [mavoweb/mavo#542]
Hi everybody and thank you for creating Mavo. 

Recently I am getting a weird behavior. 

This happened after I changed the repo from public to private, but I'm not sure if it is related to the issue. Here the details: 

## CASE:

*When* user is **logged-in**  > can see stored data.
*When* user is **logged-out** > can not see stored data.

**`mv-app` and `mv-storage` setting:**

```HTML
<div mv-app id="Feature" mv-storage="https://github.com/USERNAME/REPONAME">
<div class="mv-bar" mv-bar="no-login"></div>
```

## EXPECTED BEHAVIOR:

*When* user is **logged-in**  > can see, edit, add and delete data.
*When* user is **logged-out** > can only see stored data and perform allowed actions (i.e. click on buttons, etc..)

### Logged-In:

<img width="491" alt="logged-in" src="https://user-images.githubusercontent.com/44086439/61935764-7f25a800-af8b-11e9-933b-d301b1a4b13f.png">

---

### Logged-Out:

<img width="469" alt="logged-out" src="https://user-images.githubusercontent.com/44086439/61935765-7fbe3e80-af8b-11e9-9616-ab474102bc12.png">

---

#### Details:

> - MacBook Pro
> - macOS High Sierra `Version 10.13.6`
> - Safari, Chrome, Firefox
> - Tested: Friday, July 26, 2019

**Comment by DmitrySharabin** [comment]
> This happened after I changed the repo from public to private, but I'm not sure if it is related to the issue.

As far as I can judge this is exactly why you face this issue. You can read about it [here](https://github.community/t5/How-to-use-Git-and-GitHub/Can-I-give-read-only-access-to-a-private-repo-from-a-developer/td-p/1967).

I think Lea can give you more details about that as that was she who wrote the Github backend.

> When user is logged-in > can see, edit, add and delete data.
> When user is logged-out > can only see stored data and perform allowed actions (i.e. click on buttons, etc..)

I believe you might get the desired result via CSS by following [these](https://mavo.io/docs/ui#styling-with-css) instructions.

> <div mv-app id="Feature" mv-storage="https://github.com/USERNAME/REPONAME">
> <div class="mv-bar" mv-bar="no-login"></div>

One more thing: the `mv-bar` attribute is typically specified on the Mavo root (the element with the `mv-app` attribute). So in your case, I would suggest changing the code slightly:
```
<div mv-app id="Feature" ... **mv-bar="no-login"**>
<div class="mv-bar"></div>
```

**Comment by HRSlab** [comment]
Thank you for your precious suggestions @DmitrySharabin. 

Definitely, the issue is related to the private repository. I changed it to public and work fine. I changed also the mv-bar position to Mavo root. Could be useful to have a Github backend working on the "private" mode. Maybe @LeaVerou can provide more information about how to make it work.

**Comment by LeaVerou** [comment]
Yup, this is a feature, not a bug. It's done this way so that people can have apps that handle sensitive data. Also, if your repo is private, the Github API won't let us read the data anyway. Furthermore, Github doesn't allow logged out users (or even any logged in user that has not been explicitly added as a collaborator) to edit data in a repo, so it looks like the access control model you have in mind cannot be supported by Github as a storage backend. Perhaps [Google Drive](https://plugins.mavo.io/plugin/gdrive) would allow setting such permissions and, failing that, [Firebase](https://plugins.mavo.io/plugin/firebase) gives you all the flexibility, but is a bit more involved to set up.

Hope this helps!

**Comment by HRSlab** [comment]
@Thank you son much @LeaVerou. It works with Google Drive. and I will soon try with Firebase.
