### ISSUE TITLE
<pre> is edited via single line text field, not multiline <textarea>

### ISSUE THREAD

**Issue by karger** [mavoweb/mavo#543]
If you have a <pre property=""> element inside an mv-multiple element and edit the <pre> contents, a return does not cause a newline to be inserted in the <pre> field; instead a new item is generation in the collection.
https://codepen.io/karger/pen/YmVWar

**Comment by LeaVerou** [comment]
I thought we found that the bug you had was related to the `<pre>` being a single line input and not a textarea?
For single line inputs, this is a feature, not a bug!

**Comment by LeaVerou** [comment]
Testcase: https://codepen.io/pen?template=gxPjmz&editors=1100#0

**Comment by LeaVerou** [comment]
The fix seems to have resolved your testcase too.
