### ISSUE TITLE
Use of # in href

### ISSUE THREAD

**Issue by lawrencenull** [mavoweb/mavo#557]
Seems that # can't be used as a modifier for an href, example:

<a href="#[category]" property="category" mv-multiple class="side-nav tab-link">[category] </a>

It results in an infinite loop of adding # to the href. Maybe I'm missing something or maybe it is a bug. 

The use case is pulling in a list of categories and dynamically building tabs with internal linking.

**Comment by DmitrySharabin** [comment]
Hey @lawrencenull!
Please, have a look at [this pen](https://codepen.io/dsharabin/pen/BaaZOEq). If I understood you correctly, that might solve your issue. So, to my mind, that is not a bug.

**Comment by lawrencenull** [comment]
Dmitry,

Thank you that works perfect! I had tried using URL and Href. I didn't see anything like this in the documents. Seems Mavo can do a lot, it just needs more documentation.

**Comment by DmitrySharabin** [comment]
> Seems Mavo can do a lot, it just needs more documentation.

Right you are! As Lea mentioned in the [contributing guide](https://github.com/mavoweb/mavo/blob/master/CONTRIBUTING.md): “Currently the main need is documentation. There is literally a ton of functionality in Mavo that is not documented yet.“

You may find useful this regularly expandable [collection of demos](https://codepen.io/collection/XjLMqp/) made with Mavo on CodePen.

And please fill free to ask any questions you have about Mavo on [Gitter](https://gitter.im/mavoweb). It's beneficial to see the ways Mavo is being used in the wild. 😊

**Comment by lawrencenull** [comment]
It would seem that the href problem I was having has worked it's way into your solution now. Have a look at your demo. 

https://codepen.io/dsharabin/pen/BaaZOEq

**Comment by lawrencenull** [comment]
> Hey @lawrencenull!
> Please, have a look at [this pen](https://codepen.io/dsharabin/pen/BaaZOEq). If I understood you correctly, that might solve your issue. So, to my mind, that is not a bug.

It would seem that the href problem I was having has worked its way into your solution now. Have a look at your demo.

https://codepen.io/dsharabin/pen/BaaZOEq

**Comment by LeaVerou** [comment]
@lawrencenull How to reproduce the issue? I don't see an infinite loop in Dmitry's pen?
