### ISSUE TITLE
Firefox shows editing popup for dynamic <select> if <option> has the `mv-attribute="value"` attribute 

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#559]
The reduced testcase: https://codepen.io/dmitrysharabin/pen/LYENWEb

OS: macOS Catalina (10.15.1)
Browser: Firefox 71.0 (64-bit)

I also noticed that in Chrome, when I change the value, I can see the intermediate values between the previous value and the new one (e.g., if the value was 2 and I change it to 9, I notice that the final value sets not immediately).

**Comment by LeaVerou** [comment]
Oof, that's bad. Not only is it a bug because it doesn't quite make sense to show an editing popup for `<option>` but primarily because it should be read-only!

**Comment by DmitrySharabin** [comment]
Interestingly Mavo makes the first `<option>` read-only but makes the others editable.
![option in Firefox](https://user-images.githubusercontent.com/9166277/71411126-2a30af80-2659-11ea-94e0-b68844a84e58.png)

**Comment by DmitrySharabin** [comment]
Fixed with #564
