### ISSUE TITLE
mv-group doesn't work on <option>

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#565]
Testcase: https://codepen.io/dmitrysharabin/pen/xxbPVEP

This is a regression introduced by issue #564.

It also broke the Mavo site (see the corresponding `select` elements): https://mavo.io/docs/functions/ and https://mavo.io/get/ (it might be there are some other issues—I haven't checked it yet).

The issue with the Mavo version selector can be fixed rather easily, but not the problem with filters in the **Functions** section.

It might be better to revert? What do you think?

**Comment by DmitrySharabin** [comment]
The issue is being fixed by adding the `mv-attribute=none` attribute to `<option>` (see the testcase).
The problems with the site are being fixed with the PR mavo.io#68.

**Comment by LeaVerou** [comment]
> It might be better to revert? What do you think?

Yes, it looks like it might be better to revert. While we *could* add `mv-attribute="none"` to all our code (though it's a bit of a hassle), we can't possibly expect that of our users. Any such backwards incompatible change needs to come with *serious* justification, and a bugfix of a rather infrequent bug that has a workaround is not sufficient justification.

**Comment by DmitrySharabin** [comment]
Totally agree! Do I need to perform any actions to revert? Or is it on your side?
