### ISSUE TITLE
french locale doesn't seem to work

### ISSUE THREAD

**Issue by albu77** [mavoweb/mavo#568]
I'm just starting with Mavo but can't obtain french locale on Save button.
Should  I need to include something else?
![MavoBug1](https://user-images.githubusercontent.com/624802/73847891-714cbb80-4827-11ea-8396-b1a915ed7029.PNG)
![MavoBug2](https://user-images.githubusercontent.com/624802/73847906-7578d900-4827-11ea-98fd-ee9193447ba9.PNG)

**Comment by DmitrySharabin** [comment]
@albu77 Hey there! To enable the localization feature, you ought to add the `lang="fr"` attribute to the Mavo root element (or to any element which contains the mavo root element). In your case, it could look like that:
```html
...
<div mv-app="TestMavo" mv-storage="local" mv-plugins="locale-fr" lang="fr">
...
```

**Comment by DmitrySharabin** [comment]
By the way, feel free to ask any questions you have on [Gitter](https://gitter.im/mavoweb). We would love to help you.

**Comment by DmitrySharabin** [comment]
@albu77 Alain, I hope your problem is solved. Do you mind if we close the issue then?

**Comment by albu77** [comment]
Soryy, Last time I'v looked at your answer I saw closed.Perhaps I was tire. Yes you can it's working
