### ISSUE TITLE
How would I make a real-time chat app?

### ISSUE THREAD

**Issue by Glench** [mavoweb/mavo#570]
Hey, I just found Mavo and I really love it! This is a question that I'm asking in a public way so that it might help others looking to do the same thing or help the developers expand the scope of the project.

My question is can Mavo be used to create a real-time chat app? I started making one [here in this codepen](https://codepen.io/Glench/pen/zYGxBye?editors=1100) as a way to play around with Mavo but ran into some questions, which I've listed below:

- Can Mavo store and retrieve real-time data? It looks like some plugin backends can work this way, but it would be amazing if the default backends could have options to work this way.
- Can Mavo have a mix of local data and remote data? I wanted this app to be non-authenticated which means I wanted to have the user set their username string on the first page load and then persist the username in local storage *only in that user's browser*. But it's not clear to me if this would have to be another Mavo app or have custom JS or what.
- Can Mavo listen to keyboard events? I used a little JS to listen for a carriage return keyboard event on the text input and then programmatically click the button, but that feels pretty hacky. 

I ask these questions mostly because I think it would be amazing if beginners could easily write a chat app in a dozen lines of HTML. Maybe that's already possible? Please let me know and thanks for reading!

**Comment by LeaVerou** [comment]
Hi there,
Glad you like Mavo!

> Can Mavo store and retrieve real-time data? It looks like some plugin backends can work this way, but it would be amazing if the default backends could have options to work this way.

Unfortunately we cannot provide this functionality with all backends, because we are limited by what the backends can do.
However, you can use [Firebase](https://plugins.mavo.io/plugin/firebase) for real-time data and access control (though you'd need to write the access control rules yourself on Firebase) to prevent everyone from editing everyone else's messages.

> Can Mavo have a mix of local data and remote data? I wanted this app to be non-authenticated which means I wanted to have the user set their username string on the first page load and then persist the username in local storage only in that user's browser. But it's not clear to me if this would have to be another Mavo app or have custom JS or what.

Yes, currently the only way to do this would be to have another Mavo app, and refer to this data with expressions.

> Can Mavo listen to keyboard events? I used a little JS to listen for a carriage return keyboard event on the text input and then programmatically click the button, but that feels pretty hacky.

Not yet, we are still exploring the best syntax for this to enable customizing the trigger for Actions (beyond keyboard events, e.g. gestures, mouseovers, maybe even things like location changes!). Suggestions are welcome!

**Comment by Glench** [comment]
Thanks for your response!

> Yes, currently the only way to do this would be to have another Mavo app, and refer to this data with expressions.

Mavo apps can get and set data from other Mavo apps on the same page? How is this done?

**Comment by DmitrySharabin** [comment]
Hey there!
I can answer your last question if you don't mind. You can get or set data from any Mavo app via its name, like so: `appName.property`.
On the mavo web site, there is a [demo app](https://mavo.io/demos/eshop/), illustrating that feature (see its source code).

**Comment by DmitrySharabin** [comment]
> I used a little JS to listen for a carriage return keyboard event on the text input and then programmatically click the button, but that feels pretty hacky.

Please have a look at [this pen](https://codepen.io/dmitrysharabin/pen/RwPNKpb?editors=1000). It might help you achieve the same result but a bit more mavo-way. :)

**Comment by Glench** [comment]
@DmitrySharabin thanks for both tips! `appName.propertyName` worked perfectly. 

I was using a `<textarea>` in order to be able to send multi-line messages but I guess for playing around an `<input>` works :)

**Comment by Glench** [comment]
@LeaVerou I had to give up on the firebase plugin because it was so complicated to set up. I wonder if there's a way to introduce polling on non-realtime services so then this chat app would be way more straightforward to set up.

**Comment by LeaVerou** [comment]
@Glench Yes, that would definitely work! What kind of syntax do you envision for it?

**Comment by Glench** [comment]
In keeping with autosave, maybe ‘mv-autopull=“3”’?

**Comment by LeaVerou** [comment]
Oooh, I like that!

Of course, there's the problem of what to do when local edits conflict with pulled data. I wonder how the Firebase plugin solves that.
