### ISSUE TITLE
Backend ignores dynamic mv-storage attribute on (computed) properties

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#576]
I have a use case where I need to store or not to store a computed property depending on a situation. As the `mv-storage` attribute is live, I decided to use an expression that switches the `mv-storage` attribute value between `inherit` and `none`. The `mv-storage` attribute value is being updated as it should, but the backend seems not to take it into account—the value of a computed property is always being stored.

Reduced testcase: https://codepen.io/dmitrysharabin/pen/XWbowwo?editors=1000

Is this issue related to #84?

**Comment by LeaVerou** [comment]
Not related to #84, that's about allowing proper storage URLs, e.g. have some properties tored on Github whereas others are stored locally.
What you need is much simpler. Basically, I think all you need is a mutation observer for `mv-storage` on each Mavo node that updates `this.storage` accordingly. You can search the codebase for `Mavo.Observer` and see how other mutation observers work. It should be a relatively easy PR!

**Comment by DmitrySharabin** [comment]
Hope I got you right. Sent a PR.
