### ISSUE TITLE
Expressions should be restricted to MavoScript

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#591]
Accepting arbitrary JS was one of the mistakes in Mavo.

It forces us to treat expressions as a black box everywhere, which is the root of our slowness: we can't have a proper dependency graph (we only have a sort of loose probabilistic dependency graph), and we have to use proxies all over the place where rewriting would do.

It is also the cause of subtle bugs, where you *think* your expression is MavoScript, but is actually parsed as JS, with a bunch of subtle differences.

Once we restrict expressions to MavoScript we can be a lot more aggressive with optimizations because we will be able to fully understand what each expression does.

After all, there is nothing that can be done with custom JS in expressions that is not possible by just writing a custom JS function and using that, since functions are valid MavoScript syntax.

**Comment by LeaVerou** [comment]
@parulsingh23 @DmitrySharabin can one of you update the docs accordingly, to remove mentions of how people can use JS in expressions?
The table of MavoScript vs JS should stay, as that's still useful.

**Comment by parulsingh23** [comment]
Will do! :)

**Comment by unuseless** [comment]
Can you add an example of how to call a js function to https://mavo.io/docs/functions/?role=function ?  That would help a lot.  I was only to find out about this possibility by searching through github issues.

**Comment by LeaVerou** [comment]
@unuseless That is a reference of MavoScript functions, so I'm not sure it would fit there. However, it should be mentioned here, possibly under "Function calls": https://mavo.io/docs/expressions @parulsingh23 wanna give that a shot?

**Comment by LeaVerou** [comment]
I went to the docs to remove any references of being able to use regular JS in expressions, but I couldn't find any. @DmitrySharabin can you confirm?

**Comment by DmitrySharabin** [comment]
> I went to the docs to remove any references of being able to use regular JS in expressions, but I couldn't find any. @DmitrySharabin can you confirm?

I found this one in the `docs.json`. Still, I can't find it on the site: `If a Mavo expression is more advanced than MavoScript, it is automatically parsed as JavaScript, allowing experienced web developers to do more with Mavo expressions.` Does it count?

**Comment by DmitrySharabin** [comment]
And another one:
Since MavoScript does not support comments, an easy way to force JS mode is a `/* js */` comment in the start or end of the expression.

**Comment by LeaVerou** [comment]
Thanks @DmitrySharabin! Could you edit them out?

**Comment by DmitrySharabin** [comment]
> Thanks @DmitrySharabin! Could you edit them out?

Sure, Lea. With pleasure.

**Comment by DmitrySharabin** [comment]
@LeaVerou Done! Sent a PR.
