### ISSUE TITLE
Add a debugging mechanism for plugins

### ISSUE THREAD

**Issue by karger** [mavoweb/mavo#601]
The current mechanism for loading plugins inlines source code in the html, which somehow prevents the chrome dev console from tracing that code.  It would be convenient if at least for debugging it were possible to directly load plugin code as a normal source file.

**Comment by LeaVerou** [comment]
I believe the only reason we inline plugin code is that raw.githubusercontent.com doesn't use the correct MIME type. We can use jsdelivr (we already use this for uploads and it's less destructive here if jsdelivr goes away)
