### ISSUE TITLE
option[mv-value] regression

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#602]
Testcase: https://codepen.io/dmitrysharabin/pen/JjGGoYO

The same but in Mavo 0.2.0: https://codepen.io/dmitrysharabin/pen/RwrrNWe

I noticed that now we have

`<input value="..." placeholder="(...)" class="mv-editor" style="width: ...;">`

inside `option`. Previously we haven't got it.

**Comment by LeaVerou** [comment]
I believe this fixes it!

Thank you Dmitry!

Btw, in the future please use the non-transpiled Mavo URL for bug testcases, unless the bug is specific to the transpiled version. Otherwise, this adds an extra layer of abtstraction to debug through.
