### ISSUE TITLE
Let's drop IE11, Edge < 16, Chrome 41

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#606]
Now that the market share of IE combined plus old Edge is < 2%, I think it's about time to drop them in future releases. This way we can finally refactor the codebase to use async/await, and even modules one day, and it will reduce the size of our transpiled code significantly.

We can also drop Chrome 41, since [Googlebot updated last year](https://searchengineland.com/google-will-ensure-googlebot-runs-the-latest-version-of-chromium-316534).

Useful for decisions: https://caniuse.com/usage-table

**Comment by joyously** [comment]
You basically did that already since Mavo doesn't test which version to load.
https://github.com/mavoweb/mavo/issues/569#issuecomment-583111027

**Comment by LeaVerou** [comment]
@joyously Support for a given browser doesn't mean every single bundle needs to support that browser, just one. Typically, browser support is up to the app developer, and they can pick an appropriate bundle. I do like your idea about loading the transpiled bundle conditionally, it would make a cool plugin.

**Comment by karger** [comment]
It is certainly irrelevant from a research perspective, and you know better about the practical/developer consequences.  For clarification: you talk about transpiling in the original post; will you still generate a transpiled version that works in edge, or will it just not work at all?

**Comment by LeaVerou** [comment]
@karger Last time I checked, async/await can't really be transpiled (the transpiled code was monstrously huge). Also, keeping the transpiled file small to serve the needs of the many is a goal as well.

**Comment by DmitrySharabin** [comment]
I am all in favor. I believe the Mavo bundle size is crucial for most developers who might give Mavo a try, like it, but never use it in production because of its size. And if we can make it smaller, I’m in.
