### ISSUE TITLE
[GitHub] Can't upload SVG's

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#608]
In the console, I get the `422 (Unprocessable Entity)` error.

Precisely, in response, I get `content is not valid Base64`.

Testcase: https://test.mavo.io/github.html#github-upload

**Comment by LeaVerou** [comment]
Is this a regression? I think it worked in the past. There's even a [test that includes an SVG](https://test.mavo.io/github.html#github-upload)
Can you test with older versions and see if you can reproduce?

**Comment by DmitrySharabin** [comment]
We both use the same link. :)
And this test fails.
By “older versions” you mean Mavo older version? Since we haven’t updated the Github backend yet.

**Comment by LeaVerou** [comment]
> We both use the same link. :)
And this test fails.

Yes, I'm just saying, the presence of the test indicates this might have worked in the past.

> By “older versions” you mean Mavo older version?

Yup!

**Comment by DmitrySharabin** [comment]
I checked all previous versions, and every attempt failed. What if something changed on Github, so the way we transform data into `base64` doesn't work anymore?

**Comment by DmitrySharabin** [comment]
I have found the problem. Yay!
Before uploading a file, we encode it and remove the media part. SVGs have `image/svg+xml` as a media part. When we try to remove this part (and also the `;base64,` part) using the `replace` method with `RegExp()` as the first parameter, the `+` sign is interpreted as a qualifier in the corresponding regular expression but must be interpreted literally. So, the media part wasn't removed, and GitHub returns an error.

The fix is a part of PR #607.

**Comment by DmitrySharabin** [comment]
It's fixed now. Yay!
