### ISSUE TITLE
Editable image is not visible by default

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#612]
Without custom CSS, one can't see a thing.

Testcase: https://codepen.io/leaverou/pen/JjGWpRY?editors=1100

**Comment by DmitrySharabin** [comment]
Or until you add a non-empty `alt` attribute.

**Comment by LeaVerou** [comment]
I just pushed some basic styling (min-dimensions and a background emoji), feedback welcome!

![image](https://user-images.githubusercontent.com/175836/85235205-4089af00-b3e1-11ea-8150-7354fc859ec4.png)


> Weirdly, I faced this so many times but never thought it was a bug. 😅 I always thought it was my responsibility as an author to fix it.

Yeah, it's common that users blame themselves for usability issues. 🙃
