### ISSUE TITLE
Image pasting into an uploading popup doesn't work

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#622]
Working on this enhancement https://github.com/mavoweb/plugins/issues/65, I noticed that the image paste feature stopped working.

I believe, the problem is with this line: `var item = evt.clipboardData.items[0];`

It might be it's just me. Anybody else faces this issue? Here is the reduced testcase: https://codepen.io/dmitrysharabin/pen/KKVoxaQ

**Comment by LeaVerou** [comment]
I noticed it on forkgasm, but I thought it was specific to the website. Damn.
