### ISSUE TITLE
Logical operators as words (and, or, not)

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#63]
Easier for non-developers. Depends on #60

**Comment by brundonsmith** [comment]
Making a note here that `and` and `or` are functional, but `not` doesn't seem to be (which is probably why this issue hasn't been closed)

**Comment by LeaVerou** [comment]
Yup, exacxtly! It's blocked on this jsep bug: https://github.com/soney/jsep/issues/26
