### ISSUE TITLE
Mavo doesn't work on iOS

### ISSUE THREAD

**Issue by Jenna1337** [mavoweb/mavo#633]
Mavo does not appear to work properly in Safari on my iPhone 7 running iOS 12.3.1

Several pages that don't work as expected are https://mavo.io/demos/ and https://mavo.io/demos/svgpath/

It's worth noting that these pages work fine on my computer in Firefox.

**Comment by soyapark** [comment]
I also run into the same issue. Demos in the main website is not working in Safari. There are numerous erros found in web console: 
![image](https://user-images.githubusercontent.com/33616044/96347830-44b59880-1072-11eb-9483-8611a2995a24.png)


But it works on Chrome.

**Comment by LeaVerou** [comment]
Which version of Safari is that? Works fine on my Safari 13.1.1

**Comment by soyapark** [comment]
@LeaVerou ah! I see! I just updated to Safari 13 from 11, then now it is working! Thanks for checking Lea

**Comment by Jenna1337** [comment]
Yeah, it seems to work fine on iOS 14.0.1

**Comment by LeaVerou** [comment]
We should probably use the transpiled Mavo for the homepage, which works in a larger array of browsers. Could one of you file a bug in the https://github.com/mavoweb/mavo.io repo about that?

**Comment by joyously** [comment]
I suggested that in https://github.com/mavoweb/mavo/issues/491 and https://github.com/mavoweb/mavo/issues/569
