### ISSUE TITLE
If an expression contains a mistake, Mavo shows `[SyntaxError: Unexpected token ')']` as its result

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#640]
Previously Mavo showed the expression itself (as it should), but now something is broken.
Testcase: https://mavo.io/docs/expressions#providing-fallbacks-the-mv-value-attribute

**Comment by LeaVerou** [comment]
Thanks Dmitry. Could you do `git bisect` to find which commit broke it?

**Comment by DmitrySharabin** [comment]
Sure. Will do my best.

**Comment by DmitrySharabin** [comment]
Lea, I have found this one: [d6cec3abc771631bdd3ab873254d0f6c25f1ef95] Calculate dependencies from AST instead of regex, fixes #628

Thanks for introducing me to that Git feature. It's awesome! 🙇
