### ISSUE TITLE
Remove ?login after logout

### ISSUE THREAD

**Issue by leph83** [mavoweb/mavo#644]
Current state: When you are logged in and press logout, the URL still has the ?login parameter, so that immediatly after you've logged out, the Popup to login shows up again. 

Remove the **?login** parameter from the URL after logout, so that the popup doesn't show up again when you are finished with editing would be a nice feature.

**Comment by LeaVerou** [comment]
This should be very easy to fix.

Notes for anyone who wants to pick it up:
Basically, once someone logs in via a `?login` (and friends) params, use the history API to remove the param in place so that future link shares / reloads don't include it.

**Comment by raytran** [comment]
I can take this (don't have permissions to self assign)
