### ISSUE TITLE
Mavo freezes in talks page

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#648]
I had the same bug here: https://lea.verou.me/speaking/ and I fixed it by reverting to the latest stable.

@svgeesus has the same bug here: https://svgees.us/talks.html
And we have the same issue on our talks page: https://mavo.io/demos/talks/
All of these are based on the same Mavo app, with minor differences.

This is a pretty serious regression.

@DmitrySharabin @raytran @parulsingh23 Could one of you please use `git bisect` to find which commit broke these demos?

**Comment by DmitrySharabin** [comment]
Sure. I'll do it now. I have some time.

**Comment by DmitrySharabin** [comment]
@LeaVerou It seems to me, this one is the first bad commit:
[c2594f1987de1fce9d1380a7b8198731765cfd46] Edit immediately once the nearest collection item is in view, closes #581 #600

**Comment by LeaVerou** [comment]
Thanks Dmitry! Damn, that's a big change. I'll look into fixing it.

**Comment by raytran** [comment]
So I spent some time looking at this and I found that this.sneak() under primitive.js was getting caught in an infinite recursion. It looks like adding a dataOnly: true flag to the .setValue() calls fixes this. I assume this is ok (what else do you want from a primitive other than setting its data?), but I'm going to comment here before sending a PR.

https://github.com/raytran/mavo/commit/c4310dce8f8a098f9dd062b863f1d9260b2a9273

**Comment by LeaVerou** [comment]
Thank you for looking into it, and finding this workaround. However, I'm not sure we still fully understand what caused this bug. When we fix a bug without fully understanding its cause, it can come back to bite us.
*Why* was it being caught in infinite recursion? What was happening, and why did that commit change it?
It looks like your change is under the mutation overserver for a custom editor. Did something in that change cause the `<select>` that is a custom editor to constantly mutate? Perhaps the `primitive.setValue()` without the flag somehow caused that? If so, how?

**Comment by LeaVerou** [comment]
Furthermore, while `dataOnly` seems to fix this bug, I believe it would also be introducing a different bug, as it basically renders that line of code somewhat pointless. That line is setting the primitive's value based on its current value, so its only point is to apply any further constraints introduced by the updated custom editor. By marking it as `dataOnly` it means these constraints won't be reflected in the DOM.

**Comment by raytran** [comment]
More specifically, I think the bug is localized/involved with this section in primitive.js line 590:
```
// Also set DOM value if either using a popup, or there's no editor
// or the editor is not inside the element (e.g. it could be a nested editor that is now detached)
if (this.popup || !this.editor || (this.editor !== document.activeElement && !this.element.contains(this.editor))) {
	if (this.config.setValue) {
		this.config.setValue.call(this, this.element, value);
	}
	else if (!o.dataOnly) {
		_.setValue(this.element, value, {
			config: this.config,
			attribute: this.attribute,
			datatype: this.datatype,
			map: this.originalEditor || this.editor,
			node: this
		});
	}
}
```
For whatever reason when loading the talks page, the recursive call to _.setValue never meets a base case. Good note about .dataOnly; I assumed dataOnly meant "update DOM; don't update event handlers/trigger anything", which is definitely not the case.

**Comment by LeaVerou** [comment]
Nice, localizing it to a particular block is a good first step. 😊 But we need to investigate *why* does this block loop.

Note that `_.setValue()` is not a recursive call. `_` is a local variable pointing to the Primitive class itself. There's an instance `setValue()` method (that one), and a static `setValue()` method (the one being called).

**Comment by raytran** [comment]
Oh I see. I was tracing through the call stack in the debugger and assumed the _.setValue() was a recursive call since it kept appearing. Either way, that block of code is either executed a million times or is called recursively somehow.

**Comment by LeaVerou** [comment]
`setValue()` is called very frequently in general, though a million times is certainly indicative of a problem! (not sure if "a million" was a figure of speech). The static `getValue()` is also called in every expression evaluation, not just every value update.

As with every bug, I'd suggest first making a reduced test case, by removing parts of the app that don't contribute to the bug (remove something, if the bug disappeared, re-add it, proceed until there's only a bare minimum left).
The reduction itself may give you a hint about what's wrong, and even if not, it will make further debugging easier as it reduces the number of code paths that may contribute to it.

Once you have a reduction, you could comment out parts of the code that you suspect may contribute, and check when the bug stops occurring. Since we know which commit introduced it, you could focus on those parts of the code.

But understanding the root cause of a bug is essential in a long-term project. Otherwise you may end up with a fix that only coincidentally fixes it in certain cases but not others, and/or introduces regressions.

**Comment by raytran** [comment]
It was not a figure of speech; to test I put a `console.log()` in `setValue()` and left it running for a while to see if it would halt. It got to around 700,000 prints until I decided to close the tab.

So I've narrowed it down to 3 lines from [c2594f1]. If you comment out the following in main:

Lines 979-981 (from latest commit)
```
if (option.classList.contains("mv-volatile")) {
	option.remove();
}
```

Then the talks page magically loads. However, I don't fully understand the mechanism behind this/why this works.

**Comment by LeaVerou** [comment]
Oh, I think I know what's going on. Thanks for tracking this down!

`<option>` elements with a class of `mv-volatile` are temporary options added to `<select>` menus because there is no option for their current value. Once something else is selected, the option disappears from the select menu, which is what that line does. This was I believe one of the changes made in the commit that Dmitry tracked down. My guess for why the bug is happening, is that because the select is a custom editor, there is a mutation observer tracking changes to it, and that mutation observer fires and causes a loop. Most likely running that code within a sneak() call so that the observer isn't triggered by it should be sufficient to fix the bug.

**Comment by raytran** [comment]
In the middle of trying to refactor this, I wrapped that line with a sneak:

```
if (option.classList.contains("mv-volatile")) {
	o.node.sneak(() => {
		option.remove();
	});
}
```
Is this what you mean? Because this doesn't seem to work either. Still results in an infinite loop.

**Comment by LeaVerou** [comment]
Hi @raytran,
I got some complaints about this issue so I just pushed a quick fix. It's been over 3 weeks since the initial report, and I’m afraid it's too serious of a regression to leave it unfixed for longer. Sorry about that! 
@raytran & @DmitrySharabin thank you both so much for your help triaging and debugging this, this would have taken orders of magnitude more time to fix without your help!
