### ISSUE TITLE
The Mavo duration function should be able to represent more than 1 unit of time

### ISSUE THREAD

**Issue by parulsingh23** [mavoweb/mavo#651]
Currently, Mavo's duration function only returns the single largest-fitting time unit. This is especially unhelpful when the user enters a duration datetime attribute like "3 days 4 hours", where it shows as only "3 days". However, This is a case where we might have to reconsider the default orders of magnitude beyond just what the user inputs: for example, would an entry of "4 days 2 seconds" be best suited to show up as just "4 days", and "4 days 10 hours 9 minutes 2 seconds" be best suited to show up as is?
Perhaps if a unit differs in magnitude by 2 or more units (where the order of units is days, hours, minutes, seconds), we only display the units up until that 'leap' of 2 units. (so something like "4 days 10 hours 2 seconds" would be represented by "4 days 10 hours")

**Comment by karger** [comment]
what about an optional second argument that allows you to specify either a number of units (e.g., duration(x,3) would give years-days-hours or days-hours-minutes or hours-minutes-seconds) or a minimum unit (e.g., duration (x,'hours') would always report down to hours regardless of the size of x?

**Comment by LeaVerou** [comment]
Closed via #653
