### ISSUE TITLE
Remove mv-bar element when mv-bar="none" is specified

### ISSUE THREAD

**Issue by karger** [mavoweb/mavo#660]
Right now specifying mv-bar="none" results in placing an empty `<div class="mv-bar">` into the app.    Which messed up some of my CSS formatting rules that assumed it wouldn't be there at all.  Mavo should stick a display: none on the element, or perhaps remove it entirely (although that may lead to code complexity since the code would probably need to add checks for the element being present in various places.

**Comment by raytran** [comment]
It looks like the div does in fact have a display: none from this selector: 
https://github.com/mavoweb/mavo/blob/27c4c0b1b74828ac017b6eb4d528e54690776cd9/src-css/_bar.scss#L224-L227

In any case, the small fixes here https://github.com/raytran/mavo/commit/34a2430a8787b6e1f19019b449578a6549adc35b
should work to remove the element from the DOM

**Comment by LeaVerou** [comment]
@raytran PR?

**Comment by karger** [comment]
Yes, there is a selector that should be fixing this problem.   But the problem did happen.  I'm going to close the issue for now, and reopen once I've reconstructed the problem.
