### ISSUE TITLE
Reload data when mv-storage-* or mv-source-* changes

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#664]
Leftover work from #657

Currently, when `mv-storage` changes (and there is no source) or `mv-source` changes, data is fetched again. This allows apps to have dynamic storage locations. In #657 we added support for attributes that provide additional metadata to the backend. These attributes should probably also cause the same kind of reload.

Whoever takes on this issue should not duplicate the reloading code, but piggyback on the existing detection for the `mv-storage` and `mv-source` attributes, and just extend it.

**Comment by karger** [comment]
We've discuss that sometimes we might want to *store* data when 
mv-storage changes, instead of load it.  I wonder if there should be 
another attribute on the app (dynamic of course) specifying which 
storage is dominant.

**Comment by LeaVerou** [comment]
That is orthogonal. We can introduce that before or after this issue is resolved, since this piggybacks on the existing updating.

**Comment by DmitrySharabin** [comment]
I don't know why this issue hadn't been closed automatically. It definitely should. 🤔

Are we going to continue discussing David's proposal here, or can we close the issue and open another one?

**Comment by LeaVerou** [comment]
We can always open another one, but this issue is not about that.
