### ISSUE TITLE
Select as a custom editor is broken

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#680]
Testcase (showing regression): https://codepen.io/dmitrysharabin/pen/YzGdYbj
Testcase (showing the right behavior): https://codepen.io/dmitrysharabin/pen/WNGLMpr

It seems to me it's a regression. `git bisect` showed this commit (225bbd7b4539357e790812086ab6b0ad7d91f6e5) as the first bad one.

**Comment by LeaVerou** [comment]
Nice reduced testcase!
What are the differences between the two testcases? I can see that one is working and one is not, but the code seems identical.

**Comment by DmitrySharabin** [comment]
> Nice reduced testcase!

Thank you, Lea! ☺️

>What are the differences between the two testcases? I can see that one is working and one is not, but the code seems identical.

You are right; they are identical. The working one is using the _stable_ Mavo version. Just to illustrate what I'm talking about. I thought it might be useful. :)
