### ISSUE TITLE
Regression with mv-bar button order

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#681]
See failing test here: http://test.mavo.io/bar.html#authentication

@DmitrySharabin could you bisect?

**Comment by DmitrySharabin** [comment]
@LeaVerou 
This test was added to reflect changes introduced by this PR (when it's being merged): https://github.com/mavoweb/mavo/pull/584. It should fix this issue: https://github.com/mavoweb/mavo/issues/469

So, I believe it's not a regression. But a test for a known bug that is not yet fixed.

**Comment by LeaVerou** [comment]
Ah, ok, I'll mark it as a known failure then.
