### ISSUE TITLE
Regression with pressing enter or backspace inside a form input in a collection item

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#682]
See failing test: http://test.mavo.io/collections.html#collections-with-form-elements

@DmitrySharabin would you have time to bisect?

**Comment by DmitrySharabin** [comment]
Sure!

**Comment by DmitrySharabin** [comment]
@LeaVerou 

Done! Here is the first bad commit: c2594f1987de1fce9d1380a7b8198731765cfd46

I am sorry—it's a big one!
