### ISSUE TITLE
[Github] Ability to define GraphQL query via attribute

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#684]
In the past we had to shoehorn everything in a URL but since #670 we can provide storage/source/init options via attributes, it would be good to have a `query` storage attribute to provide a GraphQL query instead of the URL shoehorning.

**Comment by DmitrySharabin** [comment]
Should we get a backward-compatible code, i.e., should we support URLs like this one: `https://api.github.com/graphql#query{ viewer { login } }`?

Or we should support _only_ this kind of code:
`<E mv-storage="https://api.github.com/graphql" mv-storage-query="viewer { login }"`?

**Comment by LeaVerou** [comment]
Ideally, both

**Comment by DmitrySharabin** [comment]
Got it. Thanks.
