### ISSUE TITLE
Regressions with mv-value

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#687]
@LeaVerou
Hi Lea. As you asked me, I bisected to find commits that caused the regressions with `mv-value`. Please have a look.

| Testsuite | First Bad Commit |
| ----- | ----- |
| [Collections](https://test.mavo.io/value.html#collections) | 32d6e096ac415011422a86ef5578f8c3e5d2412e |
| [Property edited with dynamic select](https://test.mavo.io/value.html#property-edited-with-dynamic-select) | c2594f1987de1fce9d1380a7b8198731765cfd46 |

**Comment by LeaVerou** [comment]
Thank you Dmitry!
Damn, I was hoping it was the same commit for all of these regressions. Oh well. I'll get right to it.

**Comment by DmitrySharabin** [comment]
> Damn, I was hoping it was the same commit for all of these regressions.

Yes, me too. Unfortunately, our hope failed.
