### ISSUE TITLE
Remove ability to edit properties by nesting a form element

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#696]
This is inconsistent behavior, since certain types of descendants are not treated as regular parts of the Mavo tree, but as special parameters. If people want to use a custom editor, they should link to it via `mv-edit`, and `mv-edit` should be made live, to allow for linking to elements based on expressions, which would allow linking to a different editor for each collection item, which was a primary use case for this syntax. Also, in the future we should support `:scope` in selectors (or `&`), to fetch editors relative to the current element.

I believe that syntax is not used at all in the wild, so it should be relatively pain-free to remove. Any objections @DmitrySharabin @karger?

**Comment by DmitrySharabin** [comment]
I personally have never used a nested form element as a custom editor. Moreover, when I teach someone Mavo and tell about custom editors, the only way I suggest using this feature is via `mv-edit`. 

+1 for making this attribute live.

So, as you can see, no objections. :)

**Comment by DmitrySharabin** [comment]
>... which would allow linking to a different editor for each collection item, which was a primary use case for this syntax.

To be honest, I’ve never thought of this use case. Now I start thinking that I build elementary Mavo apps. 😅

**Comment by karger** [comment]
I agree with this change.
