### ISSUE TITLE
mavo.io/get is broken

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#698]
This is not in the mavo.io repo because I suspect it's a Mavo regression.

Visit https://mavo.io/get/
Select that you want a different version.
Note that the URL displayed doesn't change until you actually select something from the `<select>`.
Same with the radios, clicking them doesn't seem to change the appropriate expressions until you make a few more clicks.

**Comment by DmitrySharabin** [comment]
Git bisect showed this commit as the first bad one: 6c49c06326d4cd48082cfdd33589b5beca8372a9

**Comment by LeaVerou** [comment]
Dang, I suspect it would have been that. 😢
