### ISSUE TITLE
Handling persisted vs un-persisted state

### ISSUE THREAD

**Issue by tscanlin** [mavoweb/mavo#704]
I'd like to add a search input for a list of items, however I don't really want the search term persisted. What is the best way to add temporary, un-persisted state or properties in mavo? If you still want most other properties and data persisted. I checked here but didn't see anything for this in particular: https://github.com/mavoweb/mavo/issues/161

Thanks!

**Comment by DmitrySharabin** [comment]
If I understand you correctly, I would suggest adding `mv-storage="none"` to the property you don't want to be persistent.

See https://mavo.io/docs/storage#disabling-storage

**Comment by LeaVerou** [comment]
As Dmitry said, the fastest way is `mv-storage="none"` on the property itself.

Another common pattern, if you want to persist the search locally in the browser, is to include it in a separate Mavo app with `mv-storage="local"`, then refer to it from your main app via `otherAppId.searchProperty`.

**Comment by tscanlin** [comment]
Oh, I didn’t realize you could do that. Both are great options, thanks so much!
