### ISSUE TITLE
Mavo login to Github is broken

### ISSUE THREAD

**Issue by amyxzhang** [mavoweb/mavo#713]
![image](https://user-images.githubusercontent.com/1301962/113363452-bbcfa800-9305-11eb-997f-578e3d5d7796.png)
Clicking on the "Log in" button does nothing. I was able to get around this problem by manually copying the access_token in the error, going into my local storage, and adding it as a value for the key "mavo:githubtoken".

**Comment by LeaVerou** [comment]
@DmitrySharabin could you investigate please? You're the last one that made changes to `auth.mavo.io`.

@amyxzhang you may want to obscure your access token in the screenshot, as it's sensitive information.

**Comment by LeaVerou** [comment]
Actually, I investigated and pushed a fix. Apparently the primary problem was that access tokens now have a new format which includes arbitrary letters and underscores, not just hex characters, so the regex reading the access token wasn't picking it up.
The stuff about undefined variable was just a notice, not the reason login broke.

I will go ahead and close this now, @amyxzhang please let us know if you encounter any similar issues in the future!

**Comment by amyxzhang** [comment]
Thanks, I'm going to remove my screenshot.
