### ISSUE TITLE
Collections should be represented in the DOM

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#72]
Attribute TBD, most likely `data-list`

Reasons:
- `data-multiple` can always be emulated by wrapping the element with a wrapper div (if one does not exist) and putting `data-list` on that div. Mavo can do that automatically.
- Drag and Drop becomes immensely easier to implement when there is a container
- No need for a dummy marker element any more.
- Makes it possible to mark up collections where the repeated part is multiple elements (e.g. definition lists)

**Comment by LeaVerou** [comment]
To add to this, we observed that several participants in our user study were confused about the fact that the collection itself is invisible in the HTML, and we only see its items.

Also, this would make it IMMENSELY easier to specify attributes on the collection itself, instead of having to use flimsy heuristics or naming conventions.

After 3 years of `mv-multiple` I am VERY MUCH in favor of this. We just need to come up with a good syntax that works well with `mv-multiple`.

**Comment by LeaVerou** [comment]
Thinking about what mistakes I've made in the design of Mavo, this is one of the things that crop up among the top 5.

Collections should be represented in the DOM and attributes about the collection itself should be on that element instead of `mv-multiple-*` attributes on the item or weird heuristics. There could be a shortcut for container-less collections so we can keep the current syntax too and be mostly backwards compatible (and because containers are not legal in certain cases), but it should not be the norm and can not support full functionality.
 
Using attributes on the collection element would be the **only** way to specify attributes on the collection itself. Anything on the item, should set attributes on the item.

So, we should support both of these (element types are examples):

```html
<dl mv-collection property="item">
	<dt property="foo"></dt>
	<dd property="bar"></dd>
</dl>`
```

Old syntax:
```html
<ul>
	<li mv-multiple property="item">
		<div property="foo"></div>
		<div property="bar"></div>
	</li>
</ul>
```

What happens when both are used?

```html
<ul mv-collection property="item">
	<li mv-multiple property="item2">
		<div property="foo"></div>
		<div property="bar"></div>
	</li>
</ul>
```

Are they two nested collections or the same one?

**Comment by LeaVerou** [comment]
RESOLVED in meeting: 
- Add `mv-collection` element to represent the collection
- Undecided what should happen with nested `mv-collection` and `mv-multiple` with different (or same) names

**Comment by LeaVerou** [comment]
After thinking about this a bit more, a few more thoughts and things to decide.

## 1. Both the collection and the item need to be DOM elements

If we want every Mavo node to be represented in the DOM, we can't have collection items that are comprised of multiple elements, except as a macro to be expanded. But ultimately, both the collection and the item need to be represented in the DOM. This means that things like:

```html
<dl mv-collection property="item">
	<dt property="foo"></dt>
	<dd property="bar"></dd>
</dl>`
```

would be possible, but would be converted to:

```html
<dl mv-collection property="item">
	<div mv-multiple property="item">
		<dt property="foo"></dt>
		<dd property="bar"></dd>
	</div>
</dl>`
```

(which is actually valid HTML)

Similarly, things like:

```html
<span mv-multiple property="tag"></span>
```

Would be converted to:

```html
<div mv-collection="tag">
	<span mv-multiple property="tag"></span>
</div>
```

We can apply `display: contents` to these generated elements, to minimize effect in the CSS, though some effect will be present, in selectors at the very least (and overrides).

If you think the latter is too limiting and too backwards incompatible, we could instead have "light" collections, eg without drag and drop (it was a pile of hacks to get Dragula to work without a dedicated container and would love to remove that logic at some point).

## 2. What happens when both are present plus additional content?

Consider something like this:

```html
<div mv-collection="foo">
	<header></header>
	<div mv-multiple="foo"></div>
	<footer></footer>
</div>
```

1. Is the item the mv-multiple div and the header and footer are not repeated?
2. Is the whole thing the item and needs to be wrapped in a div, per above?

If 2, then how do we represent `{"foo": [{foo}]}` schemas? So I'm leaning towards 1. But then what happens if we have another mv-multiple, like so:

```html
<div mv-collection="foo">
	<header></header>
	<div mv-multiple="foo"></div>
	<div mv-multiple="bar"></div>
	<footer></footer>
</div>
```

What's the collection then? What needs wrapping, if any?

## 3. Other tricky cases to resolve

What happens when we have exactly one child of mv-collection, but with a different name?

```html
<div mv-collection="foo">
	<div mv-multiple="bar"></div>
</div>
```

Do we wrap the contents with `<div mv-multiple="foo">` as we'd do with any other contents? I suppose that makes the most sense and allows the most flexibility, but not sure. Related, how do we handle this?

```html
<div mv-collection="foo">
	<div mv-multiple></div>
</div>
```

**How do we handle lack of property names?** Right now we just default to `collection`, so this would essentially be the same as the previous example. But now that each collection requires 2 elements, perhaps we should allow authors to just declare the property name once and default to that for the other element.

Also, what about this?

```html
<div mv-collection="foo">
	<div property="foo"></div>
</div>
```

Is the inner div the item, or a property of the item? Should the contents be wrapped or not?

**How do we handle duplicate property names?** Right now they create an implicit collection, i.e. they are saved as an array, but the items are fixed, and cannot be deleted, created, or rearranged. But how do we handle this?

```html
<div mv-collection="foo">
	<div property="foo"></div>
	<div property="foo"></div>
</div>
```

And what about this?

```html
<div mv-collection="foo">
	<div property="foo" mv-multiple></div>
	<div property="foo"></div>
</div>
```

**Comment by karger** [comment]
It seems to me that if we have mv-collection, olus a rule that there has to be an element representing the itme, then we don't need mv-multiple since the implication is "whatever's inside is multiple".  The presence of mv-multiple could be used as an indication this is an "old" mavo that needs the old version of the code.  Or you could try to continue to support it, but without providing the newer functionality associated with mv-collection.

Our big original concern with the collection node was that sometimes having it would violate html semantics.  For example, if I want my collection to be represented in two rows of a table, then I can't write valid html that wraps that pair of rows in one element.  And certainly after mavo renders the collection, so you have many rows, there's no valid html that wraps each pair of them inside an html element.  I can use display:contents to fix the *presentation*, but the semantics will still be wrong.  But perhaps we should think of this as the "weird" case to be handled with some special syntax---maybe attributes on the items that are supposed to be bundled into a single item (we could repurpose mv-multiple for this for example---you put mv-multiple on all the elements that are supposed to be bundled as a single item)?   Above you mentioned the hassle of providing drag and drop for non-encapsulated collection items---but aren't you still going to have to do that for a pair of trs?

**Comment by LeaVerou** [comment]
First off, the `<tr>` example is incorrect, since there is a perfectly valid wrapper: `<tbody>`. Yes, you can have as many as you want.
But going beyond that particular example: If we represent the collection in the DOM but not the item, we basically run into similar problems. All nodes need to be represented in the DOM, so both collections and items. I think it's ok for this to just apply to the rendered Mavo, and have shortcuts for generating it, but obviously I haven't ran a user study on that.

**Comment by karger** [comment]
It hadn't occurred to me, but I've checked that multiple tbody tags are permitted in a table, so indeed my example has an easy fix.  So lets go back to the more basic example of a pair of li tags.  I don't think it's valid to put any element around the pair.  Let me elaborate on this example a bit.  Suppose author perversely wants to create a ul that contains some initial, fixed items, then a collection of items each corresponding to a sequential pair of li tags.   

Considering rendered html first, the only way to be semantically valid is with a sequence of li tags, so it seems you'll have to support dragging groups of tags, unless you want to violate html semantics in the rendered content.   

But turning to authoring, how should this be done? Does author use the proposed header tag around the static elements?  Or should an attribute be used hear (mv-static?) to say this isn't replicated even though it's inside a collection, to preserve semantic validity?   Does author put a div around the pair of li tags to show they want the whole thing as one collection item?  Or do they use an attribute on each item for that purpose (mv-piece?  I'd suggest mv-group or mv-multiple but they're taken), which leads to mavo generating the wrapping div so at least the source html can be valid even though rendered is not)?  As you point out, generating wrappers not-in-source can throw off selectors and seems like a bad surprise to spring on authors.

**Comment by LeaVerou** [comment]
A `<template>` element would solve a lot of these issues, and is valid anywhere. It's also semantically more appropriate.

One issue is that while conceptually collections "contain" their items, a `<template>` would be adjacent to the items it generates.

**Comment by LeaVerou** [comment]
Serializing the discussion with @karger yesterday:

Collections would be specified via `<template mv-collection property="foo">` (or `<template mv-collection="foo">`).
Inside the template, we need a subtree with a single root to be the collection item. If there are multiple elements, we wrap them. Similarly, if the root is an element with a different property name, we wrap. If the root has no property name, we add it.

I'm not sure if new items should come before or after the `<template>` in the DOM.
If they come after, authors can use CSS sibling selectors to target them, but it affects matching of `:first-child` etc. 

Also, if the element representing collections does not contain the collection items, how much does that mess things like inherited attributes etc?

**Comment by LeaVerou** [comment]
The more I think about it, the more I dislike the idea of the collection node being adjacent to its items instead of containing them. Not only is it easier to understand when the Mavo tree is a subset of the DOM tree, but also it allows us to take advantage of things like inheritance etc, which Just Work™.

Conceptually, we have three distinct element types here:
- The collection itself
- The collection *template*
- The collection *items*

Part of the confusion of the current syntax is that while it's fast to type, it blends parts of all three in the same DOM node.
Crazy thought, but what if we represent all three separately, with appropriate shortcuts to make this less painful?

So in the fully expanded case it would be:

```html
<div mv-collection property="row">
	<template>
		<div mv-item property="row">
			...
		</div>
	</template>
</div>
```

Bikeshedding: `mv-collection` vs `mv-list`

And some rules about how to reach that expanded form from incomplete, ambiguous forms:
- Legacy `mv-multiple` elements would be wrapped with a `<template>`, and then with a `<div mv-collection>` (or `<g>` in SVG). Same with lone `mv-item` elements.
- `mv-collection` elements can contain other elements in addition to the `<template>`. Any expressions using their property name will resolve to all items.
- If there are multiple `<template>` elements, the first one is used. If there are none, the entire contents are wrapped in a `<template>`.
- The same resolution as above applies for the `<template>` itself: If there are multiple elements inside it, we wrap them. Similarly, if the root is an element with a different property name, we wrap. If the root has no property name, we add it.

Some of the cases outlined in https://github.com/mavoweb/mavo/issues/72#issuecomment-650612939 still need to be decided on, regardless of syntax, but let's first decide on what syntax makes the most sense, and we can handle corner cases later.

**Comment by karger** [comment]
Tangential thought: template is being used here to specify the schema for data object that hasn't been created yet.  So from that perspective it is a lot like a class definition in a standard programming language.   Might there be uses for that other than collections?  For example, this might interact nicely with mv-like, if I want to "define" the class in one place and use it in several.

**Comment by karger** [comment]
Question: how would someone specify a collection for which they also want to specify two initial items in the collection?  Would these be given in two html nodes outside the template?  Could the html be different from that in the template or would those two elements be rendered using the template regardless of the html used to specify them?

**Comment by karger** [comment]
It's unclear why you need to specify mv-item inside the template; isn't that implied by the existence of the template tag?

**Comment by LeaVerou** [comment]
> Tangential thought: template is being used here to specify the schema for a data object that hasn't been created yet. So from that perspective it is a lot like a class definition in a standard programming language. Might there be uses for that other than collections? For example, this might interact nicely with mv-like, if I want to "define" the class in one place and use it in several.

Absolutely, for example `mv-if`. In fact, in other frameworks, they *only* allow conditionals on `<template>`.

> Question: how would someone specify a collection for which they also want to specify two initial items in the collection? Would these be given in two html nodes outside the template? Could the html be different from that in the template or would those two elements be rendered using the template regardless of the html used to specify them?

They really shouldn't be duplicating HTML to specify the data for two initial items :(

> It's unclear why you need to specify mv-item inside the template; isn't that implied by the existence of the template tag?

The root element of the template would get `mv-item` by default, so I don't imagine people would need to explicitly specify it too frequently.

**Comment by LeaVerou** [comment]
We discussed this in our breakout yesterday with @karger.

One problem with the latest proposed syntax is that it could make certain use cases impossible, at least with valid HTML. It is unclear if there are any use cases that are impossible, even if invalid (generated) HTML is acceptable.

Consider this common pattern where a `<select>` menu is a primitive property, but its options are generated by a dynamic collection:

```html
<select property="fooFilter">
	<option mv-value="unique(foo)" mv-multiple>
</select>
```

With the new syntax, this would need some kind of container between `<option>` and `<select>`. `<div>`s work fine, but are invalid. Similarly, custom elements are also invalid here. `<optgroup label>` works and is valid, but affects rendering.

How many such cases are there? It would be interesting to make a list and see if this is workable.

Another thing we discussed was the possibility of the collection element being optional in cases where no editing is required, since it seems that a lot of the reasons to have a DOM element for the collection are editing-related.

**Comment by karger** [comment]
Per your last comment, I think a wrapping collection element is important specifically because of editing functionality.   So it can be omitted for collections that cannot be edited.  This would include collection defined implicitly by a repeated property, and for collections that are implicitly defined by mv-value  expressions that return collections.  Note that in both of these cases, the existence of the collection is clear so it seems to me there is no need for an mv-multiple declaration at all.  This would mean that <div property="[expr]"> would *automatically* replicate to multiple divs if expr evaluates to a collection.  I think this could actually help with debugging.  

On the flip side, once mv-collection is specified, I don't think mv-multiple is needed and it should be ignored if present.  So I don't see any benefit for mv-multiple in any context.

Just to explore, here's another potential way to interpret multiple children inside an mv-collection element: each child without a property tag defines a member of the collection, its structure being whatever structure is defined by its html.  So, you might end up with a heterogeneous collection.   On the other hand, if the child does have a property name, it becomes a *property* of the collection rather than a member---just as in js, a collection can also have properties that are not members.   If  none of the children is a template, then there is no defined template which means there is no add affordance in the collection editing UI.   Editing items, deletion, and reordering would still be possible (although, this would yield another situation where the edited data would "disagree" with the html content, which will an author might find surprising).   Similarly, if you invoke add(collection), it will add a null element, since without a template there's no specification of the structure of the added item.   If one (or the only one) of the children is a template tag, that becomes the template for new items added to the collection.  If you've got *multiple* template children, you've just defined a heterogeneous collection and we generalize the item bar to let you choose which "type" you want to add to the collection---perhaps leveraging some attribute to let you specify a name for each of the addable types.

**Comment by LeaVerou** [comment]
@karger Then the collection items are not represented as a DOM element, which is just as confusing as not having the collection represented in the DOM.

Did you look at https://github.com/mavoweb/mavo/issues/72#issuecomment-650612939 ? A lot of the cases described there are still tricky. 

> On the other hand, if the child does have a property name, it becomes a property of the collection rather than a member---just as in js, a collection can also have properties that are not members. 

That cannot be serialized as JSON, so we really shouldn't do it. Though I do quite like the merging of groups and collections that you're doing here. 

Heterogeneous collections are a whole different beast. E.g. how do you render existing data, which template do you use? And the UI is not that simple. You need to be able to toggle an existing item between types, and also the author needs to be able to switch types with custom UI. I suppose it could be a special `$type` property that you can optionally include. Anyway, all are solvable problems, just need some more thinking, and it may be worth it to decide what's the MVP here, as this issue is blocking a bunch of other stuff.

**Comment by karger** [comment]
> Once you have Mavo nodes that don't exist in the DOM, you run into a lot of tricky issues and confusion.

The tricky issues and confusion that I can think of are primarily associated with editing the collection, e.g. what is the container for drag and drop functionality, or what are the access control rules for the collection.   I can't think of any issues that arise for collections that are the result of evaluating an expr and thus are not editable.   Would permitting *dynamic* mv-multiples without a collection create any tricky issues?  This would offer a way to address the select menu problem above: a select menu could be defined as mv-multiple without a container.   If you do want the collection to be editable via mv-action, a (clunky) solution is to define the collection somewhere else (with an enclosing tag) and then include it by mv-value into the collection.

**Comment by LeaVerou** [comment]
Summary of breakout with @karger yesterday:

- An `mv-collection` (or `mv-list`?) attribute will be placed on the element that is the collection.
- The first `<template>` that is a direct child will contain the item template
- An `mv-item` (or `mv-multiple`) attribute will indicate the item
- The name should be declared with the collection. `mv-item` would not have a value.

So for example, here is a collection with the new syntax:

```html
<ul mv-collection="articles">
	<template>
		<li mv-item>
			...
		</li>
	<template>
</ul>
```

To address the error cases from https://github.com/mavoweb/mavo/issues/72#issuecomment-650612939 

- If there is no template in the collection:
	- If there's a child with `mv-item`, that will be wrapped with a `<template>`
	- Otherwise, the entire collection contents will be wrapped with a `<template>`
- If there is no `mv-item` element inside the template, the entire contents of the template are wrapped with a suitable element with `mv-item` on it.
- If the `mv-item` element has a `property` with a different name than the collection, then ...? (@karger, do you remember?)
- Additional heuristics/conveniences could be introduced in the future as needed

**Comment by LeaVerou** [comment]
For easier migration with today's syntax, we should also allow `mv-item` by itself. If it's the only child of its parent, and the parent doesn't have a `property` attribute, then `mv-collection` gets added to the parent, otherwise a `<div>` is generated.
