### ISSUE TITLE
Extract authentication and storage to standalone packages

### ISSUE THREAD

**Issue by fregante** [mavoweb/mavo#723]
I found Mavo to be pretty unique in its ability to get from the browser into a repository without any servers — any user-managed servers, that is.

What do you think about possibly turning the authentication and storage part into its own module? Something like:

```js
const mauth = new Mauth('https://github.com/my-user/my-storage');

await mauth.login(); // Prompts user

await mauth.store('content.json', {name: 'Rico'})
```

Implementing authentication and creating a standalone GitHub App for this is a high barrier to entry. Or maybe this could just be a blog post ;)

**Comment by LeaVerou** [comment]
Indeed, there are vague thoughts about abstracting the auth/read/storage part into its own separate JS library!
Unfortunately, there is currently no bandwidth to do it until September or so.

**Comment by karger** [comment]
In fact there is some movement here

**Comment by fregante** [comment]
I actually closed it because I wouldn't need it anymore, but I'm glad it's available now

**Comment by LeaVerou** [comment]
Closing since this is being worked on. Any feedback and improvements should be directed to https://github.com/madatajs/madata/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
