### ISSUE TITLE
Option to automatically serialize/parse collection of primitives as single string

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#729]
From discussion with @karger. 

Perhaps something like `mv-storage-separator=","` on the collection or something.

This would allow us to store collections with simple nesting (containing collections of primitives) in limited storage backends such as Google Sheets, and would allow us to support a greater number of existing Sheets.

**Comment by DmitrySharabin** [comment]
I really like this idea. Once, working on the GSheets plugin, I was going to use this method to store a collection of primitives in one cell. But I had to drop that idea since I couldn’t choose a separator to use and didn't dawn upon providing a separate option for it.

**Comment by DmitrySharabin** [comment]
This issue is the ancestor of #754. :)

@leaverou Shall we close this one?

**Comment by LeaVerou** [comment]
Dang, I thought there was an issue on this but couldn't find it anywhere. Sure!
