### ISSUE TITLE
Invalid selector on mavo.js 

### ISSUE THREAD

**Issue by tetsuo808** [mavoweb/mavo#736]
I've noticed the main Mavo file (get.mavo.io/mavo.js) isn't loading anymore over the past few days. At first I thought it was something to do with me, but the same error reported below is also the reason why the Demo page (https://mavo.io/demos) isn't loading either. 

My browser console indicates the following errors from both the official website Demo page (1) and my own app (2). They appear to be related to the same issue:

1. `Failed to execute 'matches' on 'Element': '[property]:not([typeof], [mv-group])' is not a valid selector.`
2. `Failed to execute 'querySelectorAll' on 'Element': '[property]:not([typeof], [mv-group])' is not a valid selector.`

I assume it's a known issue at this point, but thought I'd flag it anwyay :)

**Comment by LeaVerou** [comment]
Which browser/version are you using?

**Comment by tetsuo808** [comment]
> Which browser/version are you using?

Tested on:

Firefox 78.6.0esr (OSX)
Firefox 82.1.1 (Android)
Chrome 87.0.4280.141 (OSX)

**Comment by LeaVerou** [comment]
Ah yeah, these selectors are not supported in Chrome 87 [link](https://caniuse.com/css-not-sel-list). I may have been a bit quick to use them 😂 However, it's going to be a fair while before the next release, as it would have some slight breaking changes, so by then these versions will be even less used (they're already at < 3%).

For now, I would recommend using the latest stable version and not the development version that could break any moment.

@DmitrySharabin We should probably also use the latest stable on the website, and have it as a default in mavo.io/get, what do you think?

**Comment by DmitrySharabin** [comment]
> We should probably also use the latest stable on the website, and have it as a default in mavo.io/get, what do you think?

Yes, it totally makes sense. At least until we introduce flags in Mavo. 😉 Should I make these changes?

**Comment by LeaVerou** [comment]
> > We should probably also use the latest stable on the website, and have it as a default in mavo.io/get, what do you think?
> 
> Yes, it totally makes sense. At least until we introduce flags in Mavo. 😉 Should I make these changes?

Yes please. Thank you!

**Comment by tetsuo808** [comment]
> For now, I would recommend using the latest stable version and not the development version that could break any moment.

A compounding problem I'm seeing is the [Mavo builder](https://mavo.io/get/) doesn't work on even the latest build of Firefox (I've just updated, I can't upgrade Chrome yet because it requires an OS update too), since it uses Mavo JS to generate the HTML tags on the page. Unless there is another way to get the stable release URI?

Tested on Firefox 78.1.1:

`Uncaught (in promise) DOMException: Element.querySelectorAll: '[property]:not([typeof], [mv-group])' is not a valid selector`

**Comment by LeaVerou** [comment]
Oh that's bad. I'll investigate, thank you.

**Comment by LeaVerou** [comment]
Wait, Firefox 78 is quite an old version, not the latest one. Is it due to it being ESR? How far behind are these versions?

**Comment by LeaVerou** [comment]
The stable release URI is:

```
https://get.mavo.io/stable/mavo.js
https://get.mavo.io/stable/mavo.css
```

(adjust accordingly for transpiled etc)

**Comment by tetsuo808** [comment]
> Wait, Firefox 78 is quite an old version, not the latest one. Is it due to it being ESR? How far behind are these versions?

Eeek – you're correct 👍. Apparently even the latest ESR is currently at version 78. I had no idea it was that far behind. Google Chrome will be stuck on a similar issue, I'll guess.

I'm going to need to do an OS upgrade – I assume that will crush the problem. This issue is in fact not strictly Mavo-related then, but I hope informative anyway 😄

**Comment by DmitrySharabin** [comment]
These 👆🏻 PRs should fix the issue.

@LeaVerou We already had the stable version of Mavo as default in mavo.io/get. So, nothing to change there. 🥳
