### ISSUE TITLE
Implicit booleans are no longer editable

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#737]
Tests: https://test.mavo.io/property.html?#booleans

It looks like this regression was introduced by this commit: https://github.com/mavoweb/mavo/commit/9ef5813e755d1e00c06b29051e7362ee57f0b506.

**Comment by karger** [comment]
what exactly makes this an implicit boolean?  there seems to be no way at all to infer the datatype; shouldn't it be treated as a string?

**Comment by LeaVerou** [comment]
> what exactly makes this an implicit boolean? there seems to be no way at all to infer the datatype; shouldn't it be treated as a string?

Loading data that is a boolean on a property with no explicit datatype.

**Comment by karger** [comment]
It doesn't seem natural to me for the UI to change when the type of the loaded data changes; Mavo seems to point the other way, where things you say in defining the UI determine the format of the data

**Comment by LeaVerou** [comment]
If you *have* actually said things in the UI, they take precedence. If you haven't specified anything, I don't see the harm in trying to use the data intelligently. Note that spreadsheets also detect types from values.

**Comment by DmitrySharabin** [comment]
After working a bit more on this issue, I understood why we face it.

In Mavo `v0.2.3-`, the `editType` property each primitive has is a _getter_. In Mavo `v0.2.4+`, `editType` is evaluated _lazily_ (on primitive construction) and is updated _only_ if the `mv-edit-type` attribute is updated (e.g., via an expression).

However, a primitive edit type depends on its properties, i.e., whether the primitive stores its value in an attribute or not. If so, we should update the primitive edit type every time we update the primitive (main) properties (e.g., the `attribute` property). And inferring datatype is one of such cases.

So, I propose this change to the [`datatype()`](https://github.com/mavoweb/mavo/blob/d68e709d1c2817704c8cab45046ac501f71f8937/src/primitive.js#L1245) function. I already tested it.

```diff
datatype: function (value) {
	if (value !== this._datatype) {
		if (value == "boolean" && !this.attribute) {
			this.attribute = Mavo.Elements.defaultConfig.boolean.attribute;
+			this.updateEditType();
		}

		$.toggleAttribute(this.element, "datatype", value, value && value !== "string");
	}
}
```

What do you think, @LeaVerou?
