### ISSUE TITLE
[0.3.0] An issue with nested collections with `mv-value`

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#750]
Found by @karger.
Testcase: https://codepen.io/dmitrysharabin/pen/NWjppKJ

I wonder whether it makes sense while migrating to `mv-list`, we move `mv-value` (with its value) from an element with `mv-multiple` to the one with `mv-list` (aka collection container)? 🤔

In the stable version of Mavo everything works like a charm: https://codepen.io/dmitrysharabin/pen/MWmpmRq

**Comment by LeaVerou** [comment]
> I wonder whether it makes sense while migrating to `mv-list`, we move `mv-value` (with its value) from an element with `mv-multiple` to the one with `mv-list` (aka collection container)? 🤔

We do that already… https://github.com/mavoweb/mavo/blob/master/src/mavo.js#L1086

**Comment by DmitrySharabin** [comment]
Oh! That's cool. Take my words back. :)

**Comment by karger** [comment]
what happens if there is an mv-value on the mv-list-item?

**Comment by LeaVerou** [comment]
As I've previously mentioned, I cannot think of any use cases for that, but the current behavior should be that the mv-value data is rendered on the item

**Comment by DmitrySharabin** [comment]
From our discussion on Facebook.
Lea wrote: “I think in most cases `mv-value` on list item is nonsensical, but I suppose we could render the `mv-list` and then evaluate the expression and render it on the item.”

And now it works exactly as Lea mentioned.
