### ISSUE TITLE
Consistent function naming: let's go with underscores

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#793]
Currently we have very few MS functions with 2 word names (thanks @DmitrySharabin for hunting them down):

* `groupby()`
* `tolast()`
* `fromlast()`

Given that Mavo is generally case insensitive, I don't think concatenating names makes for very readable code. Instead, we should use underscores to separate words, which is guaranteed to be readable with any casing.

A solid plan for this would be:

* Any new multi-word functions use underscores (e.g. [`readable_datetime()`](https://github.com/mavoweb/mavo/commit/a8c5e827c969349bc7cb03ec7c0e9e86e2fdefe2))
* We rename the three functions above to `group_by()`, `to_last()`, `from_last()`

We add the current names as aliases, which call `Mavo.warn()` to print out something like: 

```
groupby() is deprecated and will be removed in the next version of Mavo. Please use group_by() instead.
```

and then call the new function name.

We need to also make sure we're not calling the old names in any of our own code or plugins.

**Comment by amm98d** [comment]
> > Is this up-for-grabs? Would love to contribute on this :)
> 
> Sure, thanks! One caveat is that while most of these are defined in `src/functions.js`, the `groupby()` function is defined in `src/mavoscript.js` because it's also an operator.

Alright, will send PR soon !

**Comment by jvitor211** [comment]
Hi I would like to contribute, are you still open for help?

**Comment by LeaVerou** [comment]
> Hi I would like to contribute, are you still open for help?

Sure!
How did you find this project, if I may ask?

**Comment by jvitor211** [comment]
a few days ago I was on the csail MIT website and found this research group
and commented with the professor, Mr. David Karger.
And I talked about the project asking if I could be part of it in any way
and contribute

https://prnt.sc/1y67p4j
https://prnt.sc/1y67gjx

Em ter., 2 de nov. de 2021 às 09:58, Lea Verou ***@***.***>
escreveu:

**Comment by NEERAJthinker** [comment]
I would like to contribute on this. This is going to be my first contribution, therefore can you please tell me where to start.

**Comment by norbitrial** [comment]
> Currently we have very few MS functions with 2 word names (thanks @DmitrySharabin for hunting them down):
> 
> * `groupby()`
> * `tolast()`
> * `fromlast()`
>
> Given that Mavo is generally case insensitive, I don't think concatenating names makes for very readable code. Instead, we should use underscores to separate words, which is guaranteed to be readable with any casing.

👋 Hey @LeaVerou! Not sure if help is still needed here but I've opened a PR as above. 🚀 

It tenned to add deprecation warnings for the old function calls meanwhile introducing the underscore version of them. Function calls are tested on my local, everything seems to be working exact the same way as before. There are extra warnings on the console for old function calls for the following cases:
- `groupby()` function call,
- `fromlast()` and `tofirst()` calls.

I assume these are the functions which are planned to renamed.

Let me know if you have any suggestions about the PR or anything else need to be added. 🙇 👍

**Comment by FirdausJaimi** [comment]
@LeaVerou
I would like to contribute on this. Assign me.

**Comment by DmitrySharabin** [comment]
> I couldn't really find `tolast()`.

Hey @norbitrial,

You are absolutely right—there is no such function. The correct name is `tofirst()`, and you've already fixed it. Thank you!

If you are still interested in contributing (which would be awesome), and @LeaVerou doesn't mind we can work through your PR together.

**Comment by DmitrySharabin** [comment]
> I am still happy to help here. Let me know what's required from my side there in the PR which could be found here: #821 🚀

That's great! Thanks. 😊

**Comment by Gaurav10997** [comment]
can i contribute to this project

**Comment by Ironman0505** [comment]
@LeaVerou Can I contribute to this please.. I would love to do it :).

**Comment by akashleo** [comment]
Hey would love to contribute, please assign this issue to me

**Comment by adityadalwadi1510** [comment]
Hey! I am beginner. Would love to contribute my first contribution in open source. Please assign this issue to me.

**Comment by Sooraj2003** [comment]
hey 
I'm unable to find groupby function in this repo.

**Comment by Sanketpatil27** [comment]
Hey, how can I contribute to this?
