### ISSUE TITLE
Data URIs and remote backends (simple JSON-files) are broken in the minified versions of Mavo

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#794]
Testcase: https://codepen.io/dmitrysharabin/pen/vYJqLwZ

When `mavo.min.js` is used they are being broken silently (no errors in the console). However, `mavo.es5.min.js` is completely broken.

I first noticed it while I was working on the Memory Game app.

It looks like the minifier we use works incorrectly with ES6 classes, since the first bad commit it this one: e0faaf589ee7da29da8af0637fc4ced8c7c75d78.

It might be that some other parts of Mavo are also broken for the same reason.

**Comment by LeaVerou** [comment]
Oh interesting, thanks Dmitry. Can we investigate what the minifier does with ES6 classes?

**Comment by DmitrySharabin** [comment]
Sure, Lea. I was planning to do that a bit later today. Will do my best to find a fix.

**Comment by DmitrySharabin** [comment]
Interesting observation: we know that `mavo.es5.min.js` is broken. However, after fixing the source maps (see PR #795), I found out that the problem was with this code:

https://github.com/mavoweb/mavo/blob/0ac85f6403230c7b0809050bb2140342758e75ec/src/mavo.js#L880-L907

Specifically, here is the error:

<img width="884" alt="Screen Shot 2021-11-25 at 12 28 44" src="https://user-images.githubusercontent.com/9166277/143415488-7b1e9d25-ae48-4d47-b0e8-2ebae15c0611.png">

However, replacing `let` with `var` in line 881 helped fix the error (not make the backends work correctly, though). 🤨

https://github.com/mavoweb/mavo/blob/0ac85f6403230c7b0809050bb2140342758e75ec/src/mavo.js#L881

The investigation is to be continued. 🤓

**Comment by DmitrySharabin** [comment]
The ES5 minified version breaks here:
https://github.com/mavoweb/mavo/blob/0ac85f6403230c7b0809050bb2140342758e75ec/src/mavo.js#L86

**Comment by DmitrySharabin** [comment]
It looks like the minifier we use removes class names. E.g., in the minified version, we get
```js
_.register(class extends _ {
        id = "Element";
```
instead of:
```js
_.register(class Element extends _ {
	id = "Element"
```
And later, when we try to use the name of a class (e.g., in the `Backend` class),
```js
static register (Class) {
	_[Class.name] = Class;
	_.types.push(Class);
	return Class;
}
```
we get an empty string, and as a result, the broken code.

Theoretically, we can [pass some parameters to the minifier](https://www.npmjs.com/package/gulp-babel-minify#usage):
```js
.pipe(minify({
      mangle: {
        keepClassName: true
      }
 }))
```
However, it _doesn't_ work the way it's written in the docs. 🤬 The way this parameter _should_ be applied is the following (I came up with the solution by chance, after millions of another tries):
```js
.pipe(minify({ mangle: false, keepClassName: true }))
```

The minified version is fixed! 🥳

Now, I need to find a fix for `mavo.es5.min.js`. It's still broken. And later, I'll finally able to submit a PR.

**Comment by LeaVerou** [comment]
Wow, thank you Dmitry, great work!

FIxing the minified version is still worthy, you could submit two PRs. 
Actually, feel free to just commit this kind of thing directly, no need for a PR 👍🏼

**Comment by DmitrySharabin** [comment]
I'm happy that I can help! It's an honor for me.

Now I can confirm that the issue is fully fixed. 🥳
