### ISSUE TITLE
Clicking on <a property> in edit mode actually visits the link

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#804]
Possibly related to #764

Testcase: https://codepen.io/leaverou/pen/oNGWdRP?editors=1100

This is pretty bad. It means not only people cannot make editable links, but also that they lose the other data they were editing, since we don't display a warning when navigating away with unsaved edits!

@DmitrySharabin since you worked on #764 do you want to take a look in case it's related?

**Comment by DmitrySharabin** [comment]
Yeah, that's exactly the issue I was trying to fix. I'm ready to give it another shot. And, yes, this issue is pretty annoying—it bit me many times.

**Comment by LeaVerou** [comment]
Since #764 is also not fixed, I'm gonna close this and let's track both there, since any fix for #764 should also address this.
