### ISSUE TITLE
Input type CHECKBOX displays wrong default value

### ISSUE THREAD

**Issue by GalinhaLX** [mavoweb/mavo#809]
hi

Input type checkbox with default value set to false displays true

<input type="checkbox" property="checkbox" mv-default="false" />

[https://codepen.io/GATIGA/pen/KKXbBYW](https://codepen.io/GATIGA/pen/KKXbBYW)

[https://codepen.io/GATIGA/pen/OJxrwrP](https://codepen.io/GATIGA/pen/OJxrwrP)

**Comment by LeaVerou** [comment]
If you change `mv-default="[false]"` it works fine. The problem with `mv-default="false"` is that it sets it to the *text* "false", not the `false` value and any text value that's not empty, is considered true.

@karger do you think we should special case the string "false"?
