### ISSUE TITLE
Custom data actions

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#81]
**Edit: [Current proposal here](https://github.com/mavoweb/mavo/issues/81#issuecomment-320482638)**

Currently, the controls to add/remove items in a collection and clear all data are hardcoded. Authors can include their own elements with the right classes and they will be picked up, or hide the existing ones with CSS, but the functionality is hardcoded and not particularly flexible. There should be a declarative API for specifying controls that mutate data, and then these buttons could just be a special case of that. This is more flexible and would enable things like custom data pruning (e.g. the "Clear completed" button in to-do lists). It would also automatically solve #66, #41, and #31.

The minimum elementary actions this should support are: Adding data, Deleting data, Editing the value of a property. It should also be able to specify actions that are composed of multiple such primitives.

Not sure about the syntax. It could be a microsyntax that is specified via a data attribute, such as:

``` html
<button data-action="add [someProperty] to propertyName, 
                     set myProperty to [foobar],
                     delete 5 from someCollectionProperty">Click me</button>`
```

or it could link to an HTML structure, such as:

``` html
<button data-action="#foo">Click me</button>
<mv-actions id="foo">
    <mv-action type="add" value="[someProperty]" property="propertyName">
    <mv-action type="edit" value="[foobar]" property="myProperty">
    <mv-action type="delete" value="5" property="someCollectionProperty">
</mv-actions>
```

**Comment by LeaVerou** [comment]
I think I finally have a solid proposal on how we can solve the data mutations problem.

Defining a new syntax is probably not a good idea. We have a lot of useful syntax in expressions already, and it makes it more complicated if people have to learn a different syntax for data mutations. We should re-use expression syntax with minimal expansions.

This proposal introduces an `mv-action` attribute, whose value is an expression. If the element is triggered, the expression will be evaluated (once). By default, elements are triggered through clicking, but future versions can introduce attributes to customize this (e.g. `mv-action-trigger` or `mv-action-on`). Until then, such clicks can always be triggered synthetically via JS to emulate other events. Elements with this attribute can also be named with `property` and referred to. 

It also introduces a few data modification functions that can only be used in such expressions:

- `add(property [, index [, data]])`: Adds an item to a collection, potentially with existing data and/or at a specific index. Returns the index of the new item.
- `delete(property)`: Clears a collection, deletes a collection item and/or clears data, depending on what is passed.
- `set(property, value)`: Sets a property to a given value
- `trigger(property)` triggers another `mv-action` element. This allows chaining of actions in different contexts (e.g. from outside a collection to inside a collection), which could result in more complex actions being defined.
- Potentially: `move()`, `harddelete()`?

Since these are just expressions, multiple actions can be chained via commas or semicolons.

Let’s look at a few examples of this syntax:

Use cases:
Clear completed: `delete(filter(task, done))`
Clear collection (#66): `delete(property)`
Move item to different collection from within item (#41): `add(property2, ?, delete(property1))`
Move item 3 to different collection from outside item (#41): `add(property2, ?, delete(property1[3]))`

Native Mavo controls:
- Mavo bar Clear button: `delete(mavoid)` or `delete($root)`
- Collection add new item button: `add(property)` for normal collections, `add(property, 0)` for bottom up collections
- Item bar delete button: `delete(property)`
- Item bar add button: `add(property, $index)` or `add(property, $index, property)` for clone (limitation: can't specify different behavior for when cmd/ctrl is held down which is the current behavior)
-

**Comment by karger** [comment]
Various issues here; I'm going to experiment with making different posts as a way to structure them.  I'll start with order of evaluation.  This is irrelevant in our current functional programs, but arises with mutation.   Suppose y is "global" to the evaluation scope and inside the evaluation scope there are two actions="set(y,y+1), set(foo,y)" and "set(y,y+1), set(bar,y)".  Then depending on order of evaluation we might have foo>bar or foo<bar.

**Comment by karger** [comment]
You focus on data modification actions but another generally useful action is to remember persist the value of an expression even if that value later changes.  This can be done using a "latch" triggered by a boolean expression.  For example, consider the problem of remembering the last modified time on an object.  We can do this with <div property="foo" value="currentTime()" update="modified"> with the semantics being that whenever the property "modified" becomes true then foo gets updated with the (current) value of currentTime.  But this only happens at the instant modified becomes true; the value of foo is now unchanging as modified continues to be true, and also doesn't change if modified later becomes false, but will change again when modified becomes true again.

**Comment by karger** [comment]
You argue that we should not add syntax, but it isn't clear how adding new primitive functions differs from adding syntax.  In particular we could keep expressions purely functional if we used html attributes to express the mutations e.g. <mv-delete-if="expr"> could specify to delete the given item any time expr becomes true.  Not clear this is better than using exprs but it may be worth exploring.

**Comment by karger** [comment]
with the primitive functions you added along with sequencing by commas, it becomes possible to write arbitrary programs inside an expression.  This worries me.   For example infinite loops are now easy to generate and cannot be detected (halting problem).  Also, there is now nothing to stop users from writing painfully complex code that other users won't be able to understand.    Maybe spreadsheets' requirement to switch to scripting is actually a good thin because it enforces KISS in basic expressions?

**Comment by LeaVerou** [comment]
Thanks for the feedback! Answers below.

> Various issues here; I'm going to experiment with making different posts as a way to structure them. 

I don't think it helps, since there is no threading here. You can use headings and/or numbers to structure them.

> I'll start with order of evaluation. This is irrelevant in our current functional programs, but arises with mutation. Suppose y is "global" to the evaluation scope and inside the evaluation scope there are two actions="set(y,y+1), set(foo,y)" and "set(y,y+1), set(bar,y)". Then depending on order of evaluation we might have foo>bar or foo<bar.

Not sure I follow. The two actions would have to be triggered by two different user actions. **These functions would not be available in normal expressions**! Normal expressions would continue to be restricted to side effect free functions. 

> You focus on data modification actions but another generally useful action is to remember persist the value of an expression even if that value later changes. This can be done using a "latch" triggered by a boolean expression. For example, consider the problem of remembering the last modified time on an object. [...]

There are many useful things we could do, but this issue is about one of them :) I would argue that data modification actions are far more useful than latches, except for those cases where the two overlap. I mean, even the use case you mention is a bit niche, compared to the generality of the use case "Press a button and set a value". 

> You argue that we should not add syntax, but it isn't clear how adding new primitive functions differs from adding syntax. 

Syntax has to be learned from scratch and cannot be googled, different names of known concepts can be looked up from an index. IMO this one big reason why languages like spreadsheets, HTML, and to some degree CSS (especially CSS 2.1 or earlier) are generally much easier than programming languages: The syntax is simple, with a large vocabulary. In spreadsheets, the main syntactic construct one has to learn is the function call. Everything is a function, all they need to look up is which function they need. Same with HTML: Once they learn what a tag is and what an attribute is, everything just becomes a matter of finding the right tag. 

> In particular we could keep expressions purely functional if we used html attributes to express the mutations e.g. <mv-delete-if="expr"> could specify to delete the given item any time expr becomes true. Not clear this is better than using exprs but it may be worth exploring.

We have briefly explored this and it's a bit of a dead end when it comes to adding collection items, and some property change operations (e.g. your increment example). Basically anything where the result would change with repeated execution. **Perhaps the problem is that we are trying to force a declarative approach on an inherently imperative operation?**

Even with delete which is simpler to implement this way, it gets tricky to do right. Let's assume we want to put a "Clear collection" button (`property=clear`) for collection items with `property=item`.

```html
<button property="clear">Clear</button>
<div property="item" mv-delete-if="delete > 0">
</div>
```

On the first press, the button works just fine. However, now we cannot add any items to the collection because the button has been pressed and we have no way to set it to 0!

Also this approach requires to put the code for the action on the collection item itself, which doesn't seem like a good separation of concerns to me and gets more and more complicated the more actions that are added (same with filtering).

> with the primitive functions you added along with sequencing by commas, it becomes possible to write arbitrary programs inside an expression.

That is already possible, since people can always switch to JS.

> This worries me. For example infinite loops are now easy to generate and cannot be detected (halting problem).

Infinite loops are already easy!

```html
<div property="a">[b + 1]</div>
<div property="b">[a + 1]</div>
```

In fact, I don't see any more ways to trigger them that these functions add, except cycles with `trigger()`.

> Also, there is now nothing to stop users from writing painfully complex code that other users won't be able to understand.

Such as? I really don't see how these 4 functions increase complexity more than any other 4 functions.

**Comment by RubenVerborgh** [comment]
I think you nailed it with “force a declarative approach on an inherently imperative operation”. Mutations introduce state, and this is why the mismatch happens. I'll think about this some more and see if I can suggest alternative directions.

**Comment by karger** [comment]
We've been regretting using [] for exprs instead of the more standard {}  I suspect that using , for statement separators instead of ; may lead to similar regrets?

I also wonder whether novices will be able to handle the inconsistency that certain functions work in mutation exprs but not in regular exprs

regarding your "delete > 0" clear collection example.  Having the button count its presses was a cute hack, but it doesn't really reflect actual button semantics.  If we use a latch, then the value of a button can be true while it's being clicked and false at all other times---and various actions can be triggered by the button becoming true.   Similar for actions triggered by hovering over an item, etc.    Actually, this may be a good time to read arvind satyanarayan's papers on his declarative language for input event streams.

**Comment by LeaVerou** [comment]
> We've been regretting using [] for exprs instead of the more standard {}

I’ve been having second thoughts about it, sure, but I’m not 100% convinced it was a bad idea. I still think [] is more readable than {}. I wouldn't say any of them are more "standard" though. If anything is more standard, it's `{{ }}` (two braces), which I find horrible.

And the cost of switching to `{ }` for authors is minimal: Just `mv-expressions="{ }"`, done. It can even be scoped to elements.

> I suspect that using , for statement separators instead of ; may lead to similar regrets?

Comma is a JS operator, not something I'd implement myself. It comes for free. Both that and semicolons would work. I just think that comma could be more readable in this case.

> I also wonder whether novices will be able to handle the inconsistency that certain functions work in mutation exprs but not in regular exprs

That's a legitimate concern, but not sure it's serious enough to not offer this functionality (and offering it in expressions doesn't make sense). FWIW, CSS now has selectors that don't work in certain contexts.

> regarding your "delete > 0" clear collection example. Having the button count its presses was a cute hack, but it doesn't really reflect actual button semantics. If we use a latch, then the value of a button can be true while it's being clicked and false at all other times---and various actions can be triggered by the button becoming true. Similar for actions triggered by hovering over an item, etc. 

I think these two ideas are orthogonal. You’re talking about how to specify what triggers the action, whereas I was talking about how to specify **what the action does**. 

> Actually, this may be a good time to read arvind satyanarayan's papers on his declarative language for input event streams.

I just read the Reactive Vega one, it seemed closer to this, feel free to suggest another if needed. Interesting work, but the relevant bits are the event streams, and like I said above, the *when* it happens is orthogonal to *what* happens. This thread is about the latter. We can figure out how to specify the *when* later and just start with clicks which cover a large percentage of use cases that are basically **impossible** now (without a fair bit of JS).

**Comment by LeaVerou** [comment]
@karger Actually, the [Vega website](https://vega.github.io/vega/docs/triggers/) is more informative than any particular paper. At first glance, it seems that for data mutations they do have a similar language to what I'm proposing here, except instead of functions it's properties and is less powerful. I need to look more into this.

**Comment by karger** [comment]
In terms of js stuff that comes for free, technically we don't need to 
do anything special for "what the action does" so long as the data model 
is exposed as js objects in the scope of expressions (I believe it is, 
right?).  i.e., mutation can be done with standard js assignments like 
"name=inputFieldValue".

So if that's true, then the question becomes: what do we want to provide 
a distinct syntax for so that novices don't have to work with js exprs.  
but it's worth asking: is for example set(a,b) more natural for our 
target non-programmers than a=b?   likely yes, but may be worth checking.

I agree with the distinction between the trigger and the action, but I 
was mulling over the idea of keeping the options for actions absolutely 
minimal (set property/delete property, add/remove item) and having all 
the complexity be in the (functional, side-effect-free) expressions that 
specify the value to set/add. in which case, the trigger is the crux of 
the matter since it determines *when* the values of those exprs are 
evaluated and used to update.  If we went this route, I think it would 
be natural to have the few available operations get their own 
attributes, e.g. <property=foo value="expr" update-when="trigger">, 
<delete-when="trigger">, <add-when="trigger">

**Comment by LeaVerou** [comment]
> In terms of js stuff that comes for free, technically we don't need to
do anything special for "what the action does" so long as the data model
is exposed as js objects in the scope of expressions (I believe it is,
right?).  i.e., mutation can be done with standard js assignments like
"name=inputFieldValue".

Property names etc in expressions correspond to **data**, not Mavo tree nodes. Even if modifications to this data were allowed (they currently are not), they do not transfer to the actual Mavo tree. On purpose, since expressions need to be side effect free. You can go from the data to the nodes, via a hidden symbol property, but this is not meant to be easy, on purpose. I could of course code it so that in such actions, property names and all return Mavo nodes, but then getting the data and applying functions to the data would become harder. We can't have it both ways, the property names need to either return data OR code, they can't return both.

> So if that's true, then the question becomes: what do we want to provide
a distinct syntax for so that novices don't have to work with js exprs.
but it's worth asking: is for example set(a,b) more natural for our
target non-programmers than a=b?   likely yes, but may be worth checking.

While there is a JS API, it's rather low level and is not designed to be used by novices, but by plugin authors and Mavo's internals. The functions I proposed would be high level and would do something useful in most cases, with minimal syntax and would be designed to work with the data that's already available in expressions. It's not about whether `set(a, b)` is easier than `a = b` (I doubt it), but whether `foo.bar.baz.splice(i, 0, abc.ced[j])` is easier than `add(baz, i, ced)`. And even the former isn't currently possible with the JS API, it's more like `foo.children.bar.children.baz...`;
And since when do we think it's a good idea to have novices just use a JS API? Especially for something so commonly needed?! Unless our disagreement may be that you don't consider this essential enough. In that case, I could compile a longer list of use cases that may convince you.

> I agree with the distinction between the trigger and the action, but I
was mulling over the idea of keeping the options for actions absolutely
minimal (set property/delete property, add/remove item) and having all
the complexity be in the (functional, side-effect-free) expressions that
specify the value to set/add.

I would be delighted to discuss alternative paths, but it would be good if you explained **why** you believe this might be a better approach, beyond theoretical purity. Does it address more use cases? Do we even have enough use cases with complex triggers? In most of the use cases I personally encounter the trigger is a simple click and the complexity is in specifying the data mutations. I’m not saying that use cases with complex triggers don't exist, but they seem way less common, at least in non data visualization contexts. And many of the use cases that exist seem way less crucial, e.g. compare moving items to the cart (click trigger, complexity is in the data mutation) to some mouseover effect. And even for those cases, it's much easier for those that do know JS to code up a custom event and `.click()` the existing click-based trigger than to perform complex data mutations with a JS API.

**Comment by LeaVerou** [comment]
> You focus on data modification actions but another generally useful action is to remember persist the value of an expression even if that value later changes. This can be done using a "latch" triggered by a boolean expression. For example, consider the problem of remembering the last modified time on an object. [...]

@karger Actually, re-reading this thread, I just wanted to say that [my proposal above](https://github.com/mavoweb/mavo/issues/81#issuecomment-320482638) also covers this case, just use `mv-action="set(property, value)"` and that property will only be updated when the action is triggered (you can also give it `mv-move="read"` to prevent it from becoming editable by the end user). Of course if clicking is the only trigger, then you can't implement your last modified use case, but that's rather specific.

**Comment by LeaVerou** [comment]
Closing this, since data actions have been implemented. We are tracking improvements to the syntax in #334.
