### ISSUE TITLE
Mavo bar should be inserted in <body> when mv-app is on <html>

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#830]
There is literally *no* use case where authors would want the Mavo bar to be inserted as a direct child of `<html>` before `<head>` and even if there were, they can override the default placement by using their own element.

**Comment by Harixomxsingh** [comment]
hey, i am interest to contribute this issue

**Comment by Trevy05** [comment]
Is this still open?

**Comment by RamGoel** [comment]
@LeaVerou Assign me this issue please.

**Comment by LeaVerou** [comment]
Hello, we do not assign issues to people who have never contributed before. You can submit a PR if you want to work on it. Thanks for your interest!

**Comment by vrindavan** [comment]
Can you tell me a bit about where or which files to edit? I suppose the Mavo.js?
