### ISSUE TITLE
mv-alias doesn't work on mv-multiple

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#846]
Testcase: https://codepen.io/leaverou/pen/XWZXyKy?editors=1100

Haven't checked but probably the fix is just one line: move `mv-alias` to `mv-list` element when rewriting `mv-multiple`. I bet we don't do anything with it now.

**Comment by DmitrySharabin** [comment]
Fixed with https://github.com/mavoweb/mavo/commit/6f82b9d172fb5cf19c70bb0d3d148adc1d9e02d3.
