### ISSUE TITLE
If property `foo` hasn't a default value, expression `[foo]` is not evaluated before `foo` is changed somehow

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#916]
Testcase: https://codepen.io/dmitrysharabin/pen/zYjYQQb

It looks like a regression that might cause a lot of issues. E.g., `mv-if="!foo"` won't hide a node from the very beginning.

`git bisect` showed this commit 4a03c5969a137cf116c93a9aae27ce33f29bf517 as the first bad one.

**Comment by LeaVerou** [comment]
Do you want to investigate why? Clearly the code thinks the expression hasn't changed and is not updating it. Why does this happen?

**Comment by DmitrySharabin** [comment]
Sure. Will do my best!
