### ISSUE TITLE
How to insert DOM contents in Mavo Nodes?

### ISSUE THREAD

**Issue by jhonatan-dev** [mavoweb/mavo#942]
![image](https://user-images.githubusercontent.com/109216109/209673112-2b5fe7f3-b6b3-4274-85bd-6f71f4d68bc7.png)
I have tried to insert DOM content in Mavo Nodes from the text type property.
<template property="text"></template>
Is there any options to show the DOM content from strings?
```
"<b>Size of the text</b>:&nbsp;&nbsp;&nbsp;<br><b>List of keywords matching the curriculum</b>:&nbsp;&nbsp;&nbsp;<br><b>List of difficult words</b>:&nbsp;&nbsp;&nbsp;<br><b>Exact curriculum keywords</b>:&nbsp;&nbsp;&nbsp;<br><b>Synonyms of keywords used</b>:&nbsp;&nbsp;&nbsp;"
```
I want to insert this string like 
```
<div>
 <b>Size of the text</b>:&nbsp;&nbsp;&nbsp;<br><b>List of keywords matching the curriculum</b>:&nbsp;&nbsp;&nbsp;<br><b>List of difficult words</b>:&nbsp;&nbsp;&nbsp;<br><b>Exact curriculum keywords</b>:&nbsp;&nbsp;&nbsp;<br><b>Synonyms of keywords used</b>:&nbsp;&nbsp;&nbsp;
</div>
```

**Comment by DmitrySharabin** [comment]
Hey there,

If I'm not mistaken, this is impossible. But I would suggest a workaround if you are OK with replacing HTML with Markdown. If so, [the Markdown plugin](https://plugins.mavo.io/plugin/markdown) could help. Actually, [the Mavo docs](https://github.com/mavoweb/mavo.io/blob/master/docs/index.html) are built on top of this plugin.

However, I'm not sure whether you can use the `<template>` element to achieve your goal. 🤷🏻‍♂️

**Comment by jhonatan-dev** [comment]
That works pretty! Just using the Markdown plugin, I can insert DOM contents now. But it doesn't work with `<template>`. 
![image](https://user-images.githubusercontent.com/109216109/209692500-d1ad5222-cab1-428d-8e06-d2a35044e42e.png)
Awesome!

**Comment by karger** [comment]
If I understand the question correctly, another option would be to leverage the fact that arbitrary javascript functions can be invoked inside a mavo expression.  You could write a one-line javascript function
`function getText(selector) { return document.querySelector(selector).textContent }`
then say something like `<div property="text" mv-value="getText('#myId')"`

I put an example here: https://codepen.io/karger/pen/YzjwxMw
