### ISSUE TITLE
`mv-accepts` implements precisely the opposite logic than it's stated in the docs

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#969]
Instead of [accepting items from the specified collections](https://mavo.io/docs/collections#mv-accepts), _those_ collections accept items from the _current_ one.

Testcase: https://codepen.io/dmitrysharabin/pen/gOZxJZO?editors=1100

The testcase is built with the stable version of Mavo because we don't want [the issue we are already aware of](https://github.com/mavoweb/mavo/issues/738) interfere with this one.

It looks like we have had this issue for a long time.

**Comment by LeaVerou** [comment]
Is this how it always worked, or is it a regression?
I guess we may have never noticed because it's usually used symmetrically 🤣

**Comment by DmitrySharabin** [comment]
> Is this how it always worked, or is it a regression?

I played a bit with `git bisect` and looked through the `collection.js` file history, and it looks like it always worked this way. 😅

**Comment by LeaVerou** [comment]
Do you want to fix it before we tackle #738? It looks like it should be a fairly easy fix.

**Comment by DmitrySharabin** [comment]
Sure! Will give it a try ASAP.
