### ISSUE TITLE
Page Regression

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#978]
This is not working anymore with the current Mavo version, all items are hidden regardless of applied filters: https://drafts.csswg.org/issues.html?spec=css-images-3&doc=cr-2012
It appears that 

@DmitrySharabin could you bisect please? 

It appears that the issue is that `if(and(shown), '', 'filtered')` returns an array of several `filtered` values, even if the entry should not actually be filtered.
Not sure if bug or due to some change in semantics since this app was created (if the latter, I can update the code)

**Comment by DmitrySharabin** [comment]
It looks like this is the first bad commit: 8efa850e6f3563fedc123c704914d34fbbe62114.

**Comment by DmitrySharabin** [comment]
This changes (lines 66–68) fixes the app:

```html
<meta property="shown" content="{condense(filter(openFilter, openFilter.id = openness).show)}" />
<meta property="shown" content="{!status or condense(filter(statusFilter, statusFilter.id = status).show)}" />
<meta property="shown" content="{!count(selectedTags) or intersects(tag, selectedTags)}" />
```

**Comment by DmitrySharabin** [comment]
@LeaVerou, I can send a PR with the fix if you like. It would be nice if we could fix it since it's one of the first Mavo in the Wild demos we showcase on our site.

**Comment by LeaVerou** [comment]
I will fix it

**Comment by LeaVerou** [comment]
Done

**Comment by DmitrySharabin** [comment]
Yay! 🥳 Thank you. 

I just checked. Everything works like a charm.
