### ISSUE TITLE
Properties with empty `property` attributes share the same name

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#979]
E.g.,

```html
<p property>Foo</p>
<p property>Bar</p>
```

will be transformed by Mavo to

```html
<p property="prop">Foo</p>
<p property="prop">Bar</p>
```

instead of

```html
<p property="prop">Foo</p>
<p property="prop1">Bar</p>
```

For some reason (probably because, in most cases, authors give their properties explicit names), we didn't notice this for two years. 😱

Luckily, it's an easy fix: we need to get rid of _the spread operator_ in the following line.

https://github.com/mavoweb/mavo/blob/d4d3bdd265e207ec7470b3a7ac5a41bf09b08627/src/node.js#L519

@LeaVerou, if you don't mind, I can commit it directly.

**Comment by LeaVerou** [comment]
Sure! Thanks for tracking this down!
