### ISSUE TITLE
Hide the edit and save panel

### ISSUE THREAD

**Issue by TTYYCccc** [mavoweb/mavo#983]
This project is so good for beginners like me to do some simple html programming, but when I want to show my html to my schoolmates, the panel to control edit and save mode on top of the html seems not in keeping with other contents. I wonder is there some ways to hide this panel or change its shape so I can rearrange the page layout? Anyway, this project makes programming much easier, and I like it very much:)

**Comment by LeaVerou** [comment]
Thank you, glad you like it!

I’m not quite sure I understand what you're trying to do, but I think it's one of the following:
1. Hide the toolbar completely? If so, you can use `mv-bar="none"` would do what you need
2. Hide the toolbar when you're logged out? If so, you can use `mv-bar="no-login"` 
3. The toolbar is somehow breaking your layout? If so, we need more details!

You can read more about 1 and 2 here: https://mavo.io/docs/ui#bar

**Comment by TTYYCccc** [comment]
1 is exactly what I need. Thank you!
