### ISSUE TITLE
A backend specified via the URL should have priority over backend metadata passed via storage attributes

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#984]
As we state [in the docs](https://mavo.io/docs/storage#url-params), the user can change the storage location of any Mavo app via the URL.

On the other hand, the author can configure the backend they use via [storage attributes](https://mavo.io/docs/storage#storage-attributes). And **those attributes have priority** over metadata Mavo can get by parsing the storage URL.

In most cases, that works perfectly fine. However, those storage attributes **also have priority over the URL** the user might pass to override the default storage. Consequently, the user might be unable to store their data in the file specified via the URL. So, it might break the brilliant idea of re-using apps.

For example, suppose the page with our app has the URL `https://mavo.app`, and the app is defined like so:

```html
<div mv-app mv-storage="https://github.com/mavoweb/mavo.io/docs/docs.json" mv-storage-branch="master">
	<!-- Our awesome app -->
</div>
```

This app has the following `primaryBackend` (mind `branch` and `source`):

<img width="903" alt="image" src="https://github.com/mavoweb/mavo/assets/9166277/a3461e70-0c98-46b8-ab82-ade4796a6bdd">

If we then want to work with data stored in another branch on the same repo, we can pass the file URL via the `storage` URL param like so: `https://mavo.app?storage=https://github.com/mavoweb/mavo.io/blob/road-to-0.3.0/docs/docs.json` (mind that the branch name—`road-to-0.3.0`—is in the URL).

However, the `branch` property of the `primaryBackend` didn't change (since the storage attributes have priority):

<img width="1036" alt="image" src="https://github.com/mavoweb/mavo/assets/9166277/84272de3-83e2-4b2b-ada2-5e7e3b37a8bc">

That means that Mavo will store data in the file with the following URL: `https://github.com/mavoweb/mavo.io/blob/master/docs/docs.json` which is (technically) equivalent to `https://github.com/mavoweb/mavo.io/docs/docs.json` (the same URL that we provided authoring the app). As a result, **we couldn't override the app's storage**.

**Comment by DmitrySharabin** [comment]
It feels like this issue should be fixed before releasing `v0.3.0`. But I might be mistaken since nobody reported it since `v0.2.0` (when we introduced the storage attributes). 😅

**Comment by joyously** [comment]
> But I might be mistaken since nobody reported it
 
Please don't assume you have enough users to be able to use that argument. 
I think I ran into this when trying to write a storage backend, but I had other issues too, so didn't know what it was supposed to do. I might have reported it if I better understood how it _should_ work.

**Comment by LeaVerou** [comment]
I suspect this will be pretty easy to fix, in which case we *could* get it in before v0.3.0. If it's nontrivial, then it should probably wait. @DmitrySharabin would you mind taking a look?

**Comment by DmitrySharabin** [comment]
>  @DmitrySharabin would you mind taking a look?

Sure! Was going to. :)

**Comment by DmitrySharabin** [comment]
@LeaVerou, I came up with a solution. Requested a review from you. Could you please take a look?
