### ISSUE TITLE
[Chore] Rename master to main

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#987]
'Tis the way.

**Comment by DmitrySharabin** [comment]
Not to forget, we also should remove `mv-storage-branch="master"` from all the pages on our site after we do this.

**Comment by DmitrySharabin** [comment]
> @DmitrySharabin can you do that? I've just renamed master to main, not just in this repo, but across all our mavo.io sites.

Sure! Will do it now.

**Comment by DmitrySharabin** [comment]
Done! Also fixed deploy options on Netlify.

**Comment by LeaVerou** [comment]
> Done! Also fixed deploy options on Netlify.

Thanks! For all of them?

**Comment by DmitrySharabin** [comment]
> Thanks! For all of them?

I believe yes: `mavo.io`, `dev.mavo.io`, `get.mavo.io`, `test.mavo.io`, `plugins.mavo.io`.
Any other?

**Comment by LeaVerou** [comment]
Nope, I believe that's it!
